### ISSUE TITLE
Color bar legend for py3Dmol IDDT scores

### ISSUE THREAD

**Issue by demattox** [sokrypton/ColabFold#1]
Great tool and interface, many thanks to everyone involved!

One small suggestion to help folks interpret and judge model quality quickly from browser:
Would it be possible to add a color bar to the py3Dmol structure preview for the IDDT colors? It would go a long ways towards judging model quality, especially at regions of particular interest, without requiring users to have PyMol expertise or to try and match residue numbers between the IDDT plot and the structure.

Thanks again!

**Comment by sokrypton** [comment]
Good suggestion! @dkoes says he'll add this feature to py3Dmol! :)

**Comment by dkoes** [comment]
Sorry to take so long to get around to this.   I've added the ability to give a label a background gradient.  You can make a colorbar like this:

```
import py3Dmol
p = py3Dmol.view(query='pdb:4ycv')
p.setStyle({'cartoon':{'colorscheme':{'prop':'b','gradient':'rwb','min':40,'mid':70,'max':90}}});
p.addLabel("50                                   90",
           {'position':{'x':0,'y':0,'z':0},'useScreen': True, 'fontSize': 12, 
            'borderThickness': 0.5, 'borderColor': 'black', 
            'backgroundGradient': {'gradient':'rwb','min':40,'mid':70,'max':90}})
```
