### ISSUE TITLE
Input format of complexes while running locally with colabfold_batch

### ISSUE THREAD

**Issue by marcmk6** [sokrypton/ColabFold#103]
Hi,
With the Colab notebook [AlphaFold2_mmseqs2](https://colab.research.google.com/github/sokrypton/ColabFold/blob/main/AlphaFold2.ipynb) I can use a colon `:`  to specify inter-protein chainbreaks as per instruction. I'm wondering what should I do when running with `colabfold_batch` locally.

Specifically I tried writing the following
>\>sp|Q9UI25|YP002_HUMAN Putative uncharacterized protein PRO0461 OS=Homo sapiens OX=9606 GN=PRO0461 PE=5 SV=1
>MEEMSYGENSGTHVGSFSCSPQPSQQMKVLFVGNSFLLTPVLHRQPHLQPCNFGPEVVAP
>QRL

into a fasta file inside directory tmp and run `colabfold_batch --model-type AlphaFold2-multimer tmp tmp_output` but got an error.

Here is the error log:
>Traceback (most recent call last):
>  File "/home/jovyan/.conda/envs/colabfold_test_env/lib/python3.8/site-packages/ml_collections/config_dict/config_dict.py", line 883, in __getitem__
>    field = self._fields[key]
>KeyError: 'data'
>
>During handling of the above exception, another exception occurred:
>
>Traceback (most recent call last):
>  File "/home/jovyan/.conda/envs/colabfold_test_env/lib/python3.8/site-packages/ml_collections/config_dict/config_dict.py", line 807, in __getattr__
>    return self[attribute]
>  File "/home/jovyan/.conda/envs/colabfold_test_env/lib/python3.8/site-packages/ml_collections/config_dict/config_dict.py", line 889, in __getitem__
>    raise KeyError(self._generate_did_you_mean_message(key, str(e)))
>KeyError: "'data'"
>
>During handling of the above exception, another exception occurred:
>
>Traceback (most recent call last):
>  File "/home/jovyan/.conda/envs/colabfold_test_env/bin/colabfold_batch", line 8, in <module>
>    sys.exit(main())
>  File "/home/jovyan/.conda/envs/colabfold_test_env/lib/python3.8/site-packages/colabfold/batch.py", line 1209, in main
>    run(
>  File "/home/jovyan/.conda/envs/colabfold_test_env/lib/python3.8/site-packages/colabfold/batch.py", line 998, in run
>    outs, model_rank = predict_structure(
>  File "/home/jovyan/.conda/envs/colabfold_test_env/lib/python3.8/site-packages/colabfold/batch.py", line 184, in predict_structure
>    input_features = batch_input(
>  File "/home/jovyan/.conda/envs/colabfold_test_env/lib/python3.8/site-packages/colabfold/batch.py", line 122, in batch_input
>    eval_cfg = model_config.data.eval
>  File "/home/jovyan/.conda/envs/colabfold_test_env/lib/python3.8/site-packages/ml_collections/config_dict/config_dict.py", line 809, in __getattr__
>    raise AttributeError(e)
>AttributeError: "'data'"

**Comment by konstin** [comment]
Hi, could you please post the error and the log?

**Comment by marcmk6** [comment]
> Hi, could you please post the error and the log?

Hi, I've added the log to the post.

**Comment by liuqs1990** [comment]
> Hi, could you please post the error and the log?

Hi Konstin,

I have almost the same problem when running the localcolabfold.
The error is described here:
[https://github.com/YoshitakaMo/localcolabfold/issues/69
](URL)

I am able to run with a single protein locally but always have error when trying to predict the complex structure.

any suggestions would be grateful.
