### ISSUE TITLE
Input format of complexes while running locally with colabfold_batch

### ISSUE THREAD

**Issue by marcmk6** [sokrypton/ColabFold#104]
Hi,
With the Colab notebook [AlphaFold2_mmseqs2](https://colab.research.google.com/github/sokrypton/ColabFold/blob/main/AlphaFold2.ipynb) I can use a colon to specify inter-protein chainbreaks as per instruction. I'm wondering what should I do when running with `colabfold_batch` locally.

Specifically I tried writing the following
>\>sp|Q9UI25|YP002_HUMAN Putative uncharacterized protein PRO0461 OS=Homo sapiens OX=9606 GN=PRO0461 PE=5 SV=1
>MEEMSYGENSGTHVGSFSCSPQPSQQMKVLFVGNSFLLTPVLHRQPHLQPCNFGPEVVAP
>QRL

into a fasta file inside directory tmp and run `colabfold_batch --model-type AlphaFold2-multimer tmp tmp_output` but got an error.

Here is the error log:
>Traceback (most recent call last):
>  File "/home/jovyan/.conda/envs/colabfold_test_env/lib/python3.8/site-packages/ml_collections/config_dict/config_dict.py", line 883, in __getitem__
>    field = self._fields[key]
>KeyError: 'data'
>
>During handling of the above exception, another exception occurred:
>
>Traceback (most recent call last):
>  File "/home/jovyan/.conda/envs/colabfold_test_env/lib/python3.8/site-packages/ml_collections/config_dict/config_dict.py", line 807, in __getattr__
>    return self[attribute]
>  File "/home/jovyan/.conda/envs/colabfold_test_env/lib/python3.8/site-packages/ml_collections/config_dict/config_dict.py", line 889, in __getitem__
>    raise KeyError(self._generate_did_you_mean_message(key, str(e)))
>KeyError: "'data'"
>
>During handling of the above exception, another exception occurred:
>
>Traceback (most recent call last):
>  File "/home/jovyan/.conda/envs/colabfold_test_env/bin/colabfold_batch", line 8, in <module>
>    sys.exit(main())
>  File "/home/jovyan/.conda/envs/colabfold_test_env/lib/python3.8/site-packages/colabfold/batch.py", line 1209, in main
>    run(
>  File "/home/jovyan/.conda/envs/colabfold_test_env/lib/python3.8/site-packages/colabfold/batch.py", line 998, in run
>    outs, model_rank = predict_structure(
>  File "/home/jovyan/.conda/envs/colabfold_test_env/lib/python3.8/site-packages/colabfold/batch.py", line 184, in predict_structure
>    input_features = batch_input(
>  File "/home/jovyan/.conda/envs/colabfold_test_env/lib/python3.8/site-packages/colabfold/batch.py", line 122, in batch_input
>    eval_cfg = model_config.data.eval
>  File "/home/jovyan/.conda/envs/colabfold_test_env/lib/python3.8/site-packages/ml_collections/config_dict/config_dict.py", line 809, in __getattr__
>    raise AttributeError(e)
>AttributeError: "'data'"

**Comment by liuqs1990** [comment]
> Hi, With the Colab notebook [AlphaFold2_mmseqs2](https://colab.research.google.com/github/sokrypton/ColabFold/blob/main/AlphaFold2.ipynb) I can use a colon to specify inter-protein chainbreaks as per instruction. I'm wondering what should I do when running with `colabfold_batch` locally.
> 
> Specifically I tried writing the following
> 
> > >sp|Q9UI25|YP002_HUMAN Putative uncharacterized protein PRO0461 OS=Homo sapiens OX=9606 GN=PRO0461 PE=5 SV=1
> > MEEMSYGENSGTHVGSFSCSPQPSQQMKVLFVGNSFLLTPVLHRQPHLQPCNFGPEVVAP
> > QRL
> 
> into a fasta file inside directory tmp and run `colabfold_batch --model-type AlphaFold2-multimer tmp tmp_output` but got an error.
> 
> Here is the error log:
> 
> > Traceback (most recent call last):
> > File "/home/jovyan/.conda/envs/colabfold_test_env/lib/python3.8/site-packages/ml_collections/config_dict/config_dict.py", line 883, in **getitem**
> > field = self._fields[key]
> > KeyError: 'data'
> > During handling of the above exception, another exception occurred:
> > Traceback (most recent call last):
> > File "/home/jovyan/.conda/envs/colabfold_test_env/lib/python3.8/site-packages/ml_collections/config_dict/config_dict.py", line 807, in **getattr**
> > return self[attribute]
> > File "/home/jovyan/.conda/envs/colabfold_test_env/lib/python3.8/site-packages/ml_collections/config_dict/config_dict.py", line 889, in **getitem**
> > raise KeyError(self._generate_did_you_mean_message(key, str(e)))
> > KeyError: "'data'"
> > During handling of the above exception, another exception occurred:
> > Traceback (most recent call last):
> > File "/home/jovyan/.conda/envs/colabfold_test_env/bin/colabfold_batch", line 8, in 
> > sys.exit(main())
> > File "/home/jovyan/.conda/envs/colabfold_test_env/lib/python3.8/site-packages/colabfold/batch.py", line 1209, in main
> > run(
> > File "/home/jovyan/.conda/envs/colabfold_test_env/lib/python3.8/site-packages/colabfold/batch.py", line 998, in run
> > outs, model_rank = predict_structure(
> > File "/home/jovyan/.conda/envs/colabfold_test_env/lib/python3.8/site-packages/colabfold/batch.py", line 184, in predict_structure
> > input_features = batch_input(
> > File "/home/jovyan/.conda/envs/colabfold_test_env/lib/python3.8/site-packages/colabfold/batch.py", line 122, in batch_input
> > eval_cfg = model_config.data.eval
> > File "/home/jovyan/.conda/envs/colabfold_test_env/lib/python3.8/site-packages/ml_collections/config_dict/config_dict.py", line 809, in **getattr**
> > raise AttributeError(e)
> > AttributeError: "'data'"

I have the same issue. did you solve the problem?

Thanks.
