### ISSUE TITLE
Question regarding "use template"

### ISSUE THREAD

**Issue by epitope-ucph** [sokrypton/ColabFold#109]
Hi! Quite new to alphafold, enjoying your script a lot!

Could you explain the "use template" function? I can see it requires the hhsuite and kalign in the code. If, say, I have Protein A, and a crystal structure for Protein A already exists.

If "use template = false", the structure of Protein A will only be based on the trained neural network.

if "use template= true", the structure of Protein A will be heavily biased by the crystal structure?

Cheers,

**Comment by martin-steinegger** [comment]
HHsearch is used to align templates detected by a MMseqs2. Please read our [preprint](https://www.biorxiv.org/content/10.1101/2021.08.15.456425v2) for more details on how we select templates. If a crystal structures exists, we will build input features from the template alignment and provide it additionally to the MSA. In default only the MSA is used a input feature.
