### ISSUE TITLE
retrieving pTM score

### ISSUE THREAD

**Issue by grandrea** [sokrypton/ColabFold#112]
I know the pTM is printed to stdout during a run... but is there anywhere the pTM per model is stored post-run?

**Comment by martin-steinegger** [comment]
The `AlphaFold2_mmseqs`, `colabfold_batch` notebook provides now a json file with the respective scores. Here is an example how to parse the json https://github.com/sokrypton/ColabFold/blob/main/utils/plot_scores.ipynb
