### ISSUE TITLE
Issue with float/integer

### ISSUE THREAD

**Issue by MetalDictator** [sokrypton/ColabFold#119]
Alphafold-multimer used to run fine last week and over the weekend. Since this morning, I get the following error message:

"/usr/local/lib/python3.7/dist-packages/colabfold/colabfold.py:18: TqdmExperimentalWarning: Using `tqdm.autonotebook.tqdm` in notebook mode. Use `tqdm.tqdm` instead to force console mode (e.g. in jupyter console)
  from tqdm.autonotebook import tqdm
Downloading alphafold2 weights to .: 100%|██████████| 3.82G/3.82G [01:05<00:00, 63.0MB/s]
2021-12-06 09:53:08,724 Running colabfold 1.2.0 (1b8f14dd8d03aaa3e88c4df8b95bd96a3613c35b)
2021-12-06 09:53:08,727 Found 5 citations for tools or databases
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
/usr/local/lib/python3.7/dist-packages/ml_collections/config_dict/config_dict.py in __setitem__(self, key, value)
    832             value = ConfigDict(value, self._type_safe)
--> 833           value = _safe_cast(value, type(field), self._type_safe)
    834       except TypeError as e:

5 frames
TypeError: 100.0 is of type <class 'float'> but should be of type <class 'int'>

During handling of the above exception, another exception occurred:

TypeError                                 Traceback (most recent call last)
/usr/local/lib/python3.7/dist-packages/ml_collections/config_dict/config_dict.py in __setitem__(self, key, value)
    834       except TypeError as e:
    835         raise TypeError('Could not override field \'{}\' (reference). {}'
--> 836                         .format(key, str(e)))
    837 
    838     if isinstance(value, dict) and self._convert_dict:

TypeError: Could not override field 'stop_at_score' (reference). 100.0 is of type <class 'float'> but should be of type <class 'int'>"

**Comment by konstin** [comment]
Should be fixed by 916456c

**Comment by MetalDictator** [comment]
Thanks!
