### ISSUE TITLE
Terminates after 'Gather input features, predict structure' step 

### ISSUE THREAD

**Issue by shaggy2304** [sokrypton/ColabFold#12]
The Google Notebook program terminates at this step and gives an error message "File Not Found Error". Any help on this issue would be great,

**Comment by sokrypton** [comment]
We have a little too many notebooks, could you give us the link that you're using?

**Comment by shaggy2304** [comment]
I am using the one for AlphaFold2.ipynb.
https://colab.research.google.com/github/sokrypton/ColabFold/blob/main/AlphaFold2.ipynb

**Comment by sokrypton** [comment]
Thanks! Can you also post the sequence input you tried? (Or email me if it's private at so@fas.harvard.edu )

**Comment by shaggy2304** [comment]
This is the sequence which I wanted to predict the structure for in
AlphaFold2.ipynb. Any help on why the section with 'Gather input features,
predict structure' is giving error would be highly beneficial.

>sp|Q01826|SATB1_HUMAN DNA-binding protein SATB1 OS=Homo sapiens OX=9606 GN=SATB1 PE=1 SV=1
MDHLNEATQGKEHSEMSNNVSDPKGPPAKIARLEQNGSPLGRGRLGSTGAKMQGVPLKHS
GHLMKTNLRKGTMLPVFCVVEHYENAIEYDCKEEHAEFVLVRKDMLFNQLIEMALLSLGY
SHSSAAQAKGLIQVGKWNPVPLSYVTDAPDATVADMLQDVYHVVTLKIQLHSCPKLEDLP
PEQWSHTTVRNALKDLLKDMNQSSLAKECPLSQSMISSIVNSTYYANVSAAKCQEFGRWY
KHFKKTKDMMVEMDSLSELSQQGANHVNFGQQPVPGNTAEQPPSPAQLSHGSQPSVRTPL
PNLHPGLVSTPISPQLVNQQLVMAQLLNQQYAVNRLLAQQSLNQQYLNHPPPVSRSMNKP
LEQQVSTNTEVSSEIYQWVRDELKRAGISQAVFARVAFNRTQGLLSEILRKEEDPKTASQ
SLLVNLRAMQNFLQLPEAERDRIYQDERERSLNAASAMGPAPLISTPPSRPPQVKTATIA
TERNGKPENNTMNINASIYDEIQQEMKRAKVSQALFAKVAATKSQGWLCELLRWKEDPSP
ENRTLWENLSMIRRFLSLPQPERDAIYEQESNAVHHHGDRPPHIIHVPAEQIQQQQQQQQ
QQQQQQQAPPPPQPQQQPQTGPRLPPRQPTVASPAESDEENRQKTRPRTKISVEALGILQ
SFIQDVGLYPDEEAIQTLSAQLDLPKYTIIKFFQNQRYYLKHHGKLKDNSGLEVDVAEYK
EEELLKDLEESVQDKNTNTLFSVKLEEELSVEGNTDINTDLKD

Any help on why the notebook is facing an error at this step will be beneficial.


Thanks a lot.
Regards,

**Comment by sokrypton** [comment]
hi @shaggy2304, this example ran with no problem on my side. 
I've been working on trying to reduce memory usage. Can you try the following notebook:
https://colab.research.google.com/github/sokrypton/ColabFold/blob/main/beta/AlphaFold2_advanced.ipynb

**Comment by shaggy2304** [comment]
I have tried to use the new notebook link you gave. But this time it shows
this error message:

**Comment by sokrypton** [comment]
It looks like your error message was not attached. Can you try reply via GitHub?

**Comment by shaggy2304** [comment]
![Screenshot from 2021-08-04 14-07-03](https://user-images.githubusercontent.com/88285210/128167495-a8ecd2cf-fd5f-4ff2-a939-8e59e792cd65.png)

**Comment by shaggy2304** [comment]
Is the screenshot visible now?

**Comment by sokrypton** [comment]
Nice! Looks like AlphaFold ran, but there was a bug in providing the correct variable name to amber (sorry I had this option disabled and forgot to test, can you try again?)

**Comment by shaggy2304** [comment]
I am trying it. I have started to run the sequence. This time "RunAlpha" step happened until 60%, it is still running for 3hrs 40mins. It hasn't shown error yet. But should it be taking this amount of time? It is stuck at 60 % for 2 hrs or so. Is it fine or is the program stuck?

**Comment by shaggy2304** [comment]
Finally after upgrading to COlab Pro and running for around 6-7 hrs the process was completed. Thank you so much. I managed to solve it due to all this help. Thanks a lot.
