### ISSUE TITLE
"None recycles" in multimer predictions

### ISSUE THREAD

**Issue by SamuelSchwab** [sokrypton/ColabFold#120]
When I run multimers in the AlphaFold2_mmseqs2 notebook, the prediction log mentions "None recycles" for every model:

![colabfold_recycle_bug_report](https://user-images.githubusercontent.com/86783023/145053555-f8846cc5-9549-422d-b015-f32328918c60.png)

My input sequence:
MKQHTNFNISAEAVDELCNMLEEIIKITTEVAEQNARKEGRKTIKARDIKQCDDERLKRKIIELSERTDKMPILIKEMLNVITSELK:MKQHTNFNISAEAVDELCNMLEEIIKITTEVAEQNARKEGRKTIKARDIKQCDDERLKRKIIELSERTDKMPILIKEMLNVITSELK
num_recycles: 3

It seems recycles are not being performed for multimers. Is this intended?

When running monomers, the prediction log does mention "3 recycles" for every model.

**Comment by martin-steinegger** [comment]
We perform the recycles as specified in the notebook. Currently the multimer model does not return any recycle values, we need to patch AlphaFold2 for this.

**Comment by SamuelSchwab** [comment]
Aah, ok. So it does do the recycling but it doesn't return the value in the log. Thank you!
