### ISSUE TITLE
MSA coverage plot incorrect for multimers

### ISSUE THREAD

**Issue by SamuelSchwab** [sokrypton/ColabFold#124]
When I supply an a3m file as input for a local installation of colabfold, the MSA coverage plot does not reflect the a3m file when predicting multimers. For monomers the plot is correct.

I supply this a3m ([A0A842RKJ2_dimer.zip](https://github.com/sokrypton/ColabFold/files/7693483/A0A842RKJ2_dimer.zip)) to predict the homodimer structure of A0A842RKJ2.
Colabfold returns this coverage plot:
![A0A842RKJ2_coverage](https://user-images.githubusercontent.com/86783023/145591837-969add90-749f-4d4a-90e6-a02638b27b63.png)

When I use the a3m ([A0A842RKJ2_monomer.zip](https://github.com/sokrypton/ColabFold/files/7693491/A0A842RKJ2_monomer.zip)) to predict the monomer I get this coverage plot:
![A0A842RKJ2_coverage](https://user-images.githubusercontent.com/86783023/145592303-52b2ea7d-7ee0-48f9-926b-baf66eed4b86.png)

Here is another example with a different (less sparse) a3m file:
Coverage plot of homodimer (a3m: [A0A0F7IJ02_dimer.zip](https://github.com/sokrypton/ColabFold/files/7693533/A0A0F7IJ02_dimer.zip)):
![A0A0F7IJ02_coverage](https://user-images.githubusercontent.com/86783023/145593364-5eb84907-a539-4598-af62-40c8ee649f71.png)

Coverage plot of monomer (a3m: [A0A0F7IJ02_monomer.zip](https://github.com/sokrypton/ColabFold/files/7693537/A0A0F7IJ02_monomer.zip)):
![A0A0F7IJ02_coverage](https://user-images.githubusercontent.com/86783023/145593309-014d6e24-3120-4f66-8ce4-f64e10aab8b5.png)

**Comment by martin-steinegger** [comment]
Thank you for reporting it!.  
The issue occurred in the visualization because the multimer models are padded by 512. For some reason the padding is set to 0, which is alanine. Additionally, I noticed that your MSA does not follow exactly our format and caused an issue in parsing. The query sequences was skipped.  

Both are fixed now.

**Comment by SamuelSchwab** [comment]
Great! Thank you so much.
