### ISSUE TITLE
TqdmExperimentalWarning and other issues

### ISSUE THREAD

**Issue by nmrworker** [sokrypton/ColabFold#125]
## Current Behavior
Using the latest Alphafold2.ipynb from https://github.com/sokrypton/ColabFold, I always got this error at the beginning of "Run Prediction" stage in all the calculation I tried:
/usr/local/lib/python3.7/dist-packages/colabfold/colabfold.py:18: TqdmExperimentalWarning: Using `tqdm.autonotebook.tqdm` in notebook mode. Use `tqdm.tqdm` instead to force console mode (e.g. in jupyter console)  from tqdm.autonotebook import tqdm

I don't whether it's something critical because I did get five models for each calculation. However, for some protein/peptide complex, the model shows that the peptide is somehow embedded inside the protein. Is that normal? All the default settings were used for the notebook and all the calculation was done with online sever using a paid account. The sequence was posted in next question.

I just started to use the new notebook. Comparing to the old one with AlphaFold_Advanced.ipynb, I would suggest:
1. allow to use tethering colon for a clear visualization of complex sequence separation;
2. an input box to specify the index of first residue to match the real indices instead of 1;
3. a settings.txt file in the zipped result such as following content:
notebook=https://github.com/sokrypton/ColabFold/AlphaFold2.ipynb
sequence=MVALSLKISIGNVVKTMQFEPSTMVYDACRIIRERIPEAPAGPPSDFGLFLSDDDPKKGIWLEAGKALDYYMLRNGDTMEYRKKQRPLKIRMLDGTVKTIMVDDSKTVTDMLMTICARIGITNHDEYSLVRELMEEKKEEITGTLRKDKTLLRDEKKMEKLKQKLHTDDELNWLDHGRTLREQGVEEHETLLLRRKFFYSDQNVDSRDPVQLNLLYVQARDDILNGSHPVSFDKACEFAGFQCQIQFGPHNEQKHKAGFLDLKDFLPKEYVKQKGERKIFQAHKNCGQMSEIEAKVRYVKLARSLKTYGVSFFLVKEKMKGKNKLVPRLLGITKECVMRVDEKTKEVIQEWNLTNIKRWAASPKSFTLDFGDYQDGYYSVQTTEGEQIAQLIAGYIDIILKKKKS:MGESSEDIDQMFSTLLGEMDLLTQSLGVDT
jobname=test12b
use_amber=False
use_templates=False
save_to_google_drive=True
msa_mode=MMseqs2 (UniRef+Environmental)
model_type=auto
pair_mode=unpaired+paired
num_recycles=3
-------------------------------------------------
length 435
test12b_f774f_unrelaxed_rank_1_model_5 took 100.4s (None recycles) with pLDDT 87.7 and ptmscore 0.758
test12b_f774f_unrelaxed_rank_2_model_1 took 223.4s (None recycles) with pLDDT 85.1 and ptmscore 0.756
test12b_f774f_unrelaxed_rank_3_model_3 took 100.4s (None recycles) with pLDDT 81 and ptmscore 0.693
test12b_f774f_unrelaxed_rank_4_model_2 took 100.4s (None recycles) with pLDDT 84.1 and ptmscore 0.686
test12b_f774f_unrelaxed_rank_5_model_4 took 100.4s (None recycles) with pLDDT 86.4 and ptmscore 0.675

## Steps to Reproduce (for bugs)
Please make sure to reproduce the issue after a "Factory Reset" in Colab. 
If running locally ypdate you local installation `colabfold_batch` to the newest version.
Please provide your input if you can share it. 
MVALSLKISIGNVVKTMQFEPSTMVYDACRIIRERIPEAPAGPPSDFGLFLSDDDPKKGIWLEAGKALDYYMLRNGDTMEYRKKQRPLKIRMLDGTVKTIMVDDSKTVTDMLMTICARIGITNHDEYSLVRELMEEKKEEITGTLRKDKTLLRDEKKMEKLKQKLHTDDELNWLDHGRTLREQGVEEHETLLLRRKFFYSDQNVDSRDPVQLNLLYVQARDDILNGSHPVSFDKACEFAGFQCQIQFGPHNEQKHKAGFLDLKDFLPKEYVKQKGERKIFQAHKNCGQMSEIEAKVRYVKLARSLKTYGVSFFLVKEKMKGKNKLVPRLLGITKECVMRVDEKTKEVIQEWNLTNIKRWAASPKSFTLDFGDYQDGYYSVQTTEGEQIAQLIAGYIDIILKKKKS:MGESSEDIDQMFSTLLGEMDLLTQSLGVDT

## ColabFold Output (for bugs)
Please make sure to also post the complete ColabFold output. You can use gist.github.com for large output.

## Context
Providing context helps us come up with a solution and improve our documentation for the future.

## Your Environment
Include as many relevant details about the environment you experienced the bug in.
* Git commit used
* If you run it on a local system. Please add the server specifications
* Operating system and version:

**Comment by konstin** [comment]
> a settings.txt file in the zipped result such as following content:

We add a config.json with all the options to the zip
