### ISSUE TITLE
GPU usage while running locally

### ISSUE THREAD

**Issue by marcmk6** [sokrypton/ColabFold#139]
Hi,

I have a quick question about trying to run locally. Will ColabFold also attempt to use all available GPUs like AlphaFold?

Thanks!

**Comment by martin-steinegger** [comment]
Yes

**Comment by marcmk6** [comment]
> Yes. Colabfold will try to use the GPU but only one not all. If it fails it will report it. To use the cpu you explicitly need to use the —cpu flag.

Nice. Thanks for quick response!

**Comment by rcrehuet** [comment]
You can use CUDA_VISIBLE_DEVICES to select which GPU it uses.
See https://github.com/sokrypton/ColabFold/issues/36
