### ISSUE TITLE
Prediction for FAD binding?

### ISSUE THREAD

**Issue by hungenlai90** [sokrypton/ColabFold#14]
Many thanks for setting this up! I've found it really useful in my research. I'm looking into some FAD-dependent oxidases, but it seems that cofactors like FAD is not included in the predicted model. Is there a way to do this? Or do i have to dock this after generating the apo protein model?

Thanks!

**Comment by sokrypton** [comment]
RosettaFold/AlphaFold only predicts the protein part. You'll have to dock the molecule. :(
