### ISSUE TITLE
Relaxation fails after max attempts

### ISSUE THREAD

**Issue by meh47336** [sokrypton/ColabFold#145]
Currently trying to run AlphaFold2_advanced to produce five predictions for 38 interaction hits that I've narrowed it down to. The hits were chosen by evaluating unrelaxed output structures. So, for the 5 x 38 predictions produced I'd also like to run AMBER relaxation on each.

This is being run with local GPUs on Linux. The script likely hasn't been updated much since November.

I've edited the script so that num_relax is now "Top5" (have also tried "All").

That said, for every set of predictions I receive the following output:

Traceback (most recent call last):
File "runner_batch.py", line 817, in
relaxed_pdb_lines, _, _ = amber_relaxer.process(prot=outs[key]["unrelaxed_protein"])
File "/share/apps/colab/colabfold/alphafold/relax/relax.py", line 58, in process
out = amber_minimize.run_pipeline(
File "/share/apps/colab/colabfold/alphafold/relax/amber_minimize.py", line 469, in run_pipeline
ret = _run_one_iteration(
File "/share/apps/colab/colabfold/alphafold/relax/amber_minimize.py", line 415, in _run_one_iteration
raise ValueError(f"Minimization failed after {max_attempts} attempts.")
ValueError: Minimization failed after 100 attempts.

Is this typical? Couldn't find other people running into similar problems via Google searches. Is it worth increasing the max_attempts value? Any other suggestions?

I've run the google colab notebook (AlphaFold2_advanced.ipynb) and do not run into the same issue.

Thank you.

**Comment by sokrypton** [comment]
I've seen this error when using amber+GPU. Can you try switch back to using CPU to see if they you still get this error?

**Comment by meh47336** [comment]
> I've seen this error when using amber+GPU. Can you try switch back to using CPU to see if they you still get this error?

Thanks for the advice. Unfortunately running on CPU had other issues on our end. That said, we reinstalled and updated python and alplhafold2_advanced script. Everything is working fine now! We must have just had any early version containing some sort of bug.

Thanks for your response though!
