### ISSUE TITLE
A 700 amino acid long protein - How Long to predict?

### ISSUE THREAD

**Issue by shaggy2304** [sokrypton/ColabFold#15]
Using the AlphaFold2.0 Google Colab Notebook I am trying to predict the structure of a 700-800 amino acid long protein chain, How long will the program take to run?

**Comment by shaggy2304** [comment]
The colab notebook terminates or disconnects after 4hrs. WHat could be the problem? Is Colab Pro essential for longer sequences?

**Comment by sokrypton** [comment]
Colab Pro gives you higher priority but does not guarantee bigger memory GPUs. 

It shouldn't take 4 hours...  which step are you at? Can you add link to notebook you are using?

**Comment by shaggy2304** [comment]
It is stuck in the 5th step - "Gather input features, predict structure." This is the notebook link I am using for the protein sequence:
https://colab.research.google.com/github/sokrypton/ColabFold/blob/main/AlphaFold2.ipynb
