### ISSUE TITLE
What are the mmseqs db for colabfold and is colabfold.mmseqs.com down ? 

### ISSUE THREAD

**Issue by StephaneKazmierczak** [sokrypton/ColabFold#175]
Hi, 

I would like to install a local mmseqs server to run lots of predictions with colabfold_batch 
it seems that I can't reach the page you mention in the documentation 
I am getting : colabfold.mmseqs.com refused to connect.
> The databases are available at [colabfold.mmseqs.com](https://colabfold.mmseqs.com/)

Could you let me know what are the databases you are using ?

**Comment by martin-steinegger** [comment]
Sorry, this was an issues because of a power outage. It should be up again.

**Comment by StephaneKazmierczak** [comment]
Thank you very much for making the page accessible again !
