### ISSUE TITLE
Error while creating the prediction directory in the AlphaFold2_advanced.ipynb

### ISSUE THREAD

**Issue by jlotthammer** [sokrypton/ColabFold#18]
Looks like there is a difference in the mmseq2/complexes notebooks compared to the advanced notebook. The mmseq2/complex notebooks define the following function for creating the hash for a given job:

```
import hashlib
def add_hash(x,y):
    return x+"_"+hashlib.sha1(y.encode()).hexdigest()[:5]
```
However, in the advanced notebook, this function is absent and there is instead a get_hash method call where the object doesn't seem to be defined? Here is the relevant traceback:

```
---------------------------------------------------------------------------

NameError                                 Traceback (most recent call last)

<ipython-input-1-f214cb658cff> in <module>()
     12 
     13 # prediction directory
---> 14 output_dir = 'prediction_' + cf.get_hash(full_sequence)[:5]
     15 os.makedirs(output_dir, exist_ok=True)
     16 print(f"working directory: {output_dir}")

NameError: name 'cf' is not defined
```

Thanks

**Comment by sokrypton** [comment]
hi @jlotthammer,
Did you run the first installation cell?
![image](https://user-images.githubusercontent.com/4187522/128421143-c7f0eb41-548b-42f9-a26e-d769571b5545.png)

This downloads libraries various libraries, installs alphafold and imports the "cf"

**Comment by jlotthammer** [comment]
_**facepalm**_ you are 100% absolutely right, this is totally a silly user error. Somehow I missed this cell entirely by hastily scrolling to the nitty gritty options and fun stuff. 

> I've been working on slowly moving all the redundant code among the different notebooks to a single python file, so that way each notebook can source this file, and any edits are automatically propagated to all sessions.

This makes a lot of sense! Thanks for all the effort, I've had lots of fun playing with these notebooks :) 
Cheers
