### ISSUE TITLE
missing uniref30 files mapping nodes name merged 

### ISSUE THREAD

**Issue by StephaneKazmierczak** [sokrypton/ColabFold#184]
## Current Behavior
I am getting the following error while doing MSA search over local colabfold db and uniref30 db 

## Steps to Reproduce (for bugs)
running pip colabfold 1.2.0
command colabfold_search my_seq.fasta databases msas 
 
Please make sure to execute the reproduction steps with newly recreated and empty tmp folders.

## MMseqs Output (for bugs)
Please make sure to also post the complete output of MMseqs. You can use gist.github.com for large output.
![image](https://user-images.githubusercontent.com/6080232/159718498-a5f73c9f-ee3e-4be3-bdef-43c70f2dde44.png)

## Context
I didn't run the index commands before doing the search just the tar and tsv2exprofiledb commands

**Comment by martin-steinegger** [comment]
@StephaneKazmierczak we added the missing files to the FTP 
http://wwwuser.gwdg.de/~compbiol/colabfold/uniref30_2103_taxonomy.tar.gz
Just download it and unzip in the same folder where your `uniref30_2103_db` files are. 

We as well included it in the [uniref30_2103.tar.gz](http://wwwuser.gwdg.de/~compbiol/colabfold/uniref30_2103_taxonomy.tar.gz)

**Comment by StephaneKazmierczak** [comment]
Thank you very much for the files, I will try out asap !

**Comment by StephaneKazmierczak** [comment]
Hey, everything is working fine now with the taxonomy archive you provided, 
I was able to extract it into the database folder and run some colabfold_search query !
