### ISSUE TITLE
Update Alphafold-colabfold

### ISSUE THREAD

**Issue by ajasja** [sokrypton/ColabFold#188]
Currently the amber relaxation is done using CPU by default

However, the Alphafold amber relax code has a GPU relax flag now
https://github.com/deepmind/alphafold/blob/b85ffe10799ca08cc62146f1dabb4e4ee6c0a580/run_alphafold.py#L386

@martin-steinegger Would it be possible to update alphafold-colabfold? https://github.com/steineggerlab/alphafold

v2.2.0 is the latest release  https://github.com/deepmind/alphafold/releases/tag/v2.2.0

**Comment by martin-steinegger** [comment]
We updated the AlphaFold2 version in colabfold_batch, AlphaFold2 and AlphaFold2_batch notebook

**Comment by ajasja** [comment]
Perfect thanks!
