### ISSUE TITLE
How to run complexes locally ? 

### ISSUE THREAD

**Issue by StephaneKazmierczak** [sokrypton/ColabFold#193]
Hi, 
I have been playing with the colabfold notebook and it is fantastic, 
I have also been trying to install everything locally so I can run lots of prediction for a project 
So I am trying to run complexes prediction with AF-multimer completely locally, (msa + prediction)
it seems that I have to use colbafold_search followed by collabfold_batch but the command manual indicate that complexes are not supported. Is there another way of doing it ?  
Also using the command on a fasta file with 2 sequences produce two a3m files which don't seems to match with the a3m file return by the remote (google colab) version

**Comment by ajasja** [comment]
Great question. I've been using https://github.com/YoshitakaMo/localcolabfold which outsources the MSA prep to the server.

**Comment by martin-steinegger** [comment]
@ajasja thank you for helping users! :) 
@StephaneKazmierczak should be working now with the newest MMseqs2 version or using `--threads 1` for `colabfold_search` using an older version.

**Comment by StephaneKazmierczak** [comment]
@ajasja @martin-steinegger Thanks you very much for the help !
