### ISSUE TITLE
Failed jobs and name error

### ISSUE THREAD

**Issue by soumyarao86** [sokrypton/ColabFold#2]
Hi,

I submitted hExoI with variant residues found in one of the samples.
It gets terminated with no error message at Gather input features, predict structure step.
I also get name errors even after factory reset and re-run.

```
NameError                                 Traceback (most recent call last)
<ipython-input-2-1d8cadd9b758> in <module>()
      1 #@title Gather input features, predict structure
      2 # parse TEMPLATES
----> 3 if use_templates: template_features = mk_template(jobname)
      4 else: template_features = mk_mock_template(query_sequence)
      5 

NameError: name 'use_templates' is not defined
```
Can you please let me know how to fix it?

**Comment by milot-mirdita** [comment]
Can you post the sequence you used for this prediction? Does it work for other sequences? Does this issue still happen with the newest version of the notebook?
This error looks like only part of the notebook got executed (most importantly the first cell was never executed).

**Comment by soumyarao86** [comment]
>ExoI_CLP
MGIQGLLQFIKEASEPIHVRKYKGQVVAVDTYCWLHKGAIACAEKLAKGEPTDRYVGFCM
KFVNMLLSHGIKPILVFDGCTLPSKKEVERSRRERRQANLLKGKQLLREGKVSEARECFT
RSINITHAMAHKVIKAARSQGVDCLVAPYEADAQLAYLNKAGIVQAIITEDSDLLAFGCK
KVILKMDQFGNGLEIDQARLGMCRQLGDVFTEEKFRYMCILSGCDYLSSLRGIGLAKACK
VLRLANNPDIVKVIKKIGHYLKMNITVPEDYINGFIRANNTFLYQLVFDPIKRKLIPLNA
YEDDVDPETLSYAGQYVDDSIALQIALGNKDINTFEQIDDYNPDTAMPAHSRSRSWDDKT
CQKSANVSSIWHRNYSPRPESGTVSDAPQLKENPSTVGVERVISTKGLNLPRKSSIVKRP
RSAELSEDDLLSQYSLSFTKKTKKNSSEGNKSLSFSEMFVPDLVNGPTNKKSVSTPPRTR
NKFATFLQRKNEESGAVVVPGTRSRFFCSSDSTDCVSNKVSIQPLDETAVTDKENNLHES
EYGDQEGKRLVDTDVARNSSDDIPNNHIPGDHIPDKATVFTDEESYSFESSKFTRTISPP
TLGTLRSCFSWSGGLGDFSRTPSPSPSTALQQFRRKSDSSTSLPENNMSDVSQLKSEESS
DDESHPLREGACSSQSQESGEFSLQSSNASKLSQCSSKDSDSEESDCNIKLLDSQSDQTS
KLCLSHFSKKDTPLRNKVPGLYKSSSADSLSTTKIKPLGPARASGLSKKPASIQKRKHHN
AENKPGLQIKLNELWKNFGFKKF

**Comment by soumyarao86** [comment]
I got Wnt10A model. I am running ExoI in new notebook now, reducing the no. of models to 2. I hope it works. Will let you know how it goes.

**Comment by soumyarao86** [comment]
NameError                                 Traceback (most recent call last)
<ipython-input-1-4882f4ef7f6e> in <module>()
      5 use_model = {}
      6 if "model_params" not in dir(): model_params = {}
----> 7 for model_name in ["model_1","model_2","model_3","model_4","model_5"][:num_models]:
      8   use_model[model_name] = True
      9   if model_name not in model_params:

NameError: name 'num_models' is not defined

**Comment by soumyarao86** [comment]
It takes a few hours and runtime stops.
