### ISSUE TITLE
Archana

### ISSUE THREAD

**Issue by anpanche** [sokrypton/ColabFold#200]
I am trying to run alphfold2_advanced, while doing msa it is showing the error below. I tried with different options to reduce the number of sequences but still getting the same error.Please let me know how to resolve it.
Many thanks in advance.

attempting to pair some sequences...
running mmseqs2_noenv_nofilter on all seqs
prepping seq_0
found too many sequences (550168), taking the top100000 (sorted by qid)
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
[<ipython-input-6-a121364f3f0b>](https://localhost:8080/#) in <module>()
     41 
     42 I = cf_af.prep_msa(I, msa_method, add_custom_msa, msa_format,
---> 43                    pair_mode, pair_cov, pair_qid, TMP_DIR=TMP_DIR)
     44 mod_I = I
     45

**Comment by sokrypton** [comment]
This bug should now be fixed. Try again!

**Comment by anpanche** [comment]
Thank you. I could get the msa results.



NameError                                 Traceback (most recent call last)
[<ipython-input-1-2a7abee697ae>](https://localhost:8080/#) in <module>()
     40 
     41 # prep input features
---> 42 feature_dict = cf_af.prep_feats(mod_I, clean=IN_COLAB)
     43 Ls_plot = feature_dict["Ls"]
     44 

NameError: name 'cf_af' is not defined
