### ISSUE TITLE
colabfold_batch still runs a MSA query even if `--msa-mode single_sequence`

### ISSUE THREAD

**Issue by ajasja** [sokrypton/ColabFold#204]
## Expected Behavior
No query should be sent to the server if `--msa-mode single_sequence`

`colabfold_batch --num-recycle 6 --msa-mode single_sequence --model-type AlphaFold2-multimer-v2 --recompile-padding 1 ./{fn} . `

## Current Behavior
Queries are throttled! 

```python
2022-04-14 16:47:58,472 Running colabfold 1.2.0 (6b6898514ec50dfc1a46c2c6cfa787319e7289ff)
2022-04-14 16:47:58,485 Found 2 citations for tools or databases
2022-04-14 16:48:06,026 Query 1/1: nLuc-B_BC-cLuc (length 114)
2022-04-14 16:48:08,204 Sleeping for 6s. Reason: RATELIMIT
2022-04-14 16:48:15,699 Sleeping for 7s. Reason: RATELIMIT
2022-04-14 16:48:25,661 Sleeping for 7s. Reason: RATELIMIT
2022-04-14 16:48:34,795 Sleeping for 6s. Reason: RATELIMIT
2022-04-14 16:48:42,303 Sleeping for 6s. Reason: RATELIMIT
2022-04-14 16:48:50,748 Sleeping for 10s. Reason: RATELIMIT
2022-04-14 16:49:09,517 Sleeping for 5s. Reason: RATELIMIT
2022-04-14 16:49:16,348 Sleeping for 9s. Reason: RATELIMIT
2022-04-14 16:49:26,972 Sleeping for 7s. Reason: RATELIMIT
2022-04-14 16:49:35,504 Sleeping for 10s. Reason: RATELIMIT
2022-04-14 16:49:47,474 Sleeping for 10s. Reason: RATELIMIT
2022-04-14 16:49:59,980 Sleeping for 9s. Reason: RATELIMIT
2022-04-14 16:50:10,974 Sleeping for 6s. Reason: RATELIMIT
2022-04-14 16:50:19,813 Sleeping for 7s. Reason: PENDING
```

## Steps to Reproduce (for bugs)
colabfold_batch --num-recycle 6 --msa-mode single_sequence --model-type AlphaFold2-multimer-v2 --recompile-padding 1 ./{fn} . 

## Your Environment
```json
{
    "num_queries": 1,
    "use_templates": false,
    "use_amber": false,
    "msa_mode": "single_sequence",
    "model_type": "AlphaFold2-multimer-v2",
    "num_models": 5,
    "num_recycles": 6,
    "model_order": [
        3,
        4,
        5,
        1,
        2
    ],
    "keep_existing_results": true,
    "rank_by": "multimer",
    "pair_mode": "unpaired+paired",
    "host_url": "https://api.colabfold.com",
    "stop_at_score": 100,
    "recompile_padding": 1.0,
    "recompile_all_models": false,
    "commit": "6b6898514ec50dfc1a46c2c6cfa787319e7289ff",
    "version": "1.2.0"
}
```

**Comment by ajasja** [comment]
@martin-steinegger I think there should be a case to handle the single sequence mode of paired and unpaired here:
https://github.com/sokrypton/ColabFold/blob/f3f924e4d0acc69ebab7083ca895339976e57f12/colabfold/batch.py#L669

**Comment by ajasja** [comment]
I'll guess I can get arounds this by making a paired+unpaired a3m my self? (@sokrypton)

**Comment by martin-steinegger** [comment]
I pushed some change that should fix it. Could you give it a try again please?

**Comment by ajasja** [comment]
Thanks! this fixes the call to the server, but sets 
[     paired_a3m_lines = None](https://github.com/sokrypton/ColabFold/blob/4db4be5ff626d766898dbdec6435db8e48847d3a/colabfold/batch.py#L690)

Is that the expected behavior. For a single sequence I would expect:

```fasta
>unpaired
AAAAAAAAAAAAAAAAAAAAAAAAAA-----------------------------------------------
--------------------------BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB

>paired
AAAAAAAAAAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB

>paired+unpaired
AAAAAAAAAAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
AAAAAAAAAAAAAAAAAAAAAAAAAA-----------------------------------------------
--------------------------BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
```

**Comment by ajasja** [comment]
@martin-steinegger  Sorry I was just running some old code (so you got a lot of traffic from `193.2.14.82`). Should be fixed now.
( PS Is [paired_a3m_lines = None] the correct behavior)

**Comment by ajasja** [comment]
For heterodimers it looks like the coverage is as I would expect:
![image](https://user-images.githubusercontent.com/19926/213766601-254aa3c0-8083-4c44-9fde-9b9c77fab6d4.png)
But for homodimers it looks like:
![image](https://user-images.githubusercontent.com/19926/213766704-ae5bc3b8-7ddd-4a53-b353-f51e35ac3547.png)

So there is no paired+unpaired.

**Comment by ajasja** [comment]
@sokrypton Is there any advantage to have multiple copies of the same sequence? I think superfold does something similar.

Exmaple:

>unpaired
AAAAAAAAAAAAAAAAAAAAAAAAAA-----------------------------------------------
AAAAAAAAAAAAAAAAAAAAAAAAAA-----------------------------------------------
AAAAAAAAAAAAAAAAAAAAAAAAAA-----------------------------------------------
AAAAAAAAAAAAAAAAAAAAAAAAAA-----------------------------------------------
AAAAAAAAAAAAAAAAAAAAAAAAAA-----------------------------------------------
--------------------------BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
--------------------------BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
--------------------------BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
--------------------------BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
--------------------------BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB

>paired
AAAAAAAAAAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
AAAAAAAAAAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
AAAAAAAAAAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
AAAAAAAAAAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
AAAAAAAAAAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
>paired+unpaired
AAAAAAAAAAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
AAAAAAAAAAAAAAAAAAAAAAAAAA-----------------------------------------------
--------------------------BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB

**Comment by sokrypton** [comment]
For alphafold-multimer putting them on a line, shouldn't be a problem, but for alphafold-ptm... this can be an issue.
I'll see if I can fix this in the beta version!

Thanks for the alert.
