### ISSUE TITLE
How to generate correct a3m from collab_search for multimers ?

### ISSUE THREAD

**Issue by tubiana** [sokrypton/ColabFold#209]
Hi all :) 

I'm trying to script the generation of complex models locally, and for that I have some issues with the input of colabfold_batch...

I installed the latest version of mmseq (`407b315e7edcbc9eb73527b904172e603095494e`) and the version of collabfold on our singularity is the one from 10/03/22.

colabfold_search gave me an a3m with the two alignments one after the other (see [NS5B.zip](https://github.com/sokrypton/ColabFold/files/8499825/NS5B.zip)) like 
```
AAAA
XXXX
BBBB
XXXX
```

 and I see that it is different of the a3m generated from google colab, where the sequence are actually merged like 
```
AAAAABBBBB
XXXXX-----
-----XXXXX
```

Is there a parameter to give to `colabfold_search` or `colabfold_batch` to convert them in the right formating ? 

Thank you :) 
Thibault.

**Comment by martin-steinegger** [comment]
What commit id do you use for colabfold_search? Does the error also persists with the newest version?

**Comment by tubiana** [comment]
Thank you for your feedback :)

Here's my input (`NS5B.fasta`) (two sequence on 1 line separated with `:`)
```
>NS5B_CON1
SMSYTWTGALITPCAAEETKLPINALSNSLLRHHNLVYATTSRSASLRQKKVTFDRLQVLDDHYRDVLKEMKAKASTVKAKLLSVEEACKLTPPHSARSKFGYGAKDVRNLSSKAVNHIRSVWKDLLEDTETPIDTTIMAKNEVFCVQPEKGGRKPARLIVFPDLGVRVCEKMALYDVVSTLPQAVMGSSYGFQYSPGQRVEFLVNAWKAKKCPMGFAYDTRCFDSTVTENDIRVEESIYQCCDLAPEARQAIRSLTERLYIGGPLTNSKGQNCGYRRCRASGVLTTSCGNTLTCYLKAAAACRAAKLQDCTMLVCGDDLVVICESAGTQEDEASLRAFTEAMTRYSAPPGDPPKPEYDLELITSCSSNVSVAHDASGKRVYYLTRDPTTPLARAAWETARHTPVNSWLGNIIMYAPTLWARMILMTHFFSILLAQEQLEKALDCQIYGACYSIEPLDLPQIIQRLHGLSAFSLHSYSPGEINRVASCLRKLGVPPLRVWRHRARSVRARLLSQGGRAATCGKYLFNWAVRTKLKLTPIPAASQLDLSSWFVAGYSGGDIYHSLSRARPRWFMWCLLLLSVGVGIYLLPNR:AKRRLARGSPPSLASSSASQLSAPSLKATCTTRHDSPDADLIEANLLWRQEMGGNITRVESENKVVILDSFEPLQAEEDEREVSVPAEILRRSRKFPRAMPIWARPDYNPPLLESWKDPDYVPPVVHGC
```

The command I used is : 
```bash
$SINGULARITYCOMAND\
	    colabfold_search -s 8 \
	    --db1 uniref30_2103_db \
	    --use-env 0 \
	    --use-templates 0 \
	    --filter 1 \
	    --mmseqs /programs/mmseqs \
	    --expand-eval inf \
	    --align-eval 10 \
	    --diff 0 \
	    --qsc -20.0 \
	    --max-accept 10 \
	    --db-load-mode 2 \
		--threads 1 \
	    /inout/fasta/${FASTA_FILE} /alpha/database/uniref30_2103/ /inout/output
```

For now the version of `colabfold_search` is the one as it was on 10/03/22 (I cannot generate our singularity container for now) But I check and the only difference is the change https://github.com/sokrypton/ColabFold/commit/b152f56fb1c0f08b3a49065063abdc12749038bd  which remove `Doesn't support complexes yet` from the help.

**Comment by tubiana** [comment]
Hi again!

I will close the issue for now, somehow it is fixed now...
I had to reinstall mmseqs, create simlinks into my database folder, a lot for trial and errors... But now it works! 
I will do more test from cleaned new container with last softwares and last dabases and check again. 

Thank you again :)
Thibault.
