### ISSUE TITLE
batch notebook raises error (missing "use_gpu" argument) when calling for amber relaxation

### ISSUE THREAD

**Issue by dxzh0129** [sokrypton/ColabFold#211]
## Current Behavior

The batch.ipynb has been working well until this morning, when the prediction module started raising a "missing one argument" error after getting the first unrelaxed model.

## Steps to Reproduce (for bugs)
Used default parameter settings. 
use_amber = True
use_template = False

## ColabFold Output (for bugs)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
[<ipython-input-8-f1f41d2391ab>](https://localhost:8080/#) in <module>()
     30     pair_mode="unpaired+paired",
     31     stop_at_score=stop_at_score,
---> 32     zip_results=zip_results
     33 )

1 frames
[/usr/local/lib/python3.7/dist-packages/colabfold/batch.py](https://localhost:8080/#) in run(queries, result_dir, num_models, num_recycles, model_order, is_complex, model_type, msa_mode, use_templates, custom_template_path, use_amber, keep_existing_results, rank_by, pair_mode, data_dir, host_url, stop_at_score, recompile_padding, recompile_all_models, zip_results, prediction_callback, save_single_representations, save_pair_representations, training)
   1176                 do_relax=use_amber,
   1177                 rank_by=rank_by,
-> 1178                 stop_at_score=stop_at_score,
   1179                 prediction_callback=prediction_callback,
   1180             )

[/usr/local/lib/python3.7/dist-packages/colabfold/batch.py](https://localhost:8080/#) in predict_structure(prefix, result_dir, feature_dict, is_complex, use_templates, sequences_lengths, crop_len, model_type, model_runner_and_params, do_relax, rank_by, random_seed, stop_at_score, prediction_callback)
    351                 stiffness=10.0,
    352                 exclude_residues=[],
--> 353                 max_outer_iterations=20,
    354                 use_gpu=True
    355             )

TypeError: __init__() missing 1 required keyword-only argument: 'use_gpu'

## Your Environment
Colab Pro

**Comment by martin-steinegger** [comment]
Should be fixed now. Sorry for the inconvenience. It occurred due to updating the Alphafold-version.

**Comment by dxzh0129** [comment]
Thank you! The code works now!  Just one minor issue -- the prediction block now prints out some numpy arrays before predicting the first model.  Guess it was an unintentional leftover from debugging? lol

**Comment by martin-steinegger** [comment]
let me see :O

**Comment by martin-steinegger** [comment]
Thanks you for the info. It should not print out the debug messages now.

**Comment by dxzh0129** [comment]
Thank you Martin!
