### ISSUE TITLE
Custom MSA a3m from fasta alignments

### ISSUE THREAD

**Issue by sami-chaaban** [sokrypton/ColabFold#219]
Hello,

We're trying to generate the MSA in a3m format such that it can be read by Colabfold. We have MSAs for individual chains generated in fasta format, which we can convert to a3m format without issues. When joining the MSAs of the different chains into one a3m file, are they supposed to be done sequentially? For example:

```
#3,3,3	1,1,1
>101	102	103
AAACCCDDD
>X
AAA------
>X
AAA------
>Y
---CCC---
>Y
---CCC---
>Y
---CCC---
>Z
-----DDD
>Z
-----DDD
>Z
-----DDD
```

Where the sequence of 101 is AAA, 102 is CCC, 103 is DDD. Or does it have to be in parallel? Like this:

```
#3,3,3	1,1,1
>101	102	103
AAACCCDDD
>X Y Z
AAACCCDDD
>X Y Z
AAACCCDDD
>X Y Z
AAACCCDDD
>X Y Z
AAACCCDDD
>X
AAA------
>X
AAA------
>X
AAA------
>Y
---CCC---
```

Also, if you have a dimer and set the cardinality in the first line as `#3,3,3	2,1,1`, how does the order of the sequences need to be in the input? Does this then work: `AAA:AAA:CCC:DDD` as the input to Colabfold?

**Comment by martin-steinegger** [comment]
Both of your examples should work. Paired and unpaired rows in the input MSA encode different types of information. For the paired sequence information optimally all three sequences of one row should be orthologs from the same species. The paired sequences normally help to determine the inter complex contacts even though AlphaFold can sometimes also extract it from unpaired MSAs. The unpaired sequences can be regular homologous sequences, you can add it additional to the paired sequences.

**Comment by sami-chaaban** [comment]
Thank you responding so quickly. Is the pairing arbitrary? In other words, does mmseq2 pair sequences from the same species arbitrarily or is there some logic to which isoform of one gene gets paired with which isoform of another?

I'm also still not clear how the cardinality in the first line should match the input to Colabfold, if it's `#3,3,3 2,1,1` for `AAA:AAA:CCC:DDD` (my second point above).

**Comment by martin-steinegger** [comment]
We pick the best matching hit per species for pairing in MMseqs2. You can read more about the pairing [here](https://www.biorxiv.org/content/10.1101/2021.08.15.456425v3)

Yes, `#3,3,3 2,1,1` would result in a complex `AAA:AAA:CCC:DDD`. Our MSA are de-duplicated. You only need to provide AAA once.
