### ISSUE TITLE
prediction_result, processed_feature_dict suffered a error

### ISSUE THREAD

**Issue by GuShaocheng** [sokrypton/ColabFold#22]
Hi,
I always suffered a broken when the program started prediction (calling parse_results(prediction_result, processed_feature_dict) ) after searching.
Is there any suggestion and solution for this? Many thanks!
See the error below:
..../python3.7/site-packages/jax/_src/numpy/lax_numpy.py in _expand_bool_indices(idx, shape)
   5400         expected_shape = shape[len(out): len(out) + _ndim(i)]
   5401         if i_shape != expected_shape:
-> 5402             raise IndexError("boolean index did not match shape of indexed array in index "
   5403                             f"{dim_number}: got {i_shape}, expected {expected_shape}")
   5404         out.extend(np.where(i))

IndexError: boolean index did not match shape of indexed array in index 2: got (63,), expected (64,)

**Comment by sokrypton** [comment]
@GuShaocheng which notebook are you using, and can you share the sequence input that you used?
(you can email the sequence to so@fas.harvard.edu if it's private)

**Comment by GuShaocheng** [comment]
Thanks for your prompt reply!
I run the code in google colab with local runtime. I also run it directly in the ipython of the local machine. Both gave me the same error.
I tested several sequences, all of which failed in this step. The sequence of shortest one is "MSPKKVQIKVEEKEDETEAFKMMMAKKWAKFLRDFENFKAA".
If you need me to check anything else, please let me know!

**Comment by GuShaocheng** [comment]
> @GuShaocheng which notebook are you using, and can you share the sequence input that you used?
> (you can email the sequence to [so@fas.harvard.edu](mailto:so@fas.harvard.edu) if it's private)

hanks for your prompt reply!
I run the code in google colab with local runtime. I also run it directly in the ipython of the local machine. Both gave me the same error.
I tested several sequences, all of which failed in this step. The sequence of shortest one is "MSPKKVQIKVEEKEDETEAFKMMMAKKWAKFLRDFENFKAA".
If you need me to check anything else, please let me know!

**Comment by sokrypton** [comment]
Thanks for reporting this! Looks like the colab version of jax didn't complain about the mismatch in index.

Looks like the prediction_result["distogram"]["bin_edges"] has 63 reposted bin edges, but there are actually 64 bins predicted.

While investigating I realize I had a bug. This does not affect any of the results, just the distance matrix and contact matrix visual slightly (all values are offset by ~2 angstroms).

The bug was fixed in notebook, but here is the code if you want to fix in your own installation.

```python
def parse_results(prediction_result, processed_feature_dict):
  b_factors = prediction_result['plddt'][:,None] * prediction_result['structure_module']['final_atom_mask']  
  dist_bins = jax.numpy.append(0,prediction_result["distogram"]["bin_edges"])
  dist_mtx = dist_bins[prediction_result["distogram"]["logits"].argmax(-1)]
  contact_mtx = jax.nn.softmax(prediction_result["distogram"]["logits"])[:,:,dist_bins < 8].sum(-1)

  out = {"unrelaxed_protein": protein.from_prediction(processed_feature_dict, prediction_result, b_factors=b_factors),
         "plddt": prediction_result['plddt'],
         "pLDDT": prediction_result['plddt'].mean(),
         "dists": dist_mtx,
         "adj": contact_mtx}
  if "ptm" in prediction_result:
    out.update({"pae": prediction_result['predicted_aligned_error'],
                "pTMscore": prediction_result['ptm']})
  return out
```

Tell me if you run into any more issues!

**Comment by GuShaocheng** [comment]
@sokrypton 
Thanks for your reply and fix. It is exactly this issue (I manually change "prediction_result["distogram"]["bin_edges"] < 8" to 64, even I haven't understood all the codes, the program can pass this part). 
Now, it successfully runs to the end after fixing this part. Good job!

--
Besides, it is very 'weird that colab didn't report the mismatch since I also print the output from colab which shows 63 in this part, leading me to doubt my life.
