### ISSUE TITLE
Estimated RAM and CPU usage for colabfold_search

### ISSUE THREAD

**Issue by Pooryamb** [sokrypton/ColabFold#225]
Dear ColabFold developers,

I asked my question in the issues part of GitHub because I assumed others were looking for the answer to the same question. 

I am using a busy computational server with long queues, and I don't have the opportunity to try different options for optimal resource allocation to colabfold_search. What is the estimated runtime for generating MSA for 1, 100, and 10000 proteins with 160 GB of RAM? Based on your description, colabfold_search is CPU intensive. Could you please suggest how many threads should be used with 160 GB of RAM? I just need rough estimations, not exact numbers.

Best,

**Comment by martin-steinegger** [comment]
We ran 1,762 proteins in 113 min on a computer with an AMD EPYC 7402P 24-core CPU with 512 GB RAM. In our run MMseqs2 had a maximum resident set size of 308 GB during the search. 160GB of RAM should be fine as well at the cost of runtime. It is probably not much slower.
