### ISSUE TITLE
Extract Protein Embedding using ColabFold

### ISSUE THREAD

**Issue by pykao** [sokrypton/ColabFold#226]
Hi, 

I tried to get the protein embedding using AlphaFold2, and the [issue](https://github.com/deepmind/alphafold/issues/15) mentioned that I need to set `return_representations=True` located in `alphafold/model/modules.py`. I looked into your repository and found out that `ColabFold/beta/Alphafold_single.ipynb` might be the right resource for me.

I followed the instruction by 

1. Forked the AlphaFold into my personal GitHub.
2. set two lines of `return_representations=True` located in `alphafold/model/modules.py`.
3. Forked the ColabFold into my personal GitHub. 
4. set `"GIT_REPO = 'https://github.com/pykao/alphafold'",` located in [beta/Alphafold_single.ipynb](https://github.com/pykao/ColabFold/commit/9c022c0cdf64e342bc1fd5bd1c20b72940abc52d#diff-af4802ebf3da961cb6c8564e8aafc0ae6ad3582271b0aad9cfcd595a1cb44461)
5. set the source located in [beta/Alphafold_single.ipynb](https://github.com/pykao/ColabFold/commit/df940a4b5f0d65f38648085901505e2d461a82a2)
6. set the git checkout point to the one I set `return_representations=True` located in [beta/Alphafold_single.ipynb](https://github.com/pykao/ColabFold/commit/2ab8701a3fbd8fcb91169c2f83fc6b3094b3aa68)

However, I still cannot get the `'representation'`. Could you help me out on finding the `'single'` representation of protein embedding?

Best, 
Po-Yu Kao

**Comment by milot-mirdita** [comment]
The `colabfold_batch` executable have the `--save-single-representations` and `--save-pair-representations` that should return embeddings. You should probably use these.

**Comment by pykao** [comment]
Hi @milot-mirdita,

Thank you for your quick reply. I am going to try `colabfold_batch` from [YoshitakaMo/localcolabfold](https://github.com/YoshitakaMo/localcolabfold), and get back to you if it works.

Best,
Po-Yu Kao

**Comment by milot-mirdita** [comment]
The `colabfold_batch` script is part of this repository (https://github.com/sokrypton/ColabFold).
