### ISSUE TITLE
why does colabfold_batch give deterministic results?

### ISSUE THREAD

**Issue by pykao** [sokrypton/ColabFold#227]
Hi,

I used AlphaFold 2.0 to generate the structure twice using the same protein sequence, and it gave me different structures. Then, I check the AlphaFold GitHub page:

```
flags.DEFINE_integer('random_seed', None, 'The random seed for the data '
                     'pipeline. By default, this is randomly generated. Note '
                     'that even if this is set, Alphafold may still not be '
                     'deterministic, because processes like GPU inference are '
                     'nondeterministic.')
```

However, I used `colabfold_batch` on the same protein sequence twice that surprisingly gives me the same structure.

Do you use the same seed in every experiments?

Best,
Po-Yu Kao

**Comment by milot-mirdita** [comment]
`colabfold_batch` fixes the random_seed to 0. I just pushed a change to expose the seed as a command line parameter.

**Comment by pykao** [comment]
Thank you for your explanation.
