### ISSUE TITLE
Large chunk of complex gets clipped

### ISSUE THREAD

**Issue by yangkky** [sokrypton/ColabFold#228]
## Expected Behavior

Not to clip large parts of protein sequences

## Current Behavior

Clips the first 120 residues or so of the second chain for the following input: 

```
TNLCPFGEVFNATRFASVYAWNRKRISNCVADYSVLYNSASFSTFKCYGVSPTKLNDLCFTNVYADSFVIRGDEVRQIAPGQTGKIADYNYKLPDDFTGCVIAWNSNNLDSKVGGNYNYLYRLFRKSNLKPFERDISTEIYQAGSTPCNGVEGFNCYFPLQSYGFQPTNGVGYQPYRVVVLSFELLHAPATVCG:STIEEQAKTFLDKFNHEAEDLFYQSSLASWNYNTNITEENVQNMNNAGDKWSAFLKEQSTLAQMYPLQEIQNLTVKLQLQALQQNGSSVLSEDKSKRLNTILNTMSTIYSTGKVCNPDNPQECLLLEPGLNEIMANSLDYNERLWAWESWRSEVGKQLRPLYEEYVVLKNEMARANHYEDYGDYWRGDYEVNGVDGYDYSRGQLIEDVEHTFEEIKPLYEHLHAYVRAKLMNAYPSYISPIGCLPAHLLGDMWGRFWTNLYSLTVPFGQKPNIDVTDAMVDQAWDAQRIFKEAEKFFVSVGLPNMTQGFWENSMLTDPGNVQKAVCHPTAWDLGKGDFRILMCTKVTMDDFLTAHHEMGHIQYDMAYAAQPFLLRNGANEGFHEAVGEIMSLSAATPKHLKSIGLLSPDFQEDNETEINFLLKQALTIVGTLPFTYMLEKWRWMVFKGEIPKDQWMKKWWEMKREIVGVVEPVPHDETYCDPASLFHVSNDYSFIRYYTRTLYQFQFQEALCQAAKHEGPLHKCDISNSTEAGQKLFNMLRLGKSEPWTLALENVVGAKNMNVRPLLNYFEPLFTWLKDQNKNSFVGWSTDWSPYAD
```

## Steps to Reproduce (for bugs)
Put above sequence into here: https://colab.research.google.com/github/sokrypton/ColabFold/blob/main/AlphaFold2.ipynb#scrollTo=kOblAo-xetgx

## ColabFold Output (for bugs)
I made it into a [gist](https://gist.github.com/yangkky/336db6c8021f9a2aab7699f1b34fce40)

**Comment by sokrypton** [comment]
I'm not seeing any trimming for the provided example. The lengths and sequences match
TNLCPFGEVFNATR.....
STIEEQAKTFLDKF....
<img width="350" alt="image" src="https://user-images.githubusercontent.com/4187522/168412274-895a16ce-3cae-4bb2-b969-cfcbb6621d4a.png">

Are you sure you pasted in the sequences you thought you did?

**Comment by sokrypton** [comment]
the beginning of the second chain appear intact:
<img width="277" alt="image" src="https://user-images.githubusercontent.com/4187522/168412368-792691ca-21e7-434b-b8b6-eef722b86111.png">

**Comment by yangkky** [comment]
Ah I thought the chains would be A and B so I parsed the pdb file wrong!

**Comment by milot-mirdita** [comment]
The chains starting at `B` is a bug that I've been meaning to fix. If you enable amber, it will fix the chains to start with A.
