### ISSUE TITLE
ColabFold is not working when I upgrade my Colab into ColabPro

### ISSUE THREAD

**Issue by miaolegemi1000** [sokrypton/ColabFold#231]
This [RuntimeError: Error loading imports from extension module] appears immediately when I upgrade my Colab. I upgrade for predict protein have over 1000 Seq.

**Comment by sokrypton** [comment]
Does it still fail? Typically you'd want to factory reset your session before continuing (if you just upgraded).

**Comment by miaolegemi1000** [comment]
I works now, Thank you~
