### ISSUE TITLE
Add new parameters for GPU devices

### ISSUE THREAD

**Issue by ijayden-lung** [sokrypton/ColabFold#232]
## Expected Behavior
We can select the gpu devices we want.
## Current Behavior
Could not select GPU devices

## Your Environment
Colabfold docker image from https://hub.docker.com/r/230218818/colabfold

**Comment by rcrehuet** [comment]
You can use CUDA_VISIBLE_DEVICES to select which GPU you want to use.
See https://github.com/sokrypton/ColabFold/issues/36

**Comment by ijayden-lung** [comment]
Thank you！ It works by adding export CUDA_VISIBLE_DEVICES=1 in bash script.
