### ISSUE TITLE
Run Prediction Step Fail

### ISSUE THREAD

**Issue by kplarsen** [sokrypton/ColabFold#234]
I've been trying to run using ColabFold with a Colab Pro+ subscription. However the runs keep failing with the error below. The IndexError, mentioned in another Issue, also happens. However I think the root issue is below. The AlphaFold2_advanced works fine, but the AlphaFold2 (which allows for templates) always fails in this manner.

## Current Behavior

RUN PREDICTION:  

Downloading alphafold2 weights to .: 100%|██████████| 3.47G/3.47G [00:16<00:00, 228MB/s]
2022-05-30 17:01:41,510 Found 5 citations for tools or databases
2022-05-30 17:01:47,445 Query 1/1: test_b38f0 (length 469)
COMPLETE: 100%|██████████| 150/150 [elapsed: 00:01 remaining: 00:00]
2022-05-30 17:01:49,990 Running model_1
2022-05-30 17:05:03,971 Could not predict test_b38f0. Not Enough GPU memory? INTERNAL: CustomCall failed: jaxlib/cuda_prng_kernels.cc:30: operation cudaGetLastError() failed: the provided PTX was compiled with an unsupported toolchain.
2022-05-30 17:05:03,973 Done

## Steps to Reproduce (for bugs)

This happen even after reseting runtime and with any input sequence or any length. Same issue if a template is used.

**Comment by sokrypton** [comment]
hi @kplarsen can you try create a new cell and type:
`!nvidia-smi`

To check what GPU you got assigned. So far I'm not seeing this error, so I wonder if it's specific to the assigned GPU.

**Comment by kplarsen** [comment]
It looks like an A100

+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  A100-SXM4-40GB      Off  | 00000000:00:04.0 Off |                    0 |
| N/A   33C    P0    46W / 400W |      0MiB / 40536MiB |      0%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+

**Comment by sokrypton** [comment]
Unfortunately, we don't have colab pro + for testing :(

Can you try running with the following notebook:
https://colab.research.google.com/drive/14c5weqS7_tbKzWZo7cAuucp8ZXgpFKIb

Here I removed the jaxlib version constraint during upgrade. 
`pip install --upgrade jax[cuda] -f https://storage.googleapis.com/jax-releases/jax_releases.html`

**Comment by kplarsen** [comment]
Same issue occurred: 
____
Downloading alphafold2 weights to .: 100%|██████████| 3.47G/3.47G [00:17<00:00, 215MB/s]
2022-05-30 19:46:15,217 Found 5 citations for tools or databases
2022-05-30 19:46:21,275 Query 1/1: test_b38f0 (length 469)
COMPLETE: 100%|██████████| 150/150 [elapsed: 00:02 remaining: 00:00]
2022-05-30 19:46:23,970 Running model_1
2022-05-30 19:49:36,988 Could not predict test_b38f0. Not Enough GPU memory? INTERNAL: CustomCall failed: jaxlib/cuda_prng_kernels.cc:30: operation cudaGetLastError() failed: the provided PTX was compiled with an unsupported toolchain.
2022-05-30 19:49:36,990 Done
_____

I forgot to mention that this issue did crop up on May 10th (according to my notes), but I was traveling until today and had hoped it was a one time thing on my end. So I'm not sure if there was some kind of update around that time.

**Comment by kplarsen** [comment]
This worked! Should I keep using this link or is there a way to adapt the regular Colab notebook?

**Comment by sokrypton** [comment]
This edit is now part of the main notebook! Thanks for checking.
