### ISSUE TITLE
No such file or directory when using custom template

### ISSUE THREAD

**Issue by joec97210** [sokrypton/ColabFold#240]
![Screen Shot 2022-06-14 at 11 38 46](https://user-images.githubusercontent.com/107473967/173558862-c89d0d06-2c76-4285-9788-440486633964.png)
![Screen Shot 2022-06-14 at 11 39 02](https://user-images.githubusercontent.com/107473967/173558901-b32bae6b-92a7-4756-94af-90d877416ea0.png)

So I am attempting to build a dimer model using my own crystal structure of the monomer. I added in the dimer sequence, with each monomer separated by a ":"  I converted my pdb to a .cif format using an online web server and then added
loop_
_pdbx_audit_revision_history.ordinal
_pdbx_audit_revision_history.data_content_type
_pdbx_audit_revision_history.major_revision
_pdbx_audit_revision_history.minor_revision
_pdbx_audit_revision_history.revision_date
1 'Structure model' 1 0 1971-01-01

This revision entry i believe is required at the end of the cif file. Then i coverted the name to a 4 letter code. I believe I followed all the steps for converting my pdb to the correct cif format required. But still get this error saying no such file even though the file could upload. Any help is greatly appreciated.

**Comment by milot-mirdita** [comment]
I pushed a fix to pdb file support earlier. You can also provide a PDB file, it will automatically convert it to mmCIF and add the required fields. Hope that helps avoid such issues in the future.
