### ISSUE TITLE
Download cell error, num_relax not defined

### ISSUE THREAD

**Issue by SKleinfelter** [sokrypton/ColabFold#25]
This line was throwing an error in the Download cell - when I commented it out the cell ran successfully:
text_file.write(f"num_relax={num_relax}\n")

NameError: name 'num_relax' is not defined

**Comment by sokrypton** [comment]
Thanks @SKleinfelter!

The expectation was that user would click on the amber-relax cell, even if it's optional :) 

I've removed this requirement, so all will work even if the user skips this step.
