### ISSUE TITLE
Hanging at running mmseqs2

### ISSUE THREAD

**Issue by rsrock** [sokrypton/ColabFold#26]
Starting today, after the progress bar fills completely for this step, we're hanging here (output after interrupting the kernel)

```
KeyboardInterrupt
---------------------------------------------------------------------------
KeyboardInterrupt                         Traceback (most recent call last)
/tmp/ipykernel_57/1853154669.py in <module>
     53     prefix = os.path.join('tmp',prefix)
     54     print(f"running mmseqs2")
---> 55     A3M_LINES = cf.run_mmseqs2(seqs, prefix, filter=True)
     56 
     57     # filter sequences to 10K\n",

/app/alphafold/colabfold.py in run_mmseqs2(x, prefix, use_env, filter)
    111         while out["status"] in ["UNKNOWN","RUNNING","PENDING"]:
    112           t = 5 + random.randint(0,5)
--> 113           time.sleep(t)
    114           out = status(ID)
    115           pbar.set_description(out["status"])
```

**Comment by sokrypton** [comment]
@rsrock do you remember what the status was. Was it "RUNNING"? If so, you may have submitted a protein that has too many homologous sequences, and we underestimated how long it would take to assemble the MSA. If you come back later today, and rerun the notebook, it will have finished (jobs continue to run on the webserver, even if notebook is closed, and can be recovered without restarting from scratch).

**Comment by rsrock** [comment]
Ok, we will try that and report back.  These sequences were not out of the ordinary though, and we usually get an answer back within a few minutes.

**Comment by milot-mirdita** [comment]
We are having a very high load currently as people were submitting tons of jobs through scripts. I've rate-limited some of these, I hope the server load will normalize soon.

If your job is already in RUNNING state, it should eventually finish, sometimes we find a few hundred thousand hits and that takes time to align. We are improving the pipeline to avoid cases like these.

**Comment by rsrock** [comment]
Yes, it's working now.  Next time I'll be more patient at the end there.  Thanks.
