### ISSUE TITLE
Format of custom MSA for AAA:BBB complex?

### ISSUE THREAD

**Issue by SKleinfelter** [sokrypton/ColabFold#27]
When inputting a complex in AAA:BBB format, and custom MSA, I keep getting "ERROR: the length of msa does not match input sequence".  My MSA has hyphens in it because some homologs have insertions; I have tried including the appropriate hyphens in the input sequence, but it looks like they are being ignored for the length calculation.  Is it possible to use an MSA where my target is shorter than some of the homologs?

**Comment by sokrypton** [comment]
Hi @SKleinfelter 

The custom MSA should be of the following format. No need to add any `:` or `/` in the actual custom MSA.
```
>header
AB
>header
AB
```

It will be automatically expanded into:
```
AAABBB
A--B--
A--B--
-A--B-
-A--B-
--A--B
--A--B
```

Tell me if this works!

**Comment by SKleinfelter** [comment]
Still getting the same error.  I am not trying to oligomerize, just combine a protein (A) and a peptide (B) in 1:1 stoichiometry.  I currently have AAAA:BBB in the sequence input.  In your video you suggested that the first line of the MSA could be AAAABBB and subsequent lines be:
AAAA---
AAAA---
----BBB
----BBB
I'm not sure how to handle homologs with insertions and deletions, though.
