### ISSUE TITLE
Question: socket.gaierror: [Errno -2] Name or service not known

### ISSUE THREAD

**Issue by JOJO-wc-rabbit** [sokrypton/ColabFold#273]
Hi,

I got the error below while submitting the test code (colabfold_batch --num-recycle 1 4UUZ.fasta output) on a cluster server (ssh, non-root). Is there any solution please?

![image](https://user-images.githubusercontent.com/61336971/180137806-ed98cdae-9c4a-4281-9086-abbb2bcb837f.png)

Thanks.

**Comment by YoshitakaMo** [comment]
I'll respond here https://github.com/YoshitakaMo/localcolabfold/issues/96 .
