### ISSUE TITLE
 Custom templates ignored in prediction phase (but preprocessing is working)

### ISSUE THREAD

**Issue by matteo-cagiada** [sokrypton/ColabFold#278]
## Expected Behavior
Running colabfold (online v1.4 and localcolabfold latest) with custom templates to predict different conformations
## Current Behavior
No template is detected with any combination of options in the model generation, with no error issued during the loading phase and pdb70* correctly generated. The run proceed as one without templates. 
## Steps to Reproduce (for bugs)

I've tried this with two separate examples:

1 I tried to predict structure for [P02911](https://www.uniprot.org/uniprotkb/P02911/entry), using as template two of its structures: 2LAO and 1LAH. In both the cases I followed the instructions regarding the custom template section and uploaded pdb files, both were correctly converted to cif and pdb70index and ffdata files are found in the correct folder.
I've also tried to fix numeration problems in the pdb (matching with the actual sequence numeration - using pdbtools) and also to mutate a couple of sequence residues (with pymol) to input a different variant. Nothing worked. For all the above I've tried different combinations of MSA mode but any  template was detected in the prediction phase.

2 I've use protein [PRKN_human ](https://www.uniprot.org/uniprotkb/O60260/entry). First, I tried to use a template which few months ago gave me back a running prediction with good results (pdb [6GLC](https://www.rcsb.org/structure/6GLC)), but as above it didn't work this time. Then, I decided to try first to use the pdb70 option to retrieve a list of templates and select one of them as input custom template. [6DJW](https://www.rcsb.org/structure/6DJW) was the designated one.  I used it as custom template input. I used the entire structure as well as only chain A  and I tried to use as above different combination (sequence numeration was already matching), but no template was detected in any of the combinations used.. 

Input screenshot:
![Schermata 2022-08-01 alle 17 42 13](https://user-images.githubusercontent.com/39051329/182187640-4d8b4154-a1ad-4c20-af73-620330ac815c.png)

## ColabFold Output (for bugs)

Output of prediction phase:
```
2022-08-01 15:11:44,583 Found 6 citations for tools or databases
2022-08-01 15:11:50,860 Query 1/1: test_29b6d (length 465)
COMPLETE: 100%|██████████| 150/150 [elapsed: 00:02 remaining: 00:00]
2022-08-01 15:12:03,097 Sequence 0 found no templates
2022-08-01 15:12:03,996 Running model_1
```
![Schermata 2022-08-01 alle 17 42 28](https://user-images.githubusercontent.com/39051329/182187868-fed83f4e-5a77-47d0-93c3-975e9add915c.png)

## Your Environment
[Colab](https://colab.research.google.com/github/sokrypton/ColabFold/blob/main/AlphaFold2.ipynb) and locacolabfold (latest, checked for update this morning) on a server machine with cuda/11.2.0 on a v100. ANy error during the pre-processing.

## Extra:
I've attached the data of 6DJW PARKIN run here in a zip: 
[colab_issue_PRKN.zip](https://github.com/sokrypton/ColabFold/files/9235367/colab_issue_PRKN.zip)

The archive includes:  logfile and pdb + cif + pdb70* files ( pdbs' name were fixed before the upload) 

Do you have any idea why it's not working? Thanks for your help!

**Comment by davidesala** [comment]
Hi Matteo, I'm having trouble in re-running scripts that were working time ago because of templates. It may involve the HHsuite API.
