### ISSUE TITLE
setup error

### ISSUE THREAD

**Issue by zjq1011** [sokrypton/ColabFold#280]
## Expected Behavior
local colabfold setup

## Current Behavior
error: legacy-install-failure

## Steps to Reproduce (for bugs)
create a virtual environment using conda
execute pip install "colabfold[alphafold] @ git+https://github.com/sokrypton/ColabFold"

## ColabFold Output (for bugs)
too long to present all
output around the error

Building wheels for collected packages: matplotlib, colabfold
  Building wheel for matplotlib (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [507 lines of output]
      ================================================================================
      Edit setup.cfg to change the build options

      BUILDING MATPLOTLIB
        matplotlib: yes [3.1.3]
            python: yes [3.9.12 (main, Jun  1 2022, 11:38:51)  [GCC 7.5.0]]
          platform: yes [linux]

      OPTIONAL SUBPACKAGES
       sample_data: yes [installing]
             tests: no  [skipping due to configuration]

      OPTIONAL BACKEND EXTENSIONS
               agg: yes [installing]
             tkagg: yes [installing; run-time loading from Python Tcl/Tk]
            macosx: no  [Mac OS-X only]

      OPTIONAL PACKAGE DATA
              dlls: no  [skipping due to configuration]

 fatal error: ft2build.h: No such
file or directory
          1 | #include <ft2build.h>
            |          ^~~~~~~~~~~~
      compilation terminated.
      error: command '/usr/bin/gcc' failed with exit code 1
      [end of output]

  note: This error originates from a subprocess, and is likely not a
problem with pip.
  WARNING: No metadata found in
/home/fbsb2/miniconda3/envs/colabfold/lib/python3.9/site-packages

error: legacy-install-failure

× Encountered error while trying to install package.
╰─> matplotlib

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

## Your Environment
Ubuntu 22.04
conda 4.13.0
python version in the virtual environment 3.9

**Comment by milot-mirdita** [comment]
Try installing `freetype` in the same conda environment first and then call `pip`.

**Comment by zjq1011** [comment]
Thank you for your help.
I think it works well now.
