### ISSUE TITLE
inquiry regarding environmental variable colabfold_batch 

### ISSUE THREAD

**Issue by zjq1011** [sokrypton/ColabFold#281]
Hello.
Yesterday I pulled the repo of localcolabfold from
https://github.com/YoshitakaMo/localcolabfold.
And I added the environmental variable colabfold_batch to the system environment.

Today I pulled this repo using the conda environment (#280).
If I input
**colabfold_batch <directory_with_fasta_files> <result_dir>** 
in the conda environment now,
which one will it actually execute?
Do I need to add the environmental variable in the conda environment?

I saw the question in the FAQ part
What is the difference between localcolabfold and the pip installable colabfold_batch?
localcolabfold is a command line interface for our advanced notebooks. pip is a command line version of the alphafold_mmseqs2 and alphafold_batch notebook.

I am not sure if it refers to the two repos I mentioned above.
If so, can I regard them as the local version of two different notebooks,
Alphafold2_batch and Alphafold2_advanced, respectively.

Any help will be greatly appreciated.

**Comment by YoshitakaMo** [comment]
Try `which colabfold_batch` to check the file path of it. If you added the environmental variable and the command returns `/home/foo/bar/colabfold_batch/bin/colabfold_batch`, the localcolabfold's one will be executed.

If you want to select one or the other explicitly, you should use the absolute path of `colabfold_batch` command, i.e. `/home/foo/bar/colabfold_batch/bin/colabfold_batch <directory_with_fasta_files> <result_dir>` or `/path/to/your_conda/bin/colabfold_batch <directory_with_fasta_files> <result_dir>` (after activating your conda environment).

Both are designed to use the alphafold_mmseqs2 functions. AlphaFold2_advanced is only available as Jupyter Notebook in your browser.
