### ISSUE TITLE
Partial binder hallucination?

### ISSUE THREAD

**Issue by blakely3dnm** [sokrypton/ColabFold#283]
Hi, 

Would it be possible to combine the partial hallucination and binder hallucination protocols to hallucinate loops or other new structural elements within a given binder scaffold?

A trial case I have in mind would involve a binding interface formed by a multi-chain protein binder and multiple receptor chains. I'd like to add a new loop between the multi-chain binder but leave the target receptor sequence and connectivity consistent with the input.
I almost got this to work using the partial hallucination examples, however I'm not sure how to avoid designing unnecessary loops at the chain breaks. loops of zero length force single chain outputs. 

Should I look into specifying a sequence with "/" instead of a PDB?  

Thanks

**Comment by blakely3dnm** [comment]
Nevermind! I should have tried -1 for linker length before posting. Doing so accomplishes what I intended. (Also this is probably the wrong issue section -- feel free to move it)

**Comment by sokrypton** [comment]
please reopen at ColabDesign github
