### ISSUE TITLE
sl.SSLError: [SSL: KRB5_S_TKT_NYV]

### ISSUE THREAD

**Issue by biotech70** [sokrypton/ColabFold#284]
What is your question?
During the execution of the Local-ColabFold by the following command, it encounters a problem. The error file was attached.
$ colabfold_batch --amber --templates --num-recycle 3 --use-gpu-relax --zip inputfile outputdir/

Computational environment

OS: [Ubuntu 22.04]
CUDA version if Linux (11.7)
[colabfold_error.txt](https://github.com/sokrypton/ColabFold/files/9283689/colabfold_error.txt)

**Comment by YoshitakaMo** [comment]
Duplicated and solved: https://github.com/YoshitakaMo/localcolabfold/issues/105
