### ISSUE TITLE
Request: pLDDT & pTMscore to be stored in downloaded results archive

### ISSUE THREAD

**Issue by MWNautilus** [sokrypton/ColabFold#290]
I hope I haven't overlooked something but would it please be possible to store the pLDDT and pTMscore values in a file that would be added to the downloadable model results archive? And maybe also the modeling / AMBER relaxation runtimes?

Michael.

**Comment by sokrypton** [comment]
Hi Michael,
The pLDDT and pTMscores are in the scores.json file. See instructions below from notebook:
<img width="935" alt="image" src="https://user-images.githubusercontent.com/4187522/185479537-0f8b0e73-1ebc-4304-be31-8b0cdbef643d.png">

Here is a screenshot of the results:
<img width="498" alt="image" src="https://user-images.githubusercontent.com/4187522/185480243-68141137-6d3f-4bc9-8f5f-2e06bf5ed997.png">

I don't think we currently provide the runtimes...

**Comment by MWNautilus** [comment]
Thanks Sergey for the quick reply.

Regarding the AMBER relaxation runtimes: When using Google Colab, even with the more costly Google payment models there is a total runtime limit. For each run, the AMBER relaxation steps may take quite a fraction of the total runtime allowance. Therefore, for certain (more complex) modeling applications it would be useful to de-couple the AlphaFold2 modeling part from the AMBER relaxation step(s) such that they both constitute a separate run (doubling the possible max. compute times for both, modeling & relaxation).

Wouldn't it be possible to modify the notebook such that instead of the current automatic AMBER relaxation of all models (if enabled), one could manually upload the desired AlphaFold2 output PDB files for subsequent AMBER relaxation?
Might even happen in a separate notebook.

Michael.

**Comment by sokrypton** [comment]
That's a good idea!
