### ISSUE TITLE
ValueError: setting an array element with a sequence

### ISSUE THREAD

**Issue by suchloust** [sokrypton/ColabFold#3]
I am trying to use the AlphaFold complexes notebook, but I keep getting an error code.
<img width="805" alt="Screen Shot 2021-07-20 at 9 11 49 PM" src="https://user-images.githubusercontent.com/87739710/126415489-4f95e80e-111b-4129-a608-a2f2c14bf6a6.png">
Is there something on my end that I should correct?

**Comment by sokrypton** [comment]
Can you send me the sequences used?

**Comment by suchloust** [comment]
> Can you send me the sequences used?

MENRWQVMIVWQVDRMRIRTWKSLVKHHMYVSGKARGWFYRHHYESPHPRISSEVHIPLGDARLVITTYWGLHTGERDWHLGQGVSIEWRKKRYSTQVDPELADQLIHLYYFDCFSDSAIRKALLGHIVSPRCEYQAGHNKVGSLQYLALAALITPKKIKPPLPSVTKLTEDRWNKPQKTKGHRGSHTMNGH

and

MKPHFRNTVERMYRDTFSYNFYNRPILSRRNTVWLCYEVKTKGPSRPPLDAKIFRGQVYSELKYHPEMRFFHWFSKWRKLHRDQEYEVTWYISWSPCTKCTRDMATFLAEDPKVTLTIFVARLYYFWDPDYQEALRSLCQKRDGPRATMKIMNYDEFQHCWSKFVYSQRELFEPWNNLPKYYILLHIMLGEILRHSMDPPTFTFNFNNEPWVRGRHETYLCYEVERMHNDTWVLLNQRRGFLCNQAPHKHGFLEGRHAELCFLDVIPFWKLDLDQDYRVTCFTSWSPCFSCAQEMAKFISKNKHVSLCIFTARIYDDQGRCQEGLRTLAEAGAKISIMTYSEFKHCWDTFVDHQGCPFQPWDGLDEHSQDLSGRLRAILQNQEN

**Comment by sokrypton** [comment]
try again should be fixed! (reopen if you see error again) :D

**Comment by suchloust** [comment]
> try again should be fixed! (reopen if you see error again) :D

That error seems to be resolved! When I tried to run it again though I got a couple more ://
<img width="872" alt="Screen Shot 2021-07-20 at 10 18 05 PM" src="https://user-images.githubusercontent.com/87739710/126420188-16c27523-1562-4ea7-8b07-a060c48288c5.png">

**Comment by sokrypton** [comment]
Can you try do a factory reset and run from beginning? Is it only happening when you run the same notebook again? When you do rerun are you doing "runall" ?

**Comment by suchloust** [comment]
> Can you try do a factory reset and run from beginning? Is it only happening when you run the same notebook again? When you do rerun are you doing "runall" ?

Sorry, I wrote that before resetting! It's working super well now :) Thanks!
