### ISSUE TITLE
Residue with no atoms, causes error with amber (MMseqs2)

### ISSUE THREAD

**Issue by demattox** [sokrypton/ColabFold#30]
While running UniProt ID P02744 (sequence pasted below) in the AlphaFold2 w/ MMseqs2 notebook with templates and amber selected, I get an error from amber saying at least one residue n the protein has no atoms and it can't relax it.

Not sure why this is occurring, i don't HAVE to use the amber minimization (although it would be nice), but I'm worried about what is causing this empty residue in the first place.

Error message:
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-18-af48741e914e> in <module>()
     49                          Ls=[len(query_sequence)]*homooligomer,
     50                          model_params=model_params, use_model=use_model,
---> 51                          do_relax=use_amber)

3 frames
/content/alphafold/relax/amber_minimize.py in _check_residues_are_well_defined(prot)
    139   """Checks that all residues contain non-empty atom sets."""
    140   if (prot.atom_mask.sum(axis=-1) == 0).any():
--> 141     raise ValueError("Amber minimization can only be performed on proteins with"
    142                      " well-defined residues. This protein contains at least"
    143                      " one residue with no atoms.")

ValueError: Amber minimization can only be performed on proteins with well-defined residues. This protein contains at least one residue with no atoms.

![](https://user-images.githubusercontent.com/26228450/130726890-da7a2263-2aa3-4811-8d27-5a258a7565de.png)

P02744 sequence: 

>LEEGEITSKVKFPPSSSPSFPRLVMVGTLPDLQEITLCYWFKVNQLKGTLGHSRVLBMFSYATAKKDNELLTFLDEQGDFLFNV

**Comment by demattox** [comment]
Running it again with templates but without amber minimization ran without any errors and the output model looks fine without any obvious empty residues.
![](https://user-images.githubusercontent.com/26228450/130728322-03c69115-8fde-48da-a94b-01e06bb72cdc.png)
Although on closer inspection of the returned .pdb file from model_1, it appears residue 57 is missing and matches "B" in the text which would appear to be the issue. I'll make an informed selection between Asn/Asp in this case, but some input screening to alert users to ambiguous amino acid characters that will be ignored would be greatly appreciated :)

**Comment by sokrypton** [comment]
@demattox 
thanks for alert, we'll add a check at input.
