### ISSUE TITLE
AttributeError: module 'jax' has no attribute 'tree_multimap'

### ISSUE THREAD

**Issue by MWNautilus** [sokrypton/ColabFold#300]
In the advanced colab notebook, the cell 'run alphafold' crashes with the following error log:

`Running model_1_ptm_seed_0: 0%
0/5 [elapsed: 00:22 remaining: ?]

---------------------------------------------------------------------------

UnfilteredStackTrace                      Traceback (most recent call last)

[<ipython-input-8-bc07f049eb27>](https://localhost:8080/#) in <module>
     67 outs, model_rank = cf_af.run_alphafold(feature_dict, opt, runner, num_models, num_samples, subsample_msa,
---> 68                                        rank_by=rank_by, show_images=show_images)

91 frames

UnfilteredStackTrace: AttributeError: module 'jax' has no attribute 'tree_multimap'

The stack trace below excludes JAX-internal frames.
The preceding is the original exception that occurred, unmodified.

--------------------

The above exception was the direct cause of the following exception:

AttributeError                            Traceback (most recent call last)

[/content/alphafold/alphafold/model/mapping.py](https://localhost:8080/#) in mapped_fn(*args)
    121     in_axes_ = _expand_axes(in_axes, args)
    122 
--> 123     in_sizes = jax.tree_multimap(_maybe_get_size, args, in_axes_)
    124     flat_sizes = jax.tree_flatten(in_sizes)[0]
    125     in_size = max(flat_sizes)

AttributeError: module 'jax' has no attribute 'tree_multimap'`

Michael.

**Comment by sokrypton** [comment]
Thanks! This should be fixed now.
