### ISSUE TITLE
Random seed not fully exposed 

### ISSUE THREAD

**Issue by ryin222** [sokrypton/ColabFold#307]
Hi all, thanks a lot for your excellent work! I have one minor comment about the random seed. My comment is related to https://github.com/sokrypton/ColabFold/issues/227. To fully expose the random seed, it might be a good idea to pass the random seed value along when calling model_runner.predict in this line: https://github.com/sokrypton/ColabFold/blob/22671664ac2c9dcb30086c3e654414d950ccb297/colabfold/batch.py#L359

From what I can tell, the "predict" function in lib/python3.7/site-packages/alphafold/model/model.py downloaded by pip install command will use a default random number of value 0 unless otherwise specified. Therefore, the models generated by batch.py in local colabfold would be deterministic without changing the random number when calling "predict" function.

**Comment by samuelmurail** [comment]
I agree I have launched several multimer colabfold jobs using `batch.py` and with different random seed and the results were identical for all jobs.

**Comment by sokrypton** [comment]
Thanks for the report! The bug has now been fixed.
