### ISSUE TITLE
Axis error when attempting to plot MSA with model type Alphafold2-ptm

### ISSUE THREAD

**Issue by swanss** [sokrypton/ColabFold#312]
## Expected Behavior

Google colab notebook should finish running and save output to a zip file.

## Current Behavior

All predictions are generated and seem to be accurate based on the images output in the notebook, but the program encounters an error when attempting to generate the plots. Based on my understanding of the code, it seems like `lines_to_sort` is empty, so it only has a single, empty dimension.

## Steps to Reproduce (for bugs)
Please provide your input if you can share it. 

1.  Query sequence: MFEPMELTNDAVIKVIGVGGGGGNAVEHMVRERIEGVEFFAVNTDAQALRKTAVGQTIQIGSGITKGLGAGANPEVGRNAADEDRDALRAALEGADMVFIAAGMGGGTGTGAAPVVAEVAKDLGILTVAVVTKPFNFEGKKRMAFAEQGITELSKHVDSLITIPNDKLLKVLGRGISLLDAFGAANDVLKGAVQGIAELITRPGLMNVDFADVRTVMSEMGYAMMGSGVASGEDRAEEAAEMAISSPLLEDIDLSGARGVLVNITAGFDLRLDEFETVGNTIRAFASDNATVVIGTSLDPDMNDEL:KLLKVLGRGISLLDAFGAANDVLKGAVQGI
2. Template mode: none
3. pair mode: unpaired
4. model type: AlphaFold2-ptm

All other settings are the default

## ColabFold Output (for bugs)
---------------------------------------------------------------------------
AxisError                                 Traceback (most recent call last)
[<ipython-input-13-cc18ff423952>](https://localhost:8080/#) in <module>
     56     stop_at_score=float(100),
     57     prediction_callback=prediction_callback,
---> 58     dpi=dpi
     59 )

2 frames
[/usr/local/lib/python3.7/dist-packages/colabfold/batch.py](https://localhost:8080/#) in run(queries, result_dir, num_models, num_recycles, model_order, is_complex, num_ensemble, model_type, msa_mode, use_templates, custom_template_path, use_amber, keep_existing_results, rank_by, pair_mode, data_dir, host_url, random_seed, stop_at_score, recompile_padding, recompile_all_models, zip_results, prediction_callback, save_single_representations, save_pair_representations, training, use_gpu_relax, stop_at_score_below, dpi, max_msa)
   1435             query_sequence_len_array,
   1436             query_sequence_len,
-> 1437             dpi=dpi,
   1438         )
   1439         coverage_png = result_dir.joinpath(jobname + "_coverage.png")

[/usr/local/lib/python3.7/dist-packages/colabfold/plot.py](https://localhost:8080/#) in plot_msa(msa, query_sequence, seq_len_list, total_seq_len, dpi)
     54         else:
     55             lines_to_sort = np.array(lines_to_sort)
---> 56             lines_to_sort = lines_to_sort[np.argsort(-np.nanmax(lines_to_sort, axis=1))]
     57             lines += lines_to_sort.tolist()
     58             lines_to_sort = []

<__array_function__ internals> in nanmax(*args, **kwargs)

[/usr/local/lib/python3.7/dist-packages/numpy/lib/nanfunctions.py](https://localhost:8080/#) in nanmax(a, axis, out, keepdims)
    432         # Fast, but not safe for subclasses of ndarray, or object arrays,
    433         # which do not implement isnan (gh-9009), or fmax correctly (gh-8975)
--> 434         res = np.fmax.reduce(a, axis=axis, out=out, **kwargs)
    435         if np.isnan(res).any():
    436             warnings.warn("All-NaN slice encountered", RuntimeWarning,

AxisError: axis 1 is out of bounds for array of dimension 1

## Context
Providing context helps us come up with a solution and improve our documentation for the future.

There is no error when running with model type: Alphafold2-multimer-v2. I'm not sure what exactly differs between the models, but I think this could be helpful for tracking down the issue. Using the monomer version is important for my application, as it seems to predict models with higher confidence with my specific set of proteins.

## Your Environment
Include as many relevant details about the environment you experienced the bug in.

I saved a copy of the notebook to my drive, here's a link: https://colab.research.google.com/drive/1oxE5ntH-idscp0clMQL7obmepSTs39Qb?usp=sharing

**Comment by sokrypton** [comment]
Should be fixed.
