### ISSUE TITLE
IndexError: list index out of range in Display 3D structure

### ISSUE THREAD

**Issue by WalterFu1024** [sokrypton/ColabFold#329]
I'm trying to predict the protein structure using MMSequence2 mode

IndexError:  list index out of range in Display 3D structure

---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
[<ipython-input-34-4f3f55b1da52>](https://localhost:8080/#) in <module>
     47 
     48 
---> 49 show_pdb(rank_num,show_sidechains, show_mainchains, color).show()
     50 if color == "lDDT":
     51   plot_plddt_legend().show()

[<ipython-input-34-4f3f55b1da52>](https://localhost:8080/#) in show_pdb(rank_num, show_sidechains, show_mainchains, color)
     20   model_name = f"rank_{rank_num}"
     21   view = py3Dmol.view(js='https://3dmol.org/build/3Dmol.js',)
---> 22   view.addModel(open(pdb_file[0],'r').read(),'pdb')
     23 
     24   if color == "lDDT":

IndexError: list index out of range

![image](https://user-images.githubusercontent.com/88904613/201788831-728ed03f-c2fa-4301-8cd6-772fac356b5d.png)

protein sequence:
TIKEMPQPKTFGELKNLPLLNTDKPVQALMKIADELGEIFKFEAPGRVTRYLSSQRLIKEACDESRFDKNLSQGFKFCRDFLGDGLATSWTHEKNWKKAHNILLPSFSQQAMKGYHAMMVDIAVQLVQKWERLNADEHIEVSEDMTRLTLDTIGLCGFNYRFNSFYRDQPHPFIISLVRAMDEVMNKLQRANPDDPAYDENKRQFQEDIKVMNDLVDKIIADRKARGEQSDDLLTQMLNGKDPETGEPLDDGNIRYQIITFLQAGHEPTSGLLSFALYFLVKNPHVLQKVAEEAARVLVDPVPSYKQVKQLKYVGMVLNEALRLWPPVPAFSLYAKEDTVLGGEYPLEKGDEVMVLIPQLHRDKTVWGDDVEEFRPERFENPSAIPQHAFKPFGNGQRASIGQQFALHEATLVLGMMLKHFDFEDHTNYELDIKEAPTLKPKGFVVKAKSKKIPLGGIPSPSTEQSAKKVRKKAENAHNTPLLVLYGSNMGTAEGTARDLADIAMSKGFAPQVATLDSHAGNLPREGAVLIVTASYNGHPPDNAKQFVDWLDQASADEVKGVRYSVFGCGDKNWATTYQKVPAFIDETLAAKGAENIADRGEADASDDFEGTYEEWREHMWSDVAAYFNLDIENSEDNKSTLSLQFVDSAADMPLAKMHGAFSTLEHHHHHH*

**Comment by WalterFu1024** [comment]
![image](https://user-images.githubusercontent.com/88904613/201789033-400d3f6e-f7f8-4726-a4a9-d17b6d7a5640.png)
![image](https://user-images.githubusercontent.com/88904613/201789108-8d4ae12d-f6a4-4591-96f0-2bdb50a0304a.png)
![image](https://user-images.githubusercontent.com/88904613/201789138-7db049f2-45b3-44ed-97c3-fab89be31ec1.png)

**Comment by YoshitakaMo** [comment]
Don't include `*` character in the input sequence. Remove `*` and try again.

**Comment by WalterFu1024** [comment]
> 

Thanks, it's working now!
