### ISSUE TITLE
Amber-relax fails

### ISSUE THREAD

**Issue by kkorotkov27** [sokrypton/ColabFold#33]
Amber-relax fails on some structures. For example:

/usr/local/lib/python3.7/dist-packages/jax/interpreters/xla.py in _execute_compiled_primitive(prim, compiled, result_handler, *args)
    388   device, = compiled.local_devices()
    389   input_bufs = list(it.chain.from_iterable(device_put(x, device) for x in args if x is not token))
--> 390   out_bufs = compiled.execute(input_bufs)
    391   check_special(prim.name, out_bufs)
    392   return result_handler(*out_bufs)

RuntimeError: Internal: Failed to load in-memory CUBIN: CUDA_ERROR_ILLEGAL_ADDRESS: an illegal memory access was encountered

**Comment by sokrypton** [comment]
Hmmm... can you share the sequence it fails on? (you can email me if it's confidential: so@fas.harvard.edu)

**Comment by kkorotkov27** [comment]
Here is the sequence:

IENPCAEPNGSNTKHRAIAHNVAYHTQKDAHAEASKRGLSKLRAHAEKGEYALRGKSSVLNDVCKITLKHSNRNPAQSTGPCNGKDGDNKRFKIGTPWKGGEQVSTSYSDVFLPPRRQHMCTSNLEHLNTKSTGLSESKLASNSLLGDVLLAAKYEAEDIKKNYKERNGQIDNKGKCRAIRYSFADLGDIIRGRDLWDLDEGSKKMEGHLKKIFKQIKEKHPGVQEKYNSDNDYNKYINLRSDWWEANRHKVWKAMKCEISELKDMSGHHASSSHCGYSHGMPVDDYIPQRLRWMTEWAEWYCKAQSQEYDKLMGACGSCMGKGKVQGCTSGDVDSVKKCEKCKTACDEYWNKIKPWKGQWNTMEIKYLTLYAYAQMASNNKGDMSIFGNAVGPKDKPVVQILQELLPPKSVKPGAPTPTLTSPYFTAAGYIHQEARVGECEEQKHFCTSGDKENKDKYAFREKPKDHDDACACENNTKPQPAP

I ran it again today, still fails. Quite puzzling...

**Comment by sokrypton** [comment]
@kkorotkov27 which notebook are you using?

**Comment by sokrypton** [comment]
It looks like alphafold code is doing something dumb. They run amber on CPU, but then switch to GPU to compute violations (clashes) which then controls how many iterations are run. To fix this error, one option would be to force the clash check to also run on CPU. I'll see what we can do!
