### ISSUE TITLE
"ValueError: I/O operation on closed file" even for test sequence when using amber minimization

### ISSUE THREAD

**Issue by norbert1000** [sokrypton/ColabFold#331]
## Expected Behavior
no errors :-)!

## Current Behavior
ColabFold stops with error: "ValueError: I/O operation on closed file"

## Steps to Reproduce (for bugs)
After loading the ColabFold page with the test sequence, change the following options:
-activate "use_amber"
-template_mode: pdb70

The error is linked to amber minimization. If you do not request this, everything is fine.

The error occurs with custom sequences but also with the short test sequence.

## ColabFold Output (for bugs)
ValueError                                Traceback (most recent call last)

[<ipython-input-26-cc18ff423952>](https://localhost:8080/#) in <module>
     56     stop_at_score=float(100),
     57     prediction_callback=prediction_callback,
---> 58     dpi=dpi
     59 )

3 frames

[/usr/local/lib/python3.7/dist-packages/alphafold/relax/utils.py](https://localhost:8080/#) in overwrite_b_factors(pdb_str, bfactors)
     67   pdb_io.set_structure(structure)
     68   pdb_io.save(new_pdb)
---> 69   return new_pdb.getvalue()
     70 
     71 

ValueError: I/O operation on closed file

## Context
no special context

## Your Environment
running in a ColabNotebook, not locally

Thanks,

Norbert

**Comment by milot-mirdita** [comment]
The issue should be fixed now.

**Comment by norbert1000** [comment]
Yes, it runs fine now. Thanks  a lot!
