### ISSUE TITLE
`colabfold_batch` is not using all available GPUs

### ISSUE THREAD

**Issue by dsclassen** [sokrypton/ColabFold#337]
## Expected Behavior

I would expect multiple independent instances of `colabfold_batch` to take advantage of the presence of multiple GPUs.

## Current Behavior

submitting multiple simultaneous jobs results in all jobs using a single GPU.

## Your Environment
Using https://github.com/sokrypton/ColabFold/commit/b41ed8d6e98bf33a82307557f3e9102bd34eeafe

Machine is running Rocky Linux 8.7
AMD EPYC 7643
256GB RAM
2x NVIDIA A100-80 GPUs

**Comment by stanislc** [comment]
Check #36

**Comment by dsclassen** [comment]
Thanks for the tip. setting these variables allows me to specify one of the two available GPUs.

`export CUDA_VISIBLE_DEVICES=0`
or
`export CUDA_VISIBLE_DEVICES=1`
