### ISSUE TITLE
Colabfold failing to load openmm

### ISSUE THREAD

**Issue by MartinStoermer** [sokrypton/ColabFold#338]
## Expected Behavior

using shared colabfold "AlphaFold2 using MMseqs2" 
## Current Behavior
after first model is built and jobs proceeds to model relaxation with amber, the jobb fails to load the openmm module

## Steps to Reproduce (for bugs)

1) add sequences
2) select Run All

## ColabFold Output (for bugs)

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
[<ipython-input-5-a6916f1f3a7f>](https://localhost:8080/#) in <module>
     33 model_type = set_model_type(is_complex, model_type)
     34 download_alphafold_params(model_type, Path("."))
---> 35 run(
     36     queries=queries,
     37     result_dir=result_dir,

4 frames
[/usr/local/lib/python3.7/site-packages/simtk/openmm/openmm.py](https://localhost:8080/#) in <module>
     11 # Import the low-level C/C++ module
     12 if __package__ or "." in __name__:
---> 13     from . import _openmm
     14 else:
     15     import _openmm

ImportError: cannot import name '_openmm' from partially initialized module 'simtk.openmm' (most likely due to a circular import) (/usr/local/lib/python3.7/site-packages/simtk/openmm/__init__.py)

---------------------------------------------------------------------------
NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.

To view examples of installing some common dependencies, click the
"Open Examples" button below.
---------------------------------------------------------------------------

## Context

just running as have done multiple times, using the shared workspace that I made a copy of in my home dir. Worked as recent;y as last night.

## Your Environment
running a copy of the AlphaFold2.ipynb notebook (no changes made, just saved a copy in my Google Drive, inside Chrome Version 103.0.5060.134 (Official Build) (x86_64) on MacOS 10.12.6 (16G2136)
<img width="1170" alt="Screen Shot 2022-12-01 at 9 08 43 am" src="https://user-images.githubusercontent.com/119544795/204929431-2de16249-fb90-4ffd-b651-4b4ddbe2ad9a.png">

**Comment by alexwu66666** [comment]
Hi Martin,

I also have this issue, it suddenly happened today. Have you solved this problem?

Best regards,
Chao

**Comment by milot-mirdita** [comment]
I pushed a fix earlier, openmm should work again.

**Comment by MartinStoermer** [comment]
> I pushed a fix earlier, openmm should work again.

Thank you. Had to delete my saved copies and make a new copy in my G Drive, but it is working now
