### ISSUE TITLE
Import error for tensorflow in the cell4- Search against genetic databases while running alphafold2 colabfold

### ISSUE THREAD

**Issue by anpanche** [sokrypton/ColabFold#341]
## Current Behavior
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
[/opt/conda/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow.py](https://localhost:8080/#) in <module>
     61   try:
---> 62     from tensorflow.python._pywrap_tensorflow_internal import *
     63   # This try catch logic is because there is no bazel equivalent for py_extension.

ImportError: Python version mismatch: module was compiled for Python 3.7, but the interpreter version is incompatible: 3.8.15 (default, Oct 12 2022, 19:14:39) 
[GCC 7.5.0].

During handling of the above exception, another exception occurred:

ImportError                               Traceback (most recent call last)
8 frames
[/opt/conda/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow.py](https://localhost:8080/#) in <module>
     75     sys.setdlopenflags(_default_dlopen_flags)
     76 except ImportError:
---> 77   raise ImportError(
     78       f'{traceback.format_exc()}'
     79       f'\n\nFailed to load the native TensorFlow runtime.\n'

ImportError: Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 62, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: Python version mismatch: module was compiled for Python 3.7, but the interpreter version is incompatible: 3.8.15 (default, Oct 12 2022, 19:14:39) 
[GCC 7.5.0].

## Steps to Reproduce (for bugs)
Please make sure to reproduce the issue after a "Factory Reset" in Colab. 
If running locally ypdate you local installation `colabfold_batch` to the newest version.
Please provide your input if you can share it. 

## ColabFold Output (for bugs)
Please make sure to also post the complete ColabFold output. You can use gist.github.com for large output.

## Context
Providing context helps us come up with a solution and improve our documentation for the future.

## Your Environment
Include as many relevant details about the environment you experienced the bug in.
* Git commit used
* If you run it on a local system. Please add the server specifications
* Operating system and version:

**Comment by milot-mirdita** [comment]
Which notebook is this?

**Comment by anpanche** [comment]
Alphafold (DeepMind)

**Comment by milot-mirdita** [comment]
Please refer to the DeepMind GitHub issues for support for their notebook.
