### ISSUE TITLE
Singularity installations?

### ISSUE THREAD

**Issue by shahpnmlab** [sokrypton/ColabFold#35]
Hi,

I was wondering if the project could be integrated into a singularity installation of AlphaFold2. If yes, how would one go about achieving it?

Best,
Pranav

**Comment by truatpasteurdotfr** [comment]
One can "just" build a singularity container based on the work done by Yoshitaka Moriwaki and alphafold dockerfile, imho.

**Comment by tubiana** [comment]
Old topic but if you are interested @truatpasteurdotfr and @shahpnmlab, I just made one based on the AF2 docker image and the work one by Yoshitaka Moriwaki (https://github.com/YoshitakaMo/localcolabfold)
The usage is quite specific to our cluster for now but you change modify it / improve it and share it if you want. 
here's the link: https://github.com/tubiana/colabfold_singularity

Best,
Thibault.

**Comment by milot-mirdita** [comment]
We finally have actual Docker images on the GitHub container registry that we are going to keep maintaining from now on:
https://github.com/sokrypton/ColabFold/pkgs/container/colabfold

I don't know about singularity. If you have some instructions on how we can provide singularity containers. I'd be happy to look into.

**Comment by shahpnmlab** [comment]
Thanks! Will check with our sysadmins, if this plays nice with their sec policies.

**Comment by milot-mirdita** [comment]
I also just tried the Docker container together with singularity and it seems to work fine. I updated the guide above.
I am not making a separate Singularity container for now as the Docker container seems to work well with Singularity.
