### ISSUE TITLE
RATELIMIT FOREVER in Colab FOREVER even if I bought Colab Pro+! Is there any update currently?

### ISSUE THREAD

**Issue by DoraCiCy** [sokrypton/ColabFold#350]
## Steps to Reproduce (for bugs)
Commonly input amino acid sequences in query_sequence box 
click run all and no process  and RATELIMIT in the box of Run Prediction    FOREVER!!!

**Comment by milot-mirdita** [comment]
We had a hardware failure on the MSA server. We swapped to a backup server, everything should be back in working order for now.
