### ISSUE TITLE
Possible to expose last MSA or pair representation for embedding?

### ISSUE THREAD

**Issue by yoann-glanum** [sokrypton/ColabFold#351]
Hello, 

I've been looking at the ColabFold notebooks and some of the papers that add tweaks and optimisations to the AlphaFold 2 system, and was wondering if it could be possible to expose as optional outputs the last 1D MSA representation or the last 2D Pairwise representation that are fed (by my understanding) to the last Structure Block ?

This would enable using a simple 1D or 2D vector as a structure-aware embedding for downstream tasks, even if only for an AlphaFold-based clustering, instead of having to use the .pdb or the self-confidence files to post-process a new object like a distogram. Such embeddings, especially together, might have enough information to already suffice for new ML approaches for many Comp Bio or Comp Chem tasks.

If there are any way to do this with the current notebooks or ways to work around the current outputs to reverse-engineer them, please let me know !

**Comment by martin-steinegger** [comment]
We do have a way to write out the representation using the locally installed Colabfold, thanks to the PR from @lucidrains (see https://github.com/sokrypton/ColabFold/pull/180). Just use the `"--save-single-representations` or `--save-pair-representations` flag. You could also get the representations in the Notebook by providing the flags to the `run` function in the `Run Prediction` cell.
