### ISSUE TITLE
py3Dmol window not shown

### ISSUE THREAD

**Issue by ajasja** [sokrypton/ColabFold#355]
## Expected Behavior
3D structures are shown at the bottom

## Current Behavior
The part where the py3dmol window should go is blank

## Steps to Reproduce (for bugs)
Run a golabfold notebook

## Workaround
I added `pip install -U py3dmol` to the dependencies cell and that solves the problem.

**Comment by sokrypton** [comment]
Thanks! We've updated to latest py3Dmol which should fix this issue.
