### ISSUE TITLE
Can i use colabfold run multiple monomer structure?

### ISSUE THREAD

**Issue by yang-nei** [sokrypton/ColabFold#362]
there are hundreds of monomer i shall run ,but i don't wanna copy-paste the sequence one by one on my own, what can i do?

**Comment by milot-mirdita** [comment]
We have a separate notebook to batch compute structures:
https://colab.research.google.com/github/sokrypton/ColabFold/blob/main/batch/AlphaFold2_batch.ipynb

Or you install ColabFold locally, then you can use the `colabfold_batch` script for the same purpose.

**Comment by ChampInMyThought** [comment]
Could you please give me a kind introduction to using the ColabFold v1.5.1: AlphaFold2 w/ MMseqs2 BATCH?
I have been trying to run multiple multimers by creating a fasta file as follows:

>seq0
MKDNTVPLKLIALLANGEFHSGEQLGETLGMSRAAINKHIQTLRDWGVDVFTVPGKGYSLPEPIQLLNAKQILGQLDGGSVAVLPVIDSTNQYLLDRIGELKSGDACIAEYQQAGRGRRGRKWFSPFGANLYLSMFWRLEQGPAAAIGLSLVIGIVMAEVLRKLGADKVRVKWPNDLYLQDRKLAGILVELTGKTGDAAQIVIGAGINMAMRRVEESVVNQGWITLQEAGINLDRNTLAAMLIRELRAALELFEQEGLAPYLSRWEKLDNFINRPVKLIIGDKEIFGISRGIDKQGALLLEQDGIIKPWMGGEISLRSAEK:GLNDIFEAQKVEWHE

>seq1
MKDNTVPLKLIALLANGEFHSGEQLGETLGMSRAAINKHIQTLRDWGVDVFTVPGKGYSLPEPIQLLNAKQILGQLDGGSVAVLPVIDSTNQYLLDRIGELKSGDACIAEYQQAGRGRRGRKWFSPFGANLYLSMFWRLEQGPAAAIGLSLVIGIVMAEVLRKLGADKVRVKWPNDLYLQDRKLAGILVELTGKTGDAAQIVIGAGINMAMRRVEESVVNQGWITLQEAGINLDRNTLAAMLIRELRAALELFEQEGLAPYLSRWEKLDNFINRPVKLIIGDKEIFGISRGIDKQGALLLEQDGIIKPWMGGEISLRSAEK:GLNDIFEAQKIEWHE

However, it keeps returning an error message back on the prediction process

[/usr/local/lib/python3.8/dist-packages/colabfold/batch.py](https://localhost:8080/#) in parse_fasta(fasta_string)
    580         elif not line:
    581             continue  # Skip blank lines.
--> 582         sequences[index] += line
    583 
    584     return sequences, descriptions

IndexError: list index out of range
