### ISSUE TITLE
"ptmscore" vs "ptmscores" error in the model ranking for multimer?

### ISSUE THREAD

**Issue by yoann-glanum** [sokrypton/ColabFold#364]
I was looking at the batch.py code to modify the use of the rank_by parameter, and found that in the section that uses it for ranking models, the list of all ptm scores "**ptmscores**" and the latest "**ptmscore**" (by my understanding) seem to be swapped : 

beta branch, colabfold/batch.py : 
```
if rank_by == "ptmscore":
        model_rank = np.array(ptmscores).argsort()[::-1]
    elif rank_by == "multimer":
        model_rank = (np.array(iptmscores) * 0.8 + np.array(ptmscore) * 0.2).argsort()[::-1]
    else:
        model_rank = np.array(plddts).argsort()[::-1]
```
I think the one in the "multimer" condition should be "**ptmscores**" like in the ptm condition.

(also we could swap the ptm and plddt to homogenise with the early stop section that goes "ptm by default, or plddt if precised")

**Comment by sokrypton** [comment]
fixed it!

Thanks
https://github.com/sokrypton/ColabFold/commit/995965894a0c6e3b173fa597f4057910ab8158c3

**Comment by sokrypton** [comment]
Good catch! I'll fix that .
