### ISSUE TITLE
plddt is [0-100] while ptm and iptm are [0.__-1] for early stopping

### ISSUE THREAD

**Issue by yoann-glanum** [sokrypton/ColabFold#366]
In the current batch.py of the beta branch, the mean_plddt works with values such as '90' for 90%, meaning doing a rank_by that tracks the plddt will work with a "stop_at_score = 90", but mean_ptm and mean_iptm work with values such as '0.9' for 90%, meaning we'd have to do "stop_at_score = 0.9" for it to work. 

I tested out putting everything at [0-100] in the mean_score declaration and now it works fine :), a straight up multiplication like 
```
            mean_score = mean_ptm*100 # by default, overwrite if needed
            if rank_by == "plddt":
                mean_score = mean_plddt
            elif rank_by == "multimer":
                if is_complex or "ptm" in model_type:
                    if "multimer" in model_type:
                        mean_iptm = float(prediction_result["iptm"]) # need a float cast?
                        mean_score = mean_iptm * 0.8 + mean_ptm * 0.2
                        mean_score *= 100
``` 
and then the rest works fine without touching the stop_at_score or the if break condition. I figure it's simpler than detailing that in the Notebook/interface

**Comment by sokrypton** [comment]
Thanks! This has been added in beta branch!
