### ISSUE TITLE
About GPU in jupyter

### ISSUE THREAD

**Issue by MontaEllis** [sokrypton/ColabFold#37]
Hi, I wonder how to use GPU during inference in jupyter. It seems that it only use CPU. I don't know how to setting it.

**Comment by MontaEllis** [comment]
I use this jupter: https://github.com/sokrypton/ColabFold/blob/main/AlphaFold2.ipynb

**Comment by blakely3dnm** [comment]
Check that your python environment is set up to run the notebook. You need tensorflow, jax, and google-colab libraries among others. There may be some terminal messages from jupyter to help narrow down the issue.

**Comment by MontaEllis** [comment]
I've already checked my setting, but it still run on cpu. And the colab you provided runs using cpu too. I don't know what I set wrong.
