### ISSUE TITLE
Sequences from Different Organisms Appear to be Paired in MSAs

### ISSUE THREAD

**Issue by kaymccoy** [sokrypton/ColabFold#376]
## Expected Behavior

I expect that the paired sequences in the paired.msa file will come from the same organism, and so have the same ID.

## Current Behavior

However, the IDs look different for most paired sequences in the paired.msa file (like UPI0018999C64 is paired with UPI00148EFEA5, for example). My apologies if I'm misunderstanding this - I think that in the paired.msa output file, the first sequence under the first query is paired with the first sequence under the second query and first sequence under the third query, etc., and expect all paired sequences to have the same identifier. However, I'm not seeing that happening. Is there perhaps something wrong in my assumptions? If so, is there possibly a different way to identify what organism the MSA matches come from, according to their IDs? 

EDIT: I've attached an example pair.a3m file (with the .txt extension added so that it can be uploaded to github) if that's helpful [pair.a3m.txt](https://github.com/sokrypton/ColabFold/files/10669768/pair.a3m.txt)

Thank you for your time!

**Comment by sokrypton** [comment]
The example you posted, appears to be from the same organism...
https://www.uniprot.org/uniparc/UPI00148EFEA5/entry
https://www.uniprot.org/uniparc/UPI0018999C64/entry

I'll check the other from pair.a3m.txt

**Comment by sokrypton** [comment]
I checked the first 3 and they appear correct...

**Comment by kaymccoy** [comment]
Oh I had a misunderstanding about the IDs, I thought they would be the same if they were from the same organism, and googling the IDs didn't give any hits. I didn't realize how Uniprot IDs worked, thanks so much!
