### ISSUE TITLE
Omegafold beta missing biopython package

### ISSUE THREAD

**Issue by greyson9** [sokrypton/ColabFold#379]
## Expected Behavior
Successful import of all packages and modules

## Current Behavior
Error: no module named Bio

## Steps to Reproduce (for bugs)
Input sequence: MKKSQETLRVRKKEDKNQVRKTPEKFPVSPLKTDKSPERIIVSSFKAPNATRSSTSKEKSDKNIPVDFLTYENAILRSIFKFSHHRVDVIFRKWHSTASVKEYSDKKKKIERFIELLNGGLKKSTKKCLIIPPEPKSRDTILTNALLAICKNIIFIKGRLFNKWARCSTPIMARFQEYLLKNLAKILKISLQTYFAKWKNTQRTVDSAKMFGMIAVLQRIFANKGKRVFHPPYIVKDADEIMRRTIKKIRSIIHGLYDSAFIRWHYHKIACNIREKACVFYRACQLASNPIKNAFSFWREKLHSKVTVMRTSGTSKMVRALDKCFRARFKLLLFKTYLKIKPKKLLFRVFNFYSKKYCDETRSSFYLWKLSKESSDGKALQILKDSAVFDIIKNWKKSINYKLKQGFYGFMKNNKHRKLILIRAFITSWKIKKIQAWDRLKALSKDHTKKFKALKMATALKRATRRPQKYGLSKFIIVFPLRSAVSHLVYLFTLRMQRALFACSLFAKNLENVDIKTMTRGLRKDLKKERLRSGKATARSFAEVIKNIPRRVLGVSLKRITIDDEKKIKISIRAMINVFIIRPKEALATWFKFMHAVKNG

## ColabFold Output (for bugs)
Please make sure to also post the complete ColabFold output. You can use gist.github.com for large output.

## Context
I tried running this in Colab and it failed. Adding !pip install biopython to the first cell before running it resolved the error

## Your Environment
T4 GPU

This is a fantastic program, thank you for building it!

**Comment by sokrypton** [comment]
That is strange, we already have pip install biopython...
<img width="778" alt="image" src="https://user-images.githubusercontent.com/4187522/218609972-b2846ddf-fdc4-4e9f-b9a0-8d1f778b8335.png">

**Comment by greyson9** [comment]
I was unable to replicate this when I last ran the script, so I'm closing this issue.
