### ISSUE TITLE
.a3m MSA requires re-align

### ISSUE THREAD

**Issue by twaksman001** [sokrypton/ColabFold#385]
In the MSA file (.a3m) for AlphaFold2, multiple sequences are clearly not aligned with others, and re-aligning (using e.g. TCoffee or MAFFT) results in much better alignment, indicated by much higher average residue conservation score. Can you explain why this is?

**Comment by sokrypton** [comment]
The a3m format is a little funny and requires a little processing to
actually see the alignment correctly. It only contains information how all
the sequences are aligned to the first sequence (aka the query).
If you delete all lowercase letters (these are positions not aligned to
query) you'll see all sequences are aligned and same length as query.
