### ISSUE TITLE
[IndexError: list index out of range] - How to properly use ColabFold v1.5.1: AlphaFold2 w/ MMseqs2 BATCH?

### ISSUE THREAD

**Issue by ChampInMyThought** [sokrypton/ColabFold#396]
Could someone please give me a kind introduction to using the ColabFold v1.5.1: AlphaFold2 w/ MMseqs2 BATCH? I am not sure whether I did not manage to use it properly or what is the reason for the IndexError shown below. I have been trying to run multiple multimers by creating a fasta file as follows:

>seq0
MKDNTVPLKLIALLANGEFHSGEQLGETLGMSRAAINKHIQTLRDWGVDVFTVPGKGYSLPEPIQLLNAKQILGQLDGGSVAVLPVIDSTNQYLLDRIGELKSGDACIAEYQQAGRGRRGRKWFSPFGANLYLSMFWRLEQGPAAAIGLSLVIGIVMAEVLRKLGADKVRVKWPNDLYLQDRKLAGILVELTGKTGDAAQIVIGAGINMAMRRVEESVVNQGWITLQEAGINLDRNTLAAMLIRELRAALELFEQEGLAPYLSRWEKLDNFINRPVKLIIGDKEIFGISRGIDKQGALLLEQDGIIKPWMGGEISLRSAEK : GLNDIFEAQKVEWHE

>seq1
MKDNTVPLKLIALLANGEFHSGEQLGETLGMSRAAINKHIQTLRDWGVDVFTVPGKGYSLPEPIQLLNAKQILGQLDGGSVAVLPVIDSTNQYLLDRIGELKSGDACIAEYQQAGRGRRGRKWFSPFGANLYLSMFWRLEQGPAAAIGLSLVIGIVMAEVLRKLGADKVRVKWPNDLYLQDRKLAGILVELTGKTGDAAQIVIGAGINMAMRRVEESVVNQGWITLQEAGINLDRNTLAAMLIRELRAALELFEQEGLAPYLSRWEKLDNFINRPVKLIIGDKEIFGISRGIDKQGALLLEQDGIIKPWMGGEISLRSAEK : GLNDIFEAQKIEWHE

However, it keeps returning an error message back on the prediction process:

[/usr/local/lib/python3.8/dist-packages/colabfold/batch.py](https://localhost:8080/#) in parse_fasta(fasta_string)
    580         elif not line:
    581             continue  # Skip blank lines.
--> 582         sequences[index] += line
    583 
    584     return sequences, descriptions

IndexError: list index out of range

I am really new to the project so thank you everyone so much in advance.

**Comment by sokrypton** [comment]
What does your fasta file look like?
does the header have ">" ?

**Comment by ChampInMyThought** [comment]
Here are the name and format of my file.

file_name = my_fasta.fasta
`
>seq0
MKDNTVPLKLIALLANGEFHSGEQLGETLGMSRAAINKHIQTLRDWGVDVFTVPGKGYSLPEPIQLLNAKQILGQLDGGSVAVLPVIDSTNQYLLDRIGELKSGDACIAEYQQAGRGRRGRKWFSPFGANLYLSMFWRLEQGPAAAIGLSLVIGIVMAEVLRKLGADKVRVKWPNDLYLQDRKLAGILVELTGKTGDAAQIVIGAGINMAMRRVEESVVNQGWITLQEAGINLDRNTLAAMLIRELRAALELFEQEGLAPYLSRWEKLDNFINRPVKLIIGDKEIFGISRGIDKQGALLLEQDGIIKPWMGGEISLRSAEK

>seq1
MKDNTVPLKLIALLANGEFHSGEQLGETLGMSRAAINKHIQTLRDWGVDVFTVPGKGYSLPEPIQLLNAKQILGQLDGGSVAVLPVIDSTNQYLLDRIGELKSGDACIAEYQQAGRGRRGRKWFSPFGANLYLSMFWRLEQGPAAAIGLSLVIGIVMAEVLRKLGADKVRVKWPNDLYLQDRKLAGILVELTGKTGDAAQIVIGAGINMAMRRVEESVVNQGWITLQEAGINLDRNTLAAMLIRELRAALELFEQEGLAPYLSRWEKLDNFINRPVKLIIGDKEIFGISRGIDKQGALLLEQDGIIKPWMGGEISLRSAEK:GLNDIFEAQKIEWHE
`

**Comment by ChampInMyThought** [comment]
And, both seq is in the same file with ">" in the header separating each sequence.

**Comment by ChampInMyThought** [comment]
//More information in case it might be useful

I have tried to divide each sequence into its only fasta file and put them in the directory as the following path:
input_dir = '/content/drive/MyDrive/AlphaFold/input_fasta' #@param {type:"string"}

Still get the same error message:
IndexError                                Traceback (most recent call last)
[<ipython-input-14-d86446d02b7c>](https://localhost:8080/#) in <module>
     16     logging_setup = True
     17 
---> 18 queries, is_complex = get_queries(input_dir)
     19 run(
     20     queries=queries,

1 frames
[/usr/local/lib/python3.8/dist-packages/colabfold/batch.py](https://localhost:8080/#) in parse_fasta(fasta_string)
    580         elif not line:
    581             continue  # Skip blank lines.
--> 582         sequences[index] += line
    583 
    584     return sequences, descriptions

IndexError: list index out of range

**Comment by ChampInMyThought** [comment]
Okay, I finally found the issues and it's way more simple than I think.

My header did not simply contain ">" on the front as the way I created the fasta file is by TextEdit on Mac and then changing the file extension from .rtf to .fasta

I found this out after I download MEGA Software which indeed allows me to open an actual file that I have and edit them.

I have been playing around with this all night and hope this would be useful to others, additional simple way to check whether your file is correct is you should not be able to inspect your fasta file on Google Drive.

I would close the issues now. However, I still have a question. What is the simplest way I can properly create a .fasta file on mac? Now I have opened the incorrect fasta file in MEGA and then edited from there (which a lot of time this make the program crash)

**Comment by sokrypton** [comment]
technically you can use TextEdit on Mac, you just need to disable rich text formatting:
<img width="442" alt="image" src="https://user-images.githubusercontent.com/4187522/221096699-92b573ba-f4da-467f-be13-36ebfcef8963.png">

**Comment by ChampInMyThought** [comment]
Thank you so much <3
