### ISSUE TITLE
OOM with 1.8k residues on a 40GB A100

### ISSUE THREAD

**Issue by Abhishaike** [sokrypton/ColabFold#405]
## Expected Behavior
Inference should be possible, given that 2000 residue proteins should be inference-able on a T4. 

## Current Behavior
Errors out with
```
  Not Enough GPU memory? INTERNAL: RET_CHECK failure (ex
ternal/org_tensorflow/tensorflow/compiler/xla/service/gpu/gpu_compiler.cc:627) dnn != nullptr

```
## Steps to Reproduce (for bugs)
Run a multimer protein >1800 in length on a 40GB A100

## ColabFold Output (for bugs)

2023-03-06 20:29:16,343 Query 1/1: PROTEIN_AAA_333_BBB (length 1846)

https://gist.github.com/Abhishaike/22353036fba791b63ed16ad0da991a1e

## Your Environment
Include as many relevant details about the environment you experienced the bug in.
Used colabfold 1.5.2 and cuda 11.7

**Comment by sokrypton** [comment]
Can you try add the flag:
--disable-unified-memory

**Comment by Abhishaike** [comment]
Tried adding that @sokrypton and also tried disabling padding, neither worked. Running it on Colab runs fine, but the problem persists in my local environment.

 Is there some Jax/TF/otherwise update that's on Colab that's not in the requirements/toml?

**Comment by sokrypton** [comment]
are you installing using localcolabfold?
https://github.com/YoshitakaMo/localcolabfold

**Comment by Abhishaike** [comment]
The issue was that I was upgrading the Jax in localcolabfold prior to running this, removing the upgrade fixed the problem.
