### ISSUE TITLE
Error during "Set-up AlphaFold" step 

### ISSUE THREAD

**Issue by nkiely** [sokrypton/ColabFold#413]
## Current Behavior I am getting "file not found" errors as can be seen in the image below
![image](https://user-images.githubusercontent.com/127661993/225224239-d589a8c5-f36a-426e-b6cd-b4e06b2484ac.png)

## Steps to Reproduce (for bugs)
Input: VLVITAIAKFERLQTVTNYFITSLACADLVMGLAVVPFGAAHILMKMWTFGNFWCEFWTSIDVLCVTASIETLCVIAVDRYFAITSPFKYQSLLTKNKARVIILMVWIVSGLTSFLPIQMHWYRATHQEAINCYANETCCDFFTNQAYAIASSIVSFYVPLVIMVFVYSRVFQEAKRQLQKIDKSEGRFHVQNLSQVEQDGRTGHGLRRSSKFCLKEHKALKTLGIIMGTFTLCWLPFFIVNIVHVIQDNLIRKEVYILLNWIGYVNSGFNPLIY
resid 121 to 146
![image](https://user-images.githubusercontent.com/127661993/225224878-ec449437-88f3-4de1-9546-41eab52c7630.png)

## ColabFold Output (for bugs)
FileNotFoundError                         Traceback (most recent call last)
[<ipython-input-5-7a4bade36bdb>](https://localhost:8080/#) in label_sequence(seq, model_type, af_model)
    112   try:
--> 113     f = open(f"{jobname}_relaxed_rank_{rank_num}_model_1_scores.json")
    114   except FileNotFoundError as e:

FileNotFoundError: [Errno 2] No such file or directory: 'wazy_9b951_relaxed_rank_1_model_1_scores.json'

During handling of the above exception, another exception occurred:

FileNotFoundError                         Traceback (most recent call last)
1 frames
[<ipython-input-5-7a4bade36bdb>](https://localhost:8080/#) in label_sequence(seq, model_type, af_model)
    113     f = open(f"{jobname}_relaxed_rank_{rank_num}_model_1_scores.json")
    114   except FileNotFoundError as e:
--> 115     f = open(f"{jobname}_unrelaxed_rank_{rank_num}_model_1_scores.json")
    116   data = json.load(f)
    117   avg_plddt = np.mean(data["plddt"][len(protein_sequence):])

FileNotFoundError: [Errno 2] No such file or directory: 'wazy_9b951_unrelaxed_rank_1_model_1_scores.json'

## Context
I have not experienced this bug before. I had another bug in the previous step ("Install Dependencies"). Sergey O gave me some replacement code that solved it. But now this is the first time I've seen this error in the "Set-up AlphaFold" step 

## Your Environment
Running on a free account right now. I've also run in the high RAM Colab Pro while it was working. I was about to buy high RAM environment again but wanted to check everything was working first

**Comment by milot-mirdita** [comment]
Same issue as in https://github.com/sokrypton/ColabFold/issues/411

**Comment by nkiely** [comment]
Hi, I am still not sure how to resolve this error. Is it something you could easily explain?

**Comment by milot-mirdita** [comment]
We can't really do anything about this, as this is not one of our notebook.
Please ask the Wazy authors to fix the issue: https://github.com/ur-whitelab/wazy
It seems like they have an open issue here: https://github.com/ur-whitelab/wazy/issues/28

**Comment by nkiely** [comment]
Ok, thank you

**Comment by ziyueyang37** [comment]
This is due to the name format of colabfold output files changed, so you can replace 
`f = open(f"{jobname}_unrelaxed_rank_{rank_num}_model_1_scores.json"` with 
```
glob_plddt = '*scores_rank_*_alphafold2_multimer_v2_model*.json'
plddt_paths = glob.glob(glob_plddt)[0]
os.system(f'cp {plddt_paths} plddt.json')
f = open("plddt.json")
```
