### ISSUE TITLE
Out of Memory

### ISSUE THREAD

**Issue by cochan424** [sokrypton/ColabFold#42]
Hello!

I was getting an out of memory issue. I get the error in step 5 of "Gather input features, predict structure". I was originally running a sequence of ~480 amino acids for 3 homooligomers. Thinking it was a sequence length issue, I then truncated the sequence to have ~360 amino acids for 1 homooligomer. However, I am still getting this issue. I have "Factory reset runtime" to see if that would help, but still the same error.

**Comment by sokrypton** [comment]
@cochan424 
Can you try again in our advanced beta notebook for the same case:
https://colab.research.google.com/github/sokrypton/ColabFold/blob/main/beta/AlphaFold2_advanced_beta.ipynb

**Comment by cochan424** [comment]
@sokrypton I was trying a different case of a 4:4 heteroligomer in the advanced beta that I ended up hitting a "Cannot connect to GPU backend. You cannot currently connect to a GPU due to usage limits in Colab." error. It's not allowing me to try again as a result.

**Comment by sokrypton** [comment]
Sorry, you'll have to wait a few hours :(

Make sure the other notebook is closed (hit runtime-> manage sessions)
![image](https://user-images.githubusercontent.com/4187522/132816344-c7a21d14-4ba0-48f5-8376-85fbde3326a4.png)
