### ISSUE TITLE
ColabFold multimer prediction with local msa search, more 4 hours msa search for 1 sequence pair at 128~256GB RAM.

### ISSUE THREAD

**Issue by rocke2020** [sokrypton/ColabFold#427]
Thanks very much to contributors for this excellent ColabFold!!
## Expected: Generating MSAs for large scale structure/complex predictions
that's run mmseqs msa locally and fastly for colab fold multimer predictions.
I had carefully read and run "colabfold/batch.py". Now, my target is to use local mmseqs msa server to replace the online one, with similar speed, at least not too slow speed.
## Current Behavior
the local mmseqs msa works very slow, more than 4 hours for 1 seqs pairs for alphafold multimer msa. Too slow, **even slower than Alphafold orig msa on full db at the same local hardware environments.**
And the RAM usage is quite small, about 20GB during local mmseqs msa.
**The only difference is that, I did not use vmtouch to keep the precomputed database index file within system memory, because I only have max 256GB RAM.**
## Steps to Reproduce
1. run setup_databases.sh successfuly to download all the colab database.
the file read file are all ready. 'UNIREF30_READY',     'COLABDB_READY',    'PDB_READY',    'PDB70_READY',    'PDB_MMCIF_READY',
3. run MsaServer/setup-and-start-local.sh to compile mmseqs locally.
now, mmseqs server  successfully runs. at http://127.0.0.1:8888.
4. test codes below, more than 4 hours for only 1 sequence pair, the 2 "use_pairing true/false"mode both run, each need 2 hours.
```python
host_url = 'http://127.0.0.1:8888'
query = '>101\nVNPTVFFDIAVDGEPLGRVSFELFADKVPKTAENFRALSTGEKGFGYKGSCFHRIIPGFMCQGGDFTRHNGTGGKSIYGEKFEDENFILKHTGPGILSMANAGPNTNGSQFFICTAKTEWLDGKHVVFGKVKEGMNIVEAMERFGSRNGKTSKKITIADCGQLE\n>102\nHAGPIA\n'
mode = 'env'
submission_endpoint = 'ticket/msa'
res = requests.post(f'{host_url}/{submission_endpoint}', data={'q':query,'mode': mode}, timeout=6.02)
out = res.json()
print(out)
mode = ''
submission_endpoint = 'ticket/pair'
res = requests.post(f'{host_url}/{submission_endpoint}', data={'q':query,'mode': mode}, timeout=6.02)
out = res.json()
print(out)
```
## Questions
1. in the "colabfold_search.sh" file , there are reminds at first "Do not use this script. Use the python colabfold_search instead".
**why not advice us to this "colabfold_search.sh" scripts? what is "python colabfold_search"?**
2. My target is to use colabfold to predict multimer complex. That's my input is 2 different sequences at separate chains and predict on Alphafold Multimer. **I think my target is "single query searches" mode, yes?**
My computer has max 256GB memory. According to readme, single query searches require the full index (the .idx files) to be kept in memory, at least 768GB RAM. 
**Is there a solution for ColabFold multimer prediction msa search with a good speed(not fastest, but faster) with 128~256GB memeory?** 
## Your Environment
ColabFold 1.5.2
ubuntu 20.04
256GB RAM
32 cores cpu
[log-mmseqs-msa-server.log](https://github.com/sokrypton/ColabFold/files/11145262/log-mmseqs-msa-server.log)

**Comment by rocke2020** [comment]
update in 
https://github.com/soedinglab/MMseqs2/issues/690

**Comment by renzilin** [comment]
Hi there,
How to solve it?
