### ISSUE TITLE
Could not get MSA/templates for MMseqs2 API is giving errors. Please confirm your input is a valid protein sequence.

### ISSUE THREAD

**Issue by RobinGanesan** [sokrypton/ColabFold#428]
## Expected Behavior

I was able to build models yesterday using a protein sequence that is not being recognized today.  I reversed the order of the proteins in my complex and the problem appears to be the same protein sequence that I used successfully yesterday.  This has happened with multiple attempts today over a few hours.

## Current Behavior

Traceback (most recent call last):
  File "/content/colabfold/batch.py", line 1404, in run
    = get_msa_and_templates(jobname, query_sequence, result_dir, msa_mode, use_templates,
  File "/content/colabfold/batch.py", line 862, in get_msa_and_templates
    paired_a3m_lines = run_mmseqs2(
  File "/content/colabfold/colabfold.py", line 226, in run_mmseqs2
    raise Exception(f'MMseqs2 API is giving errors. Please confirm your input is a valid protein sequence. If error persists, please try again an hour later.')
Exception: MMseqs2 API is giving errors. Please confirm your input is a valid protein sequence. If error persists, please try again an hour later.
2023-03-31 13:52:36,543 Done

## Steps to Reproduce (for bugs)

I disconnected and deleted my runtime, closed the browser, and logged out of google, then logged back in, etc.

**Comment by RobinGanesan** [comment]
I tried this again with just my protein of interest (i.e. not in a complex) and it worked ok.  When I added my second protein, it again gives this (XXXXX added by me).  This has happened using two different protein sequences to complex with my protein of interest.

2023-03-31 14:08:25,399 Running on GPU
2023-03-31 14:08:25,402 Found 4 citations for tools or databases
2023-03-31 14:08:25,402 Query 1/1: XXXXXX length 1290)
COMPLETE: 100%|██████████| 300/300 [elapsed: 00:02 remaining: 00:00]
PENDING:   0%|          | 0/300 [elapsed: 00:00 remaining: ?]2023-03-31 14:08:28,897 Sleeping for 5s. Reason: PENDING
RUNNING:   2%|▏         | 5/300 [elapsed: 00:06 remaining: 06:00]2023-03-31 14:08:34,458 Sleeping for 5s. Reason: RUNNING
RUNNING:   3%|▎         | 10/300 [elapsed: 00:11 remaining: 05:35]2023-03-31 14:08:40,026 Sleeping for 8s. Reason: RUNNING
RUNNING:   6%|▌         | 18/300 [elapsed: 00:20 remaining: 05:12]2023-03-31 14:08:48,586 Sleeping for 8s. Reason: RUNNING
RUNNING:   9%|▊         | 26/300 [elapsed: 00:28 remaining: 04:59]2023-03-31 14:08:57,178 Sleeping for 9s. Reason: RUNNING
RUNNING:  12%|█▏        | 35/300 [elapsed: 00:38 remaining: 04:46]2023-03-31 14:09:06,749 Sleeping for 9s. Reason: RUNNING
RUNNING:  15%|█▍        | 44/300 [elapsed: 00:47 remaining: 04:34]2023-03-31 14:09:16,316 Sleeping for 7s. Reason: RUNNING
RUNNING:  17%|█▋        | 51/300 [elapsed: 00:55 remaining: 04:27]2023-03-31 14:09:23,878 Sleeping for 8s. Reason: RUNNING
ERROR:  17%|█▋        | 51/300 [elapsed: 01:04 remaining: 05:13]
2023-03-31 14:09:32,482 Could not get MSA/templates for XXXXX: MMseqs2 API is giving errors. Please confirm your input is a valid protein sequence. If error persists, please try again an hour later.
Traceback (most recent call last):
  File "/content/colabfold/batch.py", line 1404, in run
    = get_msa_and_templates(jobname, query_sequence, result_dir, msa_mode, use_templates,
  File "/content/colabfold/batch.py", line 862, in get_msa_and_templates
    paired_a3m_lines = run_mmseqs2(
  File "/content/colabfold/colabfold.py", line 226, in run_mmseqs2
    raise Exception(f'MMseqs2 API is giving errors. Please confirm your input is a valid protein sequence. If error persists, please try again an hour later.')
Exception: MMseqs2 API is giving errors. Please confirm your input is a valid protein sequence. If error persists, please try again an hour later.
2023-03-31 14:09:32,484 Done

**Comment by RobinGanesan** [comment]
I am also getting the following errors when the dependencies are installed, I don't remember these from yesterday:
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tensorflow 2.12.0 requires keras<2.13,>=2.12.0, but you have keras 2.11.0 which is incompatible.
tensorflow 2.12.0 requires protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.20.3, but you have protobuf 3.19.6 which is incompatible.
tensorflow 2.12.0 requires tensorboard<2.13,>=2.12, but you have tensorboard 2.11.2 which is incompatible.
tensorflow 2.12.0 requires tensorflow-estimator<2.13,>=2.12.0, but you have tensorflow-estimator 2.11.0 which is incompatible.
orbax 0.1.6 requires jax>=0.4.6, but you have jax 0.3.25 which is incompatible.
flax 0.6.8 requires jax>=0.4.2, but you have jax 0.3.25 which is incompatible.
chex 0.1.7 requires jax>=0.4.6, but you have jax 0.3.25 which is incompatible.

**Comment by RobinGanesan** [comment]
This was my input:
MASNEVLVLRGTLEGHNGWVTSLATSAGQPNLLLSASRDKTLISWKLTGDDQKFGVPVRSFKGHSHIVQDCTLTADGAYALSASWDKTLRLWDVATGETYQRFVGHKSDVMSVDIDKKASMIISGSRDKTIKVWTIKGQCLATLLGHNDWVSQVRVVPNEKADDDSVTIISAGNDKMVKAWNLNQFQIEADFIGHNSNINTLTASPDGTLIASAGKDGEIMLWNLAAKKAMYTLSAQDEVFSLAFSPNRYWLAAATATGIKVFSLDPQYLVDDLRPEFAGYSKAAEPHAVSLAWSADGQTLFAGYTDNVIRVWQVMTAN:MVGSGSHTPYDISNSPSDVNVQPATQLNSTLVEDDDVDNQLFEEAQVTETGFRSPSASDNSCAYCGIDSAKCVIKCNSCKKWFCNTKNGTSSSHIVNHLVLSHHNVVSLHPDSDLGDTVLECYNCGRKNVFLLGFVSAKSEAVVVLLCRIPCAQTKNANWDTDQWQPLIEDRQLLSWVAEQPTEEEKLKARLITPSQISKLEAKWRSNKDATINDIDAPEEQEAIPPLLLRYQDAYEYQRSYGPLIKLEADYDKQLKESQALEHISVSWSLALNNRHLASFTLSTFESNELKVAIGDEMILWYSGMQHPDWEGRGYIVRLPNSFQDTFTLELKPSKTPPPTHLTTGFTAEFIWKGTSYDRMQDALKKFAIDKKSISGYLYYKILGHQVVDISFDVPLPKEFSIPNFAQLNSSQSNAVSHVLQRPLSLIQGPPGTGKTVTSATIVYHLSKIHKDRILVCAPSNVAVDHLAAKLRDLGLKVVRLTAKSREDVESSVSNLALHNLVGRGAKGELKNLLKLKDEVGELSASDTKRFVKLVRKTEAEILNKADVVCCTCVGAGDKRLDTKFRTVLIDESTQASEPECLIPIVKGAKQVILVGDHQQLGPVILERKAADAGLKQSLFERLISLGHVPIRLEVQYRMNPYLSEFPSNMFYEGSLQNGVTIEQRTVPNSKFPWPIRGIPMMFWANYGREEISANGTSFLNRIEAMNCERIITKLFRDGVKPEQIGVITPYEGQRAYILQYMQMNGSLDKDLYIKVEVASVDAFQGREKDYIILSCVRANEQQAIGFLRDPRRLNVGLTRAKYGLVILGNPRSLARNTLWNHLLIHFREKGCLVEGTLDNLQLCTVQLVRPQPRKTERPMNAQFNVESEMGDFPKFQDFDAQSMVSFSGQIGDFGNAFVDNTELSSYINNEYWNFENFKSAFSQKQNRNEIDDRNLYQEEASHLNSNFARELQREEQKHELSKDFSNLGI

**Comment by martin-steinegger** [comment]
I tried to run it but could not reproduce the issue. Did you change any parameters?

**Comment by milot-mirdita** [comment]
The API issue should be resolved. Please let us know if there are still issues. I had forgotten to setup some files correctly during a server migration today.

**Comment by RobinGanesan** [comment]
OK it's working now, thank you so much for checking on this!
