### ISSUE TITLE
Notebook loading error

### ISSUE THREAD

**Issue by GloverLab** [sokrypton/ColabFold#44]
Hi -

Trying to load AlphaFold2_complexes.ipynb, I get the message
```
There was an error loading this notebook. Ensure that the file is accessible and try again.
Check dependency list! Synchronous require cannot resolve module 'vs/platform/quickinput/common/quickInput'. This is the first mention of this module!
https://github.com/sokrypton/ColabFold/blob/main/beta/AlphaFold2_advanced.ipynb
```

**Comment by GloverLab** [comment]
Sorry, I should have also said that I'm running it in Safari on a Mac. I've just tried in FireFox and things seem to be working.

**Comment by milot-mirdita** [comment]
Could you please provide more details (eg. in which step the error occurs, input sequence, etc.)? It seems to be working fine in my safari (14.1.2; macos 10.15.7).

**Comment by GloverLab** [comment]
Annoyingly, it's now working fine. My apologies for troubling you.
