### ISSUE TITLE
Since three days: IndexError in AlphaFold2_mmseqs2 notebook

### ISSUE THREAD

**Issue by MWNautilus** [sokrypton/ColabFold#446]
Not sure what has been changed as there is no indication of a change in the ColabFold code on the GitHub website.
Still, since three days I am receiving this error message when running the AlphaFold2_mmseqs2 notebook under default settings:

```
IndexError                                Traceback (most recent call last)

<ipython-input-6-15c5615d08fa> in <cell line: 12>()
     10 show_mainchains = False #@param {type:"boolean"}
     11 
---> 12 tag = results["rank"][0][rank_num - 1]
     13 jobname_prefix = ".custom" if msa_mode == "custom" else ""
     14 pdb_filename = f"{jobname}/{jobname}{jobname_prefix}_unrelaxed_{tag}.pdb"

IndexError: list index out of range
```

In cell 11 there is another messsage hinting to a lack of GPU memory although the sequence is <100 amino acids in length and a check of the ressources showed that 3 of 16 GB of GPU RAM are in use, only:

```
2023-05-13 13:00:00,139 Setting max_seq=75, max_extra_seq=1
2023-05-13 13:09:41,171 Could not predict 1_0a76f. Not Enough GPU memory? INTERNAL: Failed to launch CUDA kernel: concatenate with block dimensions: 1024x1x1 and grid dimensions: 12x1x1: CUDA_ERROR_ILLEGAL_ADDRESS: an illegal memory access was encountered
2023-05-13 13:09:41,252 Done
0
```

The days before, it was just fine.

Michael.

**Comment by MWNautilus** [comment]
I don't know what was changed, but now it works fine again.

Michael.

**Comment by MWNautilus** [comment]
Different protein, same issue again.

Michael.

**Comment by sokrypton** [comment]
Can you post what the error was before?

**Comment by MWNautilus** [comment]
It is exactly the same error message as posted above.

**Comment by sokrypton** [comment]
I mean the error message before this.

**Comment by MWNautilus** [comment]
There is nothing else except those messages which I posted above.
Just tried again, but still erroring out.

**Comment by sokrypton** [comment]
The error you posted usually appears if the above prediction cells failed.
There is an index error because no results were returned.

Are the predicted structures showing up above?

To debug we need to see any messages that may have appeared before. That
cell reporting index error.

**Comment by sokrypton** [comment]
Thanks for the report! Can you try again?
I added a patch (for a different reported issue) should hopefully fix this issue as well.

Also, can you post the sequence you are using?

**Comment by MWNautilus** [comment]
It now all works normally again.
Thanks a lot, Sergey!
