### ISSUE TITLE
ColabFold Relaxation not working due to "No module named 'pdbfixer'"

### ISSUE THREAD

**Issue by ndmaduro** [sokrypton/ColabFold#455]
## Expected Behavior
Relax predicted structure and output file.

## Current Behavior
Relaxation fails and notebook crashes. May be related to simtk.openmm being depreciated (see context section)?

## Steps to Reproduce (for bugs)
Predict multimeric structure for 523 residue homotrimer using custom MSA. Prediction runs fine but fails when trying to minimize. I have reattempted 2 times in the original instance & one additional time in a "factory reset" instance. 

## ColabFold Output (for bugs)
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
[<ipython-input-12-73ef1446aa8d>](https://localhost:8080/#) in <cell line: 66>()
     64 
     65 download_alphafold_params(model_type, Path("."))
---> 66 results = run(
     67     queries=queries,
     68     result_dir=result_dir,

5 frames
[/content/alphafold/relax/cleanup.py](https://localhost:8080/#) in <module>
     20 import io
     21 
---> 22 import pdbfixer
     23 from openmm import app
     24 from openmm.app import element

ModuleNotFoundError: No module named 'pdbfixer'

---------------------------------------------------------------------------
NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.

To view examples of installing some common dependencies, click the
"Open Examples" button below.
---------------------------------------------------------------------------

## Context
Previous failures were giving output of "WARNING:root:Warning: importing 'simtk.openmm' is deprecated.  Import 'openmm' instead.". These failures appear to be due to crashing from insufficient memory (despite being logged into a Pro+ account, apparently it wasn't using my session settings from previously)

## Your Environment
Colabfold V. 1.5.2

Image below is from relax_amber.ipynb: 

<img width="1307" alt="Screenshot 2023-05-24 at 2 35 44 PM" src="https://github.com/sokrypton/ColabFold/assets/32580389/721fae43-0ac8-4541-bc21-b6e6417e69d2">

ColabFold output is below: 

<img width="770" alt="Screenshot 2023-05-24 at 2 27 50 PM" src="https://github.com/sokrypton/ColabFold/assets/32580389/a24db7b8-2e1c-4b77-bb65-2b7c71791e78">

**Comment by ndmaduro** [comment]
<img width="770" alt="Screenshot 2023-05-24 at 2 27 50 PM" src="https://github.com/sokrypton/ColabFold/assets/32580389/177a2e44-1fe7-4fbd-a68e-e6eaf8c5968a">

**Comment by ndmaduro** [comment]
Update: Relaxation works just fine on relax_amber.ipynb. Issue is not related to "simtk.openmm".

**Comment by sokrypton** [comment]
Thanks! The issue should now be fixed.
