### ISSUE TITLE
Suggest to improve code for custom_template_path

### ISSUE THREAD

**Issue by data2code** [sokrypton/ColabFold#468]
## Reasoning

When custom_template_path is provided, there is no need to search PDB for templates, as the returned template_paths will be overwritten by the supplied custom_template_path anyway. This change not long avoids waste, but avoids the error message when we use run colabfold without mmseq2 API server (it tries to connect to API server but fails). Thanks for your consideration.

## Expected Behavior
Propose change to:

```
        if custom_template_path is not None:
            a3m_lines_mmseqs2 = run_mmseqs2(
                query_seqs_unique,
                str(result_dir.joinpath(jobname)),
                use_env,
                use_templates=False,
                host_url=host_url,
            )
        else:
            a3m_lines_mmseqs2, template_paths = run_mmseqs2(
                query_seqs_unique,
                str(result_dir.joinpath(jobname)),
                use_env,
                use_templates=True,
                host_url=host_url,
            )
```

## Current Behavior
In batch.py, line 752-758:

``` 
      a3m_lines_mmseqs2, template_paths = run_mmseqs2(
            query_seqs_unique,
            str(result_dir.joinpath(jobname)),
            use_env,
            use_templates=True,
            host_url=host_url,
        )
```

**Comment by YoshitakaMo** [comment]
Thank you for your suggestion. I merged your idea in the commit https://github.com/sokrypton/ColabFold/commit/34921debbc05f4722af8c9b5a544582d12f84e8c . Now the template search process will be skipped when the custom_template_path is provided.
