### ISSUE TITLE
Possible bug in pdb to cif generation for custom template

### ISSUE THREAD

**Issue by data2code** [sokrypton/ColabFold#469]
I encounter an issue with custom template.

I use the default options to predict an antibody-antigen complex (3 chains in total) with the following input seq:
ELTQSPATLSLSPGERATLSCRASQSVGRNLGWYQQKPGQAPRLLIYDASNRATGIPARFSGSGSGTDFTLTISSLEPEDFAVYYCQARLLLPQTFGQGTKVEIKRTV:EVQLLESGPGLLKPSETLSLTCTVSGGSMINYYWSWIRQPPGERPQWLGHIIYGGTTKYNPSLESRITISRDISKNQFSLRLNSVTAADTAIYYCARVAIGVSGFLNYYYYMDVWGSGTAVTVSS:WNWFDITNK

I use the custom PDB as attached 3fn0.pdb
[3fn0.zip](https://github.com/sokrypton/ColabFold/files/11891220/3fn0.zip)

The prediction output shows the following error message (these are not warnings but errors, as explained next):

2023-06-28 06:37:51,309 Sequence 0 found no templates
2023-06-28 06:37:52,599 Sequence 1 found no templates
2023-06-28 06:37:53,010 Sequence 2 found no templates

I did some tracing with an offline version of ColabFold, indeed, AlphaFold does not like the converted 3fn0.cif (this cif can also be found in the attachment).

To reproduce AlphaFold's error, please see
https://github.com/deepmind/alphafold/issues/788
You can find example code that reads 3fn0.cif and triggers an error in AlphaFold, which leads AF to not use any template.

I initially reported this as an AlphaFold issue, but later I found out that the .cif templates extracted by the non-custom-template method works, so AF's code is bug-free. My current believe is there is something in the ColabFold-generated 4fn0.cif that breaks DeepMind's code.

Really appreciate if you can help take a look at it. With this bug, the template I provided cannot be used by the prediction.

**Comment by jkosinski** [comment]
It's probably the same issue I reported here: https://github.com/sokrypton/ColabFold/issues/449. @milot-mirdita - this file makes a nice example for testing.

**Comment by data2code** [comment]
Thank you @jkosinski, they are the same issue. However, .pdf to .cif conversion is done by colabfold.util  CFMMCIFIO, so we will need to add the patched version of _save_structure into colabfold.util.CFMMCIFIO class.

It is hard to say who owns the bug, BioPython, ColabFold, or AlphaFold. I did post the issue to BioPython (https://github.com/biopython/biopython/issues/4342) and AlphaFold (https://github.com/deepmind/alphafold/issues/788). Strictly speaking, none of the three has a bug, but the logic of chain renaming crashes the custom template workflow.

For the benefit of the ColabFold users, it might be best to patch ColabFold, instead of waiting for BioPython or DeepMind. If we overwrite _save_structure in CFMMCIFIO, I can confirm it works.

See the right output below:
```
2023-06-28 10:51:17,776 Sequence 0 found templates: ['3fn0_L', '3fn0_H', '3fn0_L', '3fn0_H']
2023-06-28 10:51:18,774 Sequence 1 found templates: ['3fn0_H', '3fn0_L', '3fn0_L']
2023-06-28 10:51:19,171 Sequence 2 found templates: ['3fn0_P']
```
Thanks a lot!
