### ISSUE TITLE
Chain break is not used for `alphafold_ptm`

### ISSUE THREAD

**Issue by alirezaomidi** [sokrypton/ColabFold#473]
As you know, we can model multi-chain structure prediciton using Alphafold monomer, we can add a large number to the residue indices to denote chain breaks. Though the following function exists in the source code, it's not used anywhere in the `batch.py` file. Am I missing something or ColabFold does not actually do chain-breaking for the `ptm` model?

https://github.com/sokrypton/ColabFold/blob/c7367a3bb7b43b819562c8d9437a3b35431e1ff5/colabfold/colabfold.py#L317

**Comment by sokrypton** [comment]
There is no longer need to set the chain break. We modified the pTM model
to use asym_id defintion to modify the offset between chains directly.

See here:
https://github.com/sokrypton/alphafold/blob/024dcb275b1863115f4346abe52f30508ecb5ccc/alphafold/model/modules.py#L1934

This accomplishes the same. You either offset the residue index by large
number, which triggers clipping at min/max of -32/32 in the residue index
difference matrix (aka offset) or you just set the values to -32/32 when
the chain definition differs.

-Sergey

**Comment by alirezaomidi** [comment]
Cool. Thanks.
