### ISSUE TITLE
Cannot upload custom template

### ISSUE THREAD

**Issue by timlevine** [sokrypton/ColabFold#475]
## Expected Behavior
when template_mode: set to Custom, expect after some wait for an upload box to appear at the end of the "Input Protein" box.  

## Current Behavior
no box appears. Have tried this in 2 different browsers: Firefox and Opera. No upload box that I can see anywhere on the page.

## Steps to Reproduce (for bugs)
It's as simple as no new box appearing!

## ColabFold Output (for bugs)
Please make sure to also post the complete ColabFold output. You can use gist.github.com for large output.

## Context
First attempt at Colabfold for months

**Comment by milot-mirdita** [comment]
The input should appear directly under the cell, after you execute the cell (or click run all):
<img width="434" alt="Screen Shot 2023-07-12 at 0 19 46" src="https://github.com/sokrypton/ColabFold/assets/63657/38722727-8a9a-4da5-8d95-8bef4fecbcea">

**Comment by timlevine** [comment]
Thank you. That works - but is not what I understood from the instructions. Clearly I read them with a very literal mind-set

**Comment by milot-mirdita** [comment]
The input just appearing after you hit run is not the most intuitive thing. We would also prefer a better user experience, but are somewhat limited by what the Colab environment offers.
