### ISSUE TITLE
Inferring PLDDT using ESMFold

### ISSUE THREAD

**Issue by sid-betalol** [sokrypton/ColabFold#479]
I am running the [ESMFold notebook](https://colab.research.google.com/github/sokrypton/ColabFold/blob/main/ESMFold.ipynb#scrollTo=CcyNpAvhTX6q)

I am trying to understand:

1. Why, when I run the model for a sequence of length 546, why do I get a plddt array of shape (1, 546, 37)? I know that the first dimension refers to the number of sequences, and the second dimension refers to the sequence length, but what does the third dimension refer to?
2. I also want to understand why plddt is being calculated this way:
`plddt = output["plddt"][0,...,1].mean()`
Why are we trying to access the second element along the third dimension? 

I'd appreciate a quick clarification about these questions.

**Comment by sokrypton** [comment]
Unlike alphafold, ESMfold actually makes a error estimate for all atoms
(not just CA). To be consistent with AlphaFold's pLDDT. I also use just the
CA error estimate.

The 37 dimensions are the 37 possible atoms for any given residue. I
believe the order is N,CA,...., (Hence why we select index 1).

**Comment by sid-betalol** [comment]
Great! This is helpful. Thanks a lot!
