### ISSUE TITLE
Any status update on ColabFold MSA server issue?

### ISSUE THREAD

**Issue by MWNautilus** [sokrypton/ColabFold#480]
Is this still a problem, are we still working with old databases?

`2023/07/27: ColabFold MSA server issue: We are using the backup server with old databases (UniRef30 2202/PDB70 220313) starting from ~8:30 AM CEST until we resolve the issue.`

Michael.

**Comment by milot-mirdita** [comment]
Yes, I am afraid this will remain unresolved until Monday. We couldn’t contact the admins responsible for the networking issue.

**Comment by MWNautilus** [comment]
No problem and thanks for the feedback.
