### ISSUE TITLE
Is there a way to use only one version of ptm model instead of five?

### ISSUE THREAD

**Issue by yunxiaoliCB** [sokrypton/ColabFold#485]
I was running ColabFold with [localcolabfold](https://github.com/YoshitakaMo/localcolabfold). I know that by specifying `--model_type alphafold2_ptm`, it uses all 5 versions of alphafold2_ptm models. Is there a way to only use one version of them? The motivation is to speed up predictions on large batches of proteins.

**Comment by milot-mirdita** [comment]
You can use the `--num-models` in combination with the `--model-order` parameter to select which models you want to run.

**Comment by yunxiaoliCB** [comment]
Thank you for the solution! By using `--num-models 1` and `--model-order 4` I can indeed use only the AF_ptm_4_model.
