### ISSUE TITLE
MSA query stuck at "PENDING 0%" for a particular sequence.

### ISSUE THREAD

**Issue by jnrsloth** [sokrypton/ColabFold#49]
Not sure if I'm doing something incorrectly.
A particular sequence doing a batch run using the alphafold2_batch or a single run with the AlphaFold2_mmseqs2 notebook seems to cause the MMSeq2 query step to hang. 
My current run has been stuck at 0% on the MSA (MMSeq2 (Uniref+environmental)) step for the past 1h 43 minutes and it's been stuck for longer in the past before I kill the process.
The raw sequence is; MAQVQLVESGGGLVQAGGSLRLSCAVSGRPFSEYNLGWFRQAPGKEREFVARIRSSGTTVYTDSVKGRFSASRDNFLATT
LERIEKNFVITDPRLPDNPIIFASDSFLQLTEYSREEILGRNCRFLQGPETDRATVRKIRDAIDNQTEVTVQLINYTKSG
KKFWNLFHLQPMRDQKGDVQYFIGVQLDGTEHVRDAAEREGVMLIKKTAENIDEAAKELAKNMGYLQLNSLEPEDTAVYY
CAMSRVDTDSPAFYDYWGQGTQVTVSTPRS

Other variations on this sequence have worked flawlessly with these settings, so I'm not sure what is wrong with this sequence.
Running the notebook off a colab instance, not locally.

[LaM-8_NA73-O.txt](https://github.com/sokrypton/ColabFold/files/7208423/LaM-8_NA73-O.txt) 
file extension changed from fasta to txt so that github would allow the upload

**Comment by milot-mirdita** [comment]
That sequence was already processed before the last server update and is in now in an invalid state after the last restart.

Could you append a single amino acid to break the cache? I cant restart the server right now.

**Comment by jnrsloth** [comment]
That fixed it, perfect!
