### ISSUE TITLE
Question:  --num-ensemble flag seems not working.

### ISSUE THREAD

**Issue by hjy-1001** [sokrypton/ColabFold#494]
## Expected Behavior
I want to sample multiple conformation of protein according to Diego del Alamo et al using --num-ensemble flag. I think it will return multiple result each model (i.e. if --num-ensemble is 10, it returns 5*10 structures in total).
## Current Behavior
No  matter how many number of ensemble you specify, Localcolabfold always return 5 structures predicted by the model.
## Steps to Reproduce (for bugs)
The command is listed below
colabfold_batch --num-recycle 1 --save-all --num-ensemble 10 --num-ensemble 10 --model-type alphafold2 --max-seq $max_seq --max-extra-seq $max_extra_msa  $input_fasta $result_dir
where $max_extra_seq range from 16 to 5120, and $max-seq is half of the $max_extra_seq. 

## ColabFold Output (for bugs)
it outputs 5 structures just like no --num-ensemble 10 is specified.

## Context
My purpose is to subsample the MSA to get multiple conformation by localcolabfold, by controlling the max_seq and max_extra_seq
No error occured during prediction.

## Your Environment
Ubuntu 20.04
Newest version of localcolabfold (v1.5.2)
GPU: Nvidia A100

**Comment by sokrypton** [comment]
What you want is --num-seeds. 
See more details in:
https://github.com/sokrypton/ColabFold/wiki/v1.5.0#sampling

--num-ensembles is a different concept. It tells the model how many random msa subsamplings to average within the evoformer before making a predictions.
