### ISSUE TITLE
Timeout while submitting to MSA server. Retrying...

### ISSUE THREAD

**Issue by shhashem** [sokrypton/ColabFold#495]
## Expected Behavior
MSA server returning alignments
## Current Behavior
Timeout while submitting to MSA server. Retrying...
## Steps to Reproduce (for bugs)
colabfold_batch complex.csv COMPLEX --num-seeds 20 --num-recycle 2 --msa-mode mmseqs2_uniref_env --model-type alphafold2_multimer_v3 --rank multimer --pair-mode unpaired_paired --num-models 5 --use-dropout --save-recycles --amber --use-gpu-relax

## ColabFold Output (for bugs)
2023-08-03 10:06:45,582 Running on GPU
2023-08-03 10:06:47,101 Found 5 citations for tools or databases
2023-08-03 10:06:47,102 Query 1/1: Complex (length 520)
2023-08-03 10:06:53,163 Timeout while submitting to MSA server. Retrying...
2023-08-03 10:06:59,205 Timeout while submitting to MSA server. Retrying...

## Context
I am experiencing a problem with the generation of MSA. When running ColabFold, I get "Timeout while submitting to MSA server. Retrying..." in the logfile.
Could you please assist in that?
Thanks
## Your Environment
Newest local ColabFold version: 1.5.2

**Comment by milot-mirdita** [comment]
I don't see any issues currently. Could you send me the IP from which you are submitting request? If you don't want to share your IP publicly, you can email me at milot at mirdita dot de.

**Comment by jiejiangtao** [comment]
> I have run a job and it works now.
> 
> Thanks!
Hello, I also met this problem, how did you solve it.

**Comment by milot-mirdita** [comment]
Please open a new GitHub issue with as much detail as possible (the full error message, etc.)

**Comment by yanskysky** [comment]
> I have run a job and it works now.
> 
> Thanks!

Hi, now is 20th March, 2025, I have met the same error as yours. May you share how did you solve this?

**Comment by milot-mirdita** [comment]
I don't see any issues currently. If its not working for you, please open a new issue. Also your IP would be useful to diagnose issues.
