### ISSUE TITLE
[Request] Update README to use the same version of MMseqs2 as the MSA server.

### ISSUE THREAD

**Issue by hikarino-my** [sokrypton/ColabFold#501]
## Context
I've heard that the MSA server uses MMseqs2 with commit ID [71dd32e](https://github.com/soedinglab/MMseqs2/commit/71dd32e).
When I tried to run mmseqs2 locally using the latest MMseqs2 source code (commit ID [bb0a1b3](https://github.com/soedinglab/MMseqs2/commit/bb0a1b3569b9fe115f3bf63e5ba1da234748de23)), the resulting MSAs were different from the MSA server results.
I think there is a breaking change at MMseqs2 between commit ID [71dd32e](https://github.com/soedinglab/MMseqs2/commit/71dd32e) and [bb0a1b3](https://github.com/soedinglab/MMseqs2/commit/bb0a1b3569b9fe115f3bf63e5ba1da234748de23) in the way indexes are created and searched against.
As the README says "you need to compile the latest version", which doesn't actually work as the same way as the MSA server does, it should be updated.
https://github.com/sokrypton/ColabFold/blob/29cbf90390086c336afbe7c420eef9a3cf00451c/README.md?plain=1#L86

**Comment by hikarino-my** [comment]
Thanks to the @\YoshitakaMo 's work(https://github.com/sokrypton/ColabFold/commit/29cbf90390086c336afbe7c420eef9a3cf00451c, https://github.com/sokrypton/ColabFold/commit/5c75825a2d2d44ef75e7a150070b4b9b4bb3dac5), using MMseqs2 commit ID [71dd32e](https://github.com/soedinglab/MMseqs2/commit/71dd32e) when creating indexes and searching, it produces same results as the MSA server does.

**Comment by hikarino-my** [comment]
Related. https://github.com/sokrypton/ColabFold/issues/489

**Comment by YoshitakaMo** [comment]
Thank you for your suggestion. I've added the description about the mmseqs version info in README. https://github.com/sokrypton/ColabFold/commit/03965ba8af19ec714511abcc71fbf68ed640060a
