### ISSUE TITLE
pdb70 or pdb100 ?

### ISSUE THREAD

**Issue by EricDeveaud** [sokrypton/ColabFold#502]
Hello, 

while taking a look at the notebooks eg: [AlphaFold2](https://colab.research.google.com/github/sokrypton/ColabFold/blob/main/AlphaFold2.ipynb) notebook I noticed the following note

`2023/06/12: We now use PDB100 instead of PDB70 (see [notes]).`

and while testing local installation of ColabFold I noticed that [setup_databases.sh](https://github.com/sokrypton/ColabFold/blob/main/setup_databases.sh) still retrieve and index pdb70

I'm a little bit confused 

regards

Eric

**Comment by YoshitakaMo** [comment]
There is an instruction about PDB100 in the notebook:

> PDB100
> As of 23/06/08, we have transitioned from using the PDB70 to a 100% clustered PDB, the PDB100. The construction methodology of PDB100 differs from that of PDB70.
> The PDB70 was constructed by running each PDB70 representative sequence through [HHblits](https://github.com/soedinglab/hh-suite) against the [Uniclust30](https://colab.research.google.com/corgiredirector?site=https%3A%2F%2Funiclust.mmseqs.com%2F). On the other hand, the PDB100 is built by searching each PDB100 representative structure with [Foldseek](https://github.com/steineggerlab/foldseek) against the [AlphaFold Database](https://colab.research.google.com/corgiredirector?site=https%3A%2F%2Falphafold.ebi.ac.uk).
> To maintain compatibility with older Notebook versions and local installations, the generated files and API responses will continue to be named "PDB70", even though we're now using the PDB100.

Thus, PDB100 is now used.

I am also building and testing local installation of sequence and PDB100 databases ([pdb100_foldseek_230517.tar.gz](https://wwwuser.gwdg.de/~compbiol/data/hhsuite/databases/hhsuite_dbs/pdb100_foldseek_230517.tar.gz) and [pdb100_230517.fasta.gz](https://wwwuser.gwdg.de/~compbiol/colabfold/pdb100_230517.fasta.gz)) now. In the environment I tested, the local PDB100's hit matched the web server's one, although I am noticing that the order and values were a bit different. Thus, we'll update the setup_databases.sh script immediately.

It is notable that @hikarino-my found that the version of MMseqs should be https://github.com/soedinglab/MMseqs2/commit/71dd32e to reproduce the webserver's MSA (See also https://github.com/sokrypton/ColabFold/issues/501).

**Comment by EricDeveaud** [comment]
thanks for the fast answer. 
I must admit that I did'nt see the compatibility note.

**Comment by EricDeveaud** [comment]
Hello
seems there's a typo in `setup_databases.sh` pdb100_foldseek_230517 url is incorrect 

https://wwwuser.gwdg.de/~compbiol/colabfold/pdb100_foldseek_230517.tar.gz should be 
https://wwwuser.gwdg.de/~compbiol/data/hhsuite/databases/hhsuite_dbs/pdb100_foldseek_230517.tar.gz instead

regards

Eric

**Comment by YoshitakaMo** [comment]
Thank you, @EricDeveaud !
I have now corrected it!
