### ISSUE TITLE
ESMFold Notebook fails to install OpenFold

### ISSUE THREAD

**Issue by coliva92** [sokrypton/ColabFold#509]
## Expected Behavior

OpenFold, one of the dependencies required to run ESMFold in the ESMFold Notebook, should be installed in the first cell of the Notebook.

## Current Behavior

The Python Wheel for OpenFold fails to install due to an unknown error. 

## Steps to Reproduce (for bugs)

Bellow the cell named "install", create a new cell and insert the following code:
```
%shell pip install git+https://github.com/aqlaboratory/openfold.git@6908936b68ae89f67755240e2f588c09ec31d4c8
```

You should notice this is functionally identical to line 20 in the "install" cell, which should install OpenFold. Simply run this cell.

Alternatively, try to run the Notebook with the default settings (using the Runtime > Run all option).

## ColabFold Output (for bugs)

If you ran the inserted code mentioned above, the following error message should be produced:
```
Preparing metadata (setup.py) ... done
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Building wheel for openfold (setup.py) ... error
  ERROR: Failed building wheel for openfold
ERROR: Could not build wheels for openfold, which is required to install pyproject.toml-based projects
---------------------------------------------------------------------------
CalledProcessError                        Traceback (most recent call last)
[<ipython-input-4-3e11cfb9a03e>](https://localhost:8080/#) in <cell line: 1>()
----> 1 get_ipython().run_line_magic('shell', 'pip install -q git+https://github.com/aqlaboratory/openfold.git@6908936b68ae89f67755240e2f588c09ec31d4c8')

2 frames
[/usr/local/lib/python3.10/dist-packages/google/colab/_system_commands.py](https://localhost:8080/#) in check_returncode(self)
    135   def check_returncode(self):
    136     if self.returncode:
--> 137       raise subprocess.CalledProcessError(
    138           returncode=self.returncode, cmd=self.args, output=self.output
    139       )

CalledProcessError: Command 'pip install -q git+https://github.com/aqlaboratory/openfold.git@6908936b68ae89f67755240e2f588c09ec31d4c8' returned non-zero exit status 1.
```

Otherwise, if you try to run the Notebook normally, the following error message will be produced at the cell named "run ESMFold".

```
length 68
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<timed exec> in <module>

[/usr/local/lib/python3.10/dist-packages/torch/serialization.py](https://localhost:8080/#) in load(f, map_location, pickle_module, weights_only, mmap, **pickle_load_args)
   1012                     except RuntimeError as e:
   1013                         raise pickle.UnpicklingError(UNSAFE_MESSAGE + str(e)) from None
-> 1014                 return _load(opened_zipfile,
   1015                              map_location,
   1016                              pickle_module,

2 frames
[/usr/local/lib/python3.10/dist-packages/esm/esmfold/v1/esmfold.py](https://localhost:8080/#) in <module>
      9 import torch.nn as nn
     10 from omegaconf import MISSING
---> 11 from openfold.data.data_transforms import make_atom14_masks
     12 from openfold.np import residue_constants
     13 from openfold.utils.loss import compute_predicted_aligned_error, compute_tm

ModuleNotFoundError: No module named 'openfold'
```

## Context
Trying to run the linked ESMFold Notebook with default settings.

## Your Environment
Using commit 5637e4e at the main branch.

**Comment by coliva92** [comment]
I tried changing the commit from which OpenFold is being installed from `6908936b68ae89f67755240e2f588c09ec31d4c8` (the one used in the faulty ESMFold Notebook) to `4b41059694619831a7db195b7e0988fc4ff3a307` (the one stated in the [README](https://github.com/facebookresearch/esm#repostart) file in the official ESMFold GitHub repository). However, PIP still fails to install OpenFold.

**Comment by milot-mirdita** [comment]
Thank you, the ESMFold notebook should work again (13b7a23ff76e06ce76d08f78ef544a113c003126).

**Comment by coliva92** [comment]
Sorry for the late response. I've confirmed the Notebook is already working properly. Thank you for the swift fix.
