### ISSUE TITLE
MMSeqs version

### ISSUE THREAD

**Issue by wangy9711** [sokrypton/ColabFold#51]
Hello,
I would like to build a pipeline to search MSAs using local MMSeqs. However, There are some problems when I fllow the script 'msa.sh' returned from online MMSeqs service. For examle, when I run the command 

`"${MMSEQS}" expandaln "${BASE}/qdb" "${DBBASE}/${DB1}.idx" "${BASE}/res" "${DBBASE}/${DB1}.idx" "${BASE}/res_exp" --db-load-mode 2 ${EXPAND_PARAM}`

Then the following error will return :

```
Input database "/nfs/database/uniref30_mmseqs/uniref30.idx" has the wrong type (Generic)
Allowed input:
- Alignment
- Prefilter
- Bi-directional prefilter
- Clustering

```

I just want to figure out whether the MMSeqs used in  service is consistent with the latest one from [github](https://github.com/soedinglab/MMseqs2).
If not, how can we get the version  applied to the service?

**Comment by milot-mirdita** [comment]
The other issue (https://github.com/sokrypton/ColabFold/issues/20#issuecomment-928098245) now contains some instructions how to get ColabFold running locally. We are still in the process of making everything actually easy to run.
