### ISSUE TITLE
colabfold database not finding mmseqs

### ISSUE THREAD

**Issue by JustABiologist** [sokrypton/ColabFold#516]
## Expected Behavior
Downloading mmseq database and setting it up
## Current Behavior
Download working, mmseq not found error in line 55 

## Steps to Reproduce (for bugs)
~/Desktop/colabfold/ColabFold$ sudo MMSEQS_NO_INDEX=1 ./setup_databases.sh /mnt/data2TB/colab_database/ --mmseqs ~/mmseqs/bin/mmseqs 

## ColabFold Output (for bugs)
+ ARIA_NUM_CONN=8
+ WORKDIR=/mnt/data2TB/colab_database/
+ PDB_SERVER=--mmseqs
+ PDB_PORT=/home/gravi/mmseqs/bin/mmseqs
+ UNIREF30DB=uniref30_2302
+ MMSEQS_NO_INDEX=1
+ cd /mnt/data2TB/colab_database/
+ STRATEGY=
+ hasCommand aria2c
+ command -v aria2c
+ hasCommand curl
+ command -v curl
+ STRATEGY=' CURL'
+ hasCommand wget
+ command -v wget
+ STRATEGY=' CURL WGET'
+ '[' ' CURL WGET' = '' ']'
+ export MMSEQS_FORCE_MERGE=1
+ MMSEQS_FORCE_MERGE=1
+ '[' '!' -f UNIREF30_READY ']'
+ downloadFile https://wwwuser.gwdg.de/~compbiol/colabfold/uniref30_2302.tar.gz uniref30_2302.tar.gz
+ URL=https://wwwuser.gwdg.de/~compbiol/colabfold/uniref30_2302.tar.gz
+ OUTPUT=uniref30_2302.tar.gz
+ set +e
+ for i in $STRATEGY
+ case "$i" in
+ curl -L -o uniref30_2302.tar.gz https://wwwuser.gwdg.de/~compbiol/colabfold/uniref30_2302.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 95.8G  100 95.8G    0     0  21.9M      0  1:14:38  1:14:38 --:--:-- 54.9M
+ set -e
+ return 0
+ tar xzvf uniref30_2302.tar.gz
uniref30_2302.md5sum
uniref30_2302.tsv
uniref30_2302_h.tsv
uniref30_2302_aln.tsv
uniref30_2302_seq.tsv
uniref30_2302_db_mapping
uniref30_2302_db_taxonomy
+ mmseqs tsv2exprofiledb uniref30_2302 uniref30_2302_db
./setup_databases.sh: line 55: mmseqs: command not found

## Context
Maybe it is because the database is on a mounted disk but idk at this point... It was working fine in earlier runs, but due to once running out disk space we had to rerun with the database on another disk

## Your Environment
Include as many relevant details about the environment you experienced the bug in.
Linux zbpc1 6.2.0-34-generic #34~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Thu Sep  7 13:12:03 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

**Comment by milot-mirdita** [comment]
Setup databases doesn’t take a path to mmseqs. The database needs to be in PATH.

**Comment by JustABiologist** [comment]
@milot-mirdita so I just add  /mnt/data2TB/colab_database/  to PATH and I should be fine ?

**Comment by milot-mirdita** [comment]
You have to install [MMseqs2](https://github.com/soedinglab/mmseqs2). The localcolabfold installer also installs MMseqs2 for you within its Conda environment.

**Comment by JustABiologist** [comment]
I have mmseqs2 installed... and also added it to PATH already, do I have to do something special when using it for downloading the database to a different disk? Because when I tried setup_database.sh on the root disk it worked, just ran out of space by a few GB later on but it could use the mmseq commands just fine.

**Comment by milot-mirdita** [comment]
Could you please post the command line call and full output of the command here?

The intial command should not have `--mmseqs ~/mmseqs/bin/mmseqs` added as parameters, these will override the default PDB download location:
```
MMSEQS_NO_INDEX=1 ./setup_databases.sh /mnt/data2TB/colab_database/
```

I would also not recommend to call the script with sudo.

**Comment by JustABiologist** [comment]
Okay I guess sudo was the dealbreaker here. It worked fine now, thank you for helping out!

**Comment by milot-mirdita** [comment]
That makes sense, sudo doesn't use/export the PATH env variable you set.
