### ISSUE TITLE
Setup Databases for Multimer A3M file production via colabfold_search

### ISSUE THREAD

**Issue by NickWoodall** [sokrypton/ColabFold#518]
## Expected Behavior
The downloaded databases from setup_databases.sh will work for multimer a3m file production (default:"uniref30_2302") from colabfold_search. 

## Current Behavior

Monomer a3m file production works from colabfold_search after using code from setup_databases.sh

I could only get multimer a3m files to be produced when using the uniref30_2103 database with the provided taxonomy and mapping db files [https://wwwuser.gwdg.de/~compbiol/colabfold/uniref30_2103_taxonomy.tar.gz] which is not automatically downloaded with setup_databases.sh.

**Comment by milot-mirdita** [comment]
Do you have any error message or log outputs? Does the uniref30 archive you downloaded match the hash on colabfold.mmseqs.com?

**Comment by NickWoodall** [comment]
Sorry that wasn't very descriptive. 

The programs runs for most of its runtime ~1.5 hrs and then errors with a message that the files db_mapping and db_taxonomy are missing. The same files that are produced from [https://wwwuser.gwdg.de/~compbiol/colabfold/uniref30_2103_taxonomy.tar.gz] except they are mismatched with the default uniref version.

No error is produced when given fasta that contain monomers. 

I didn't run mmseqs with create_index since we didn't have room for the index files. 

I will reproduce the error, gather the logs and match the checksum tomorrow. Thanks for you help.

**Comment by milot-mirdita** [comment]
Can you please show a list of files in your database directory. The files should be in the archive.

**Comment by NickWoodall** [comment]
Sorry. The files are in the archive. I accidentally deleted the _db_mapping and _db_taxonomy while cleaning files when the index files overwhelmed the hard drive during my initial run with create index function assuming they were made with the create database function. Then I unfortunately got distracted find a solution from the previous version. Thank you for you help.
