### ISSUE TITLE
Is there a way to specify which GPU to use?

### ISSUE THREAD

**Issue by rainfieldcn** [sokrypton/ColabFold#521]
## Expected Behavior
I am using a workstation with four GPUs. But colabfold local can only use GPU0. Is there a way to specify which GPU to use?

## Steps to Reproduce (for bugs)
Please make sure to reproduce the issue after a "Factory Reset" in Colab. 
If running locally ypdate you local installation `colabfold_batch` to the newest version.
Please provide your input if you can share it. 

## ColabFold Output (for bugs)
Please make sure to also post the complete ColabFold output. You can use gist.github.com for large output.

## Context
Providing context helps us come up with a solution and improve our documentation for the future.

## Your Environment
Include as many relevant details about the environment you experienced the bug in.
* Git commit used
* If you run it on a local system. Please add the server specifications
* Operating system and version:

**Comment by martin-steinegger** [comment]
You can do this by using the `CUDA_VISIBLE_DEVICES` variable. 
Like this:  
```
CUDA_VISIBLE_DEVICES=1 colabfold_batch ...
```
