### ISSUE TITLE
ColabFold: AlphaFold2 w/ MMseqs2 BATCH Fails to Install Dependencies

### ISSUE THREAD

**Issue by Jzurn-ksu** [sokrypton/ColabFold#527]
## Current Behavior

Install dependencies runs for approximately 50s and produces the following error message:

ERROR: Cannot install jax[cuda11-cudnn805]==0.3.10, jax[cuda11-cudnn805]==0.3.11, jax[cuda11-cudnn805]==0.3.12, jax[cuda11-cudnn805]==0.3.13, jax[cuda11-cudnn805]==0.3.14, jax[cuda11-cudnn805]==0.3.15, jax[cuda11-cudnn805]==0.3.16, jax[cuda11-cudnn805]==0.3.17, jax[cuda11-cudnn805]==0.3.18, jax[cuda11-cudnn805]==0.3.19, jax[cuda11-cudnn805]==0.3.20, jax[cuda11-cudnn805]==0.3.21, jax[cuda11-cudnn805]==0.3.22, jax[cuda11-cudnn805]==0.3.23, jax[cuda11-cudnn805]==0.3.24, jax[cuda11-cudnn805]==0.3.25, jax[cuda11-cudnn805]==0.3.8 and jax[cuda11-cudnn805]==0.3.9 because these package versions have conflicting dependencies.
ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
---------------------------------------------------------------------------
CalledProcessError                        Traceback (most recent call last)
[<ipython-input-5-805c30dfd06f>](https://localhost:8080/#) in <cell line: 1>()
----> 1 get_ipython().run_cell_magic('bash', '-s $use_amber $use_templates', '\nset -e\n\nUSE_AMBER=$1\nUSE_TEMPLATES=$2\n\n\nif [ ! -f COLABFOLD_READY ]; then\n  # install dependencies\n  # We have to use "--no-warn-conflicts" because colab already has a lot preinstalled with requirements different to ours\n  pip install -q --no-warn-conflicts "colabfold[alphafold-minus-jax] @ git+https://github.com/sokrypton/ColabFold"\n  # high risk high gain\n  pip install -q "jax[cuda11_cudnn805]>=0.3.8,<0.4" -f [https://storage.googleapis.com/jax-releases/jax_releases.html\n](https://storage.googleapis.com/jax-releases/jax_releases.html/n)  touch COLABFOLD_READY\nfi\n\n# Download params (~1min)\npython -m colabfold.download\n\n# setup conda\nif [ ${USE_AMBER} == "True" ] || [ ${USE_TEMPLATES} == "True" ]; then\n  if [ ! -f CONDA_READY ]; then\n    wget -qnc [https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh\n](https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh/n)    bash Miniconda3-latest-Linux-x86_64.sh -bfp /usr/local 2>&1 1>/dev/null\n    rm Miniconda3-latest-Linux-x86_64.sh\n    touch CONDA_READY\n  fi\nfi\n# setup template search\nif [ ${USE_TEMPLATES} == "True" ] && [ ! -f HH_READY ]; then\n  conda install -y -q -c conda-forge -c bioconda kalign2=2.04 hhsuite=3.3.0 python=3.7 2>&1 1>/dev/null\n  touch HH_READY\nfi\n# setup openmm for amber refinement\nif [ ${USE_AMBER} == "True" ] && [ ! -f AMBER_READY ]; then\n  conda install -y -q -c conda-forge openmm=7...

4 frames
<decorator-gen-103> in shebang(self, line, cell)

[/usr/local/lib/python3.10/dist-packages/IPython/core/magics/script.py](https://localhost:8080/#) in shebang(self, line, cell)
    243             sys.stderr.flush()
    244         if args.raise_error and p.returncode!=0:
--> 245             raise CalledProcessError(p.returncode, cell, output=out, stderr=err)
    246 
    247     def _run_script(self, p, cell, to_close):

CalledProcessError: Command 'b'\nset -e\n\nUSE_AMBER=$1\nUSE_TEMPLATES=$2\n\n\nif [ ! -f COLABFOLD_READY ]; then\n  # install dependencies\n  # We have to use "--no-warn-conflicts" because colab already has a lot preinstalled with requirements different to ours\n  pip install -q --no-warn-conflicts "colabfold[alphafold-minus-jax] @ git+https://github.com/sokrypton/ColabFold"\n  # high risk high gain\n  pip install -q "jax[cuda11_cudnn805]>=0.3.8,<0.4" -f [https://storage.googleapis.com/jax-releases/jax_releases.html\n](https://storage.googleapis.com/jax-releases/jax_releases.html/n)  touch COLABFOLD_READY\nfi\n\n# Download params (~1min)\npython -m colabfold.download\n\n# setup conda\nif [ ${USE_AMBER} == "True" ] || [ ${USE_TEMPLATES} == "True" ]; then\n  if [ ! -f CONDA_READY ]; then\n    wget -qnc [https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh\n](https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh/n)    bash Miniconda3-latest-Linux-x86_64.sh -bfp /usr/local 2>&1 1>/dev/null\n    rm Miniconda3-latest-Linux-x86_64.sh\n    touch CONDA_READY\n  fi\nfi\n# setup template search\nif [ ${USE_TEMPLATES} == "True" ] && [ ! -f HH_READY ]; then\n  conda install -y -q -c conda-forge -c bioconda kalign2=2.04 hhsuite=3.3.0 python=3.7 2>&1 1>/dev/null\n  touch HH_READY\nfi\n# setup openmm for amber refinement\nif [ ${USE_AMBER} == "True" ] && [ ! -f AMBER_READY ]; then\n  conda install -y -q -c conda-forge openmm=7.5.1 python=3.7 pdbfixer 2>&1 1>/dev/null\n  touch AMBER_READY\nfi\n'' returned non-zero exit status 1.

**Comment by shivraj10** [comment]
how did this error get solved? I too am facing the same issue.

**Comment by Jzurn-ksu** [comment]
I only experienced this problem on an older version of the workbook. When you google search for the alphafold batch it points to the older workbook. If you access the most recent release accessed through the github link (https://colab.research.google.com/github/sokrypton/ColabFold/blob/main/batch/AlphaFold2_batch.ipynb) you don't run into the problem.

**Comment by milot-mirdita** [comment]
What search term did you look for and which broken notebook did you land on?

**Comment by shivraj10** [comment]
Actually I was having the same error in alphafold2.ipynb
