### ISSUE TITLE
Wrong .a3m format for hmmer

### ISSUE THREAD

**Issue by DimaMolod** [sokrypton/ColabFold#528]
Hi ColabFold!
As you might remember, we are using mmseqs2 API from within AlphaPulldown for the creation of AF features.
However, recently this feature stopped working because hmmer is unable to parse .a3m files from the web service:
`hmmbuild --amino /g/kosinski/dima/output.hmm /g/kosinski/dima/wrong_format.a3m
Alignment input open failed.
   couldn't guess alignment input format - doesn't even look like selex
   while reading file /g/kosinski/dima/wrong_format.a3m`

Upon inspection, we found that this is caused by the first line in the file:
`#158    1`
If I remove this line manually, hmmbuild works as expected.
I also attach the full a3m file.
[wrong_format.a3m.zip](https://github.com/sokrypton/ColabFold/files/13523561/wrong_format.a3m.zip)
(sorry for the stupid names :-)
Could this line be removed on your side or should we correct it ourselves? 
Many thanks!
Best regards,
Dima

**Comment by milot-mirdita** [comment]
I don't think HMMER supports A3M. You need to convert the alignments to a2m or fasta before passing them to HMMER (you can use reformat.pl from HHsuite for format conversion).
We require the "superheader" for our tools to work, if you want to use them with your own pipeline, please remove them.

**Comment by DimaMolod** [comment]
Thanks @milot-mirdita I think it solved our problem
