### ISSUE TITLE
Error Amber-relax

### ISSUE THREAD

**Issue by MFSeidl** [sokrypton/ColabFold#53]
Hello, 

I am trying to refine my structure predictions using Amber relax (in the alphafold2_advance book). However, I am getting the following error, both for my own structure as well as for the test sequence/structure:

```
UnfilteredStackTrace                      Traceback (most recent call last)

<ipython-input-16-404fe963ee1d> in <module>()
     63               max_outer_iterations=20)
---> 64           relaxed_pdb_lines, _, _ = amber_relaxer.process(prot=outs[key]["unrelaxed_protein"])
     65           with open(pred_output_path, 'w') as f:

33 frames

UnfilteredStackTrace: TypeError: take requires ndarray or scalar arguments, got <class 'list'> at position 0.

The stack trace below excludes JAX-internal frames.
The preceding is the original exception that occurred, unmodified.

--------------------


The above exception was the direct cause of the following exception:

TypeError                                 Traceback (most recent call last)

/usr/local/lib/python3.7/dist-packages/jax/_src/numpy/lax_numpy.py in _check_arraylike(fun_name, *args)
    557                     if not _arraylike(arg))
    558     msg = "{} requires ndarray or scalar arguments, got {} at position {}."
--> 559     raise TypeError(msg.format(fun_name, type(arg), pos))
    560 
    561 def _check_no_float0s(fun_name, *args):

TypeError: take requires ndarray or scalar arguments, got <class 'list'> at position 0.
```
Could you maybe help me figure out what's going on? Thank you very much!

**Comment by sokrypton** [comment]
can you try in our advanced_beta notebook here:
https://colab.research.google.com/github/sokrypton/ColabFold/blob/main/beta/AlphaFold2_advanced_beta.ipynb

**Comment by MFSeidl** [comment]
Thanks - I will try as soon as possible (currently cannot connect to GPU). 

Maybe naive question, but is it possible to access the previous results (the MSA and structures) because it seems these are gone?

**Comment by zach-hensel** [comment]
I think this and also #54 can be fixed by following along here https://github.com/YoshitakaMo/localcolabfold/issues/8#issuecomment-930799785

I guess this broke for new localcolabfold installs before colabfold, and then something jax changed on the colab image.

**Comment by sokrypton** [comment]
looks like jax update on google-colab broke alphafold (jax now requires np arrays instead of lists). The jax authors updated alpbafold to fix this. We've updated our copy of alphafold. So all should be good now!
