### ISSUE TITLE
AlphaFold Colab (DeepMind version) crash at MSA assembly stage

### ISSUE THREAD

**Issue by jfbazan** [sokrypton/ColabFold#536]
DeepMind's AF Colab seems to crash just as it's trying to run the 'Search against Genetic Databases' stage (obviously before AF's prediction is actually run), with the following error message (below). Thx in advance for your expert insights..

---------------------------------------------------------------------------
SymbolAlreadyExposedError                 Traceback (most recent call last)
<ipython-input-4-f1fdee26350e> in <cell line: 27>()
     25 import py3Dmol
     26 
---> 27 from alphafold.model import model
     28 from alphafold.model import config
     29 from alphafold.model import data

22 frames
/opt/conda/lib/python3.10/site-packages/tensorflow/python/util/tf_export.py in set_attr(self, func, api_names_attr, names)
    362     if api_names_attr in func.__dict__:
    363       if not self._allow_multiple_exports:
--> 364         raise SymbolAlreadyExposedError(
    365             'Symbol %s is already exposed as %s.' %
    366             (func.__name__, getattr(func, api_names_attr)))  # pylint: disable=protected-access

SymbolAlreadyExposedError: Symbol Zeros is already exposed as ().

**Comment by milot-mirdita** [comment]
Please post issues in DeepMind's issue tracker for their notebooks.
