### ISSUE TITLE
Error at input features and predict structure stage 

### ISSUE THREAD

**Issue by MARCOCRISCI** [sokrypton/ColabFold#54]
running model_1
---------------------------------------------------------------------------
UnfilteredStackTrace                      Traceback (most recent call last)
<ipython-input-7-af48741e914e> in <module>()
     50                          model_params=model_params, use_model=use_model,
---> 51                          do_relax=use_amber)

35 frames
UnfilteredStackTrace: TypeError: take requires ndarray or scalar arguments, got <class 'list'> at position 0.

The stack trace below excludes JAX-internal frames.
The preceding is the original exception that occurred, unmodified.

--------------------

The above exception was the direct cause of the following exception:

TypeError                                 Traceback (most recent call last)
/usr/local/lib/python3.7/dist-packages/jax/_src/numpy/lax_numpy.py in _check_arraylike(fun_name, *args)
    557                     if not _arraylike(arg))
    558     msg = "{} requires ndarray or scalar arguments, got {} at position {}."
--> 559     raise TypeError(msg.format(fun_name, type(arg), pos))
    560 
    561 def _check_no_float0s(fun_name, *args):

TypeError: take requires ndarray or scalar arguments, got <class 'list'> at position 0.

**Comment by sokrypton** [comment]
Should be fixed now! Reopen if not.
