### ISSUE TITLE
Tool boxes after google login disappeared

### ISSUE THREAD

**Issue by tomwu1495** [sokrypton/ColabFold#542]
## Current Behavior

Tool boxes, such as Runtime, disappeared after google login. I cannot run the program.

## Steps to Reproduce (for bugs)
Please make sure to reproduce the issue after a "Factory Reset" in Colab. 
If running locally ypdate you local installation `colabfold_batch` to the newest version.
Please provide your input if you can share it. 

## ColabFold Output (for bugs)
Please make sure to also post the complete ColabFold output. You can use gist.github.com for large output.

## Context
Providing context helps us come up with a solution and improve our documentation for the future.

## Your Environment
Include as many relevant details about the environment you experienced the bug in.
* Git commit used
* If you run it on a local system. Please add the server specifications
* Operating system and version:

**Comment by milot-mirdita** [comment]
Could you make a screenshot?

**Comment by tomwu1495** [comment]
![image](https://github.com/sokrypton/ColabFold/assets/154864367/6e3cb0ec-ff0b-4fbf-a534-f397941a8341)

**Comment by tomwu1495** [comment]
> Could you make a screenshot?

Can you see it above?

**Comment by milot-mirdita** [comment]
![Screenshot 2023-12-26 at 14 47 27](https://github.com/sokrypton/ColabFold/assets/63657/01503865-b3c2-4dad-8a77-7ba16c73576b)
You have to press this caret on the right to show the toolbar again.

**Comment by tomwu1495** [comment]
> ![Screenshot 2023-12-26 at 14 47 27](https://private-user-images.githubusercontent.com/63657/292812292-01503865-b3c2-4dad-8a77-7ba16c73576b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM1Njk5OTcsIm5iZiI6MTcwMzU2OTY5NywicGF0aCI6Ii82MzY1Ny8yOTI4MTIyOTItMDE1MDM4NjUtYjNjMi00ZGFkLThhNzctN2JhMTZjNzM1NzZiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI2VDA1NDgxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJiNmI0MmFjNDQ3MWY3ZThjYmI3Yjk5ODk3ZmY4ZDdkOWFkNDEwMzU4YzNlNTFhMzYwMzAyYmU5NmQzYzM5ZmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Hy5FS9b2wtU5RUFiA5881onIqDNxLmUJMsQ0nsNfJfE) You have to press this caret on the right to show the toolbar again.

Thanks lot! i'm new here.

**Comment by milot-mirdita** [comment]
No problem!
