### ISSUE TITLE
SymbolAlreadyExposedError: Symbol Ones is already exposed as ()

### ISSUE THREAD

**Issue by Saddy48** [sokrypton/ColabFold#543]
I was trying to check the simplified version of AF2 v2.3.2 by using the default protein sequence given in the query box. It was fine till last week but when I tried with different sequence it started showing this error and then now its not able to predict structure of even default query sequence. Thank you in advance for your kind help!

    362     if api_names_attr in func.__dict__:
    363       if not self._allow_multiple_exports:
--> 364         raise SymbolAlreadyExposedError(
    365             'Symbol %s is already exposed as %s.' %
    366             (func.__name__, getattr(func, api_names_attr)))  # pylint: disable=protected-access

SymbolAlreadyExposedError: Symbol Ones is already exposed as ().

**Comment by milot-mirdita** [comment]
Which notebook is this?

**Comment by Saddy48** [comment]
I am attaching a link to the notebook. Please click here
<https://colab.research.google.com/github/deepmind/alphafold/blob/main/notebooks/AlphaFold.ipynb>
.

**Comment by milot-mirdita** [comment]
Please ask in the DeepMind GitHub issues for support with their notebook. This issue tracker is only for the various ColabFold notebooks.

**Comment by Saddy48** [comment]
Notebook name is AlphaFold2 (from Deepmind).

**Comment by Saddy48** [comment]
Ok, Thank you.
