### ISSUE TITLE
Running with (A3M input + custom_template_path + is_complex) gives HHsearch error

### ISSUE THREAD

**Issue by huhlim** [sokrypton/ColabFold#555]
## Expected Behavior
A given input paired+unpaired MSA is unserialized, and resulting `unpaired_msa`s are used further for `mk_template` to search templates against custom_templates.

## Current Behavior
`unpaired_msa` does not contain the query sequence, so parsing HHsearch output (.hhr file) fails. 

## Steps to Reproduce (for bugs)
Please make sure to reproduce the issue after a "Factory Reset" in Colab. 
If running locally ypdate you local installation `colabfold_batch` to the newest version.
Please provide your input if you can share it. 

`colabfold_batch [MSA] [RESULT] --templates --custom-template-path [TEMPLATE_DIR]`
For example, 
`colabfold_batch 8x0t_c5054_0.a3m 8x0t.output --templates --custom-template-path 8x0t_template`
Input files are in the ZIP file. 
[8x0t.zip](https://github.com/sokrypton/ColabFold/files/13991266/8x0t.zip)

Or, using Google Colab notebook, please check the attached notebook file.
- template_mode = "custom" and provide 8x0t.cif
- msa_mode = "custom" and provide 8x0t_c5054_0.a3m

## ColabFold Output (for bugs)
Please make sure to also post the complete ColabFold output. You can use gist.github.com for large output.
```
2024-01-19 15:45:03,942 Running on GPU
2024-01-19 15:45:03,946 Found 5 citations for tools or databases
2024-01-19 15:45:04,301 Query 1/1: 8x0t_c5054_0.custom (length 579)
2024-01-19 15:45:23,837 Could not get MSA/templates for 8x0t_c5054_0.custom: Could not parse query line   81 LQMNSLRAEDTAVYYCARY--YPYFISYYSKmeAMDYWGQGTLVTVSSASTKGPSVFPLAPSSKSTSGGTAALGCLVKDY  158 (228)
Traceback (most recent call last):
  File "/content/colabfold/batch.py", line 1461, in run
    = get_msa_and_templates(jobname, query_seqs_unique, unpaired_msa, result_dir, 'single_sequence', use_templates,
  File "/content/colabfold/batch.py", line 781, in get_msa_and_templates
    template_feature = mk_template(
  File "/content/colabfold/batch.py", line 133, in mk_template
    hhsearch_hits = pipeline.parsers.parse_hhr(hhsearch_result)
  File "/content/alphafold/data/parsers.py", line 505, in parse_hhr
    hits.append(_parse_hhr_hit(lines[block_starts[i]:block_starts[i + 1]]))
  File "/content/alphafold/data/parsers.py", line 446, in _parse_hhr_hit
    groups = _get_hhr_line_regex_groups(patt, line[17:])
  File "/content/alphafold/data/parsers.py", line 379, in _get_hhr_line_regex_groups
    raise RuntimeError(f'Could not parse query line {line}')
RuntimeError: Could not parse query line   81 LQMNSLRAEDTAVYYCARY--YPYFISYYSKmeAMDYWGQGTLVTVSSASTKGPSVFPLAPSSKSTSGGTAALGCLVKDY  158 (228)
2024-01-19 15:45:23,842 Done
```
## Context
Providing context helps us come up with a solution and improve our documentation for the future.
`unserialize_msa` in batch.py 
https://github.com/sokrypton/ColabFold/blob/941feece178db14c9af1580eefbf4a8fe4e5b5af/colabfold/batch.py#L1116-L1131
The query sequence satisfies the `if` statement, so it is not added to `unpaired_msa`. Then, the `unpaired_msa` without the query sequence, while the first sequence has lowercase amino acids, is passed to `HHsearch.query`.
This might be resolved in either way:
(1) adding the query sequence to `a3m_lines` in `mk_template` prior to `HHsearch.query`.
(2) adding the query sequence to `unpaired_msa` in `unserialize_msa`.
I am not sure the solution (2) will cause issues for further processes.

## Your Environment
Include as many relevant details about the environment you experienced the bug in.
* Git commit used
* If you run it on a local system. Please add the server specifications
* Operating system and version:

**Comment by hyeh20** [comment]
Hi @huhlim, did you eventually resolve this? I'm also facing the same error.

**Comment by hyeh20** [comment]
It looks like a workaround (at least in my case) is to delete the second entry in the a3m file. Not a great solution, but is enough for me for now. This error also only seems to be reproducible for certain sequence queries, do you happen to be querying with an antibody sequence?

**Comment by YoshitakaMo** [comment]
Thank you for reporting this issue, @huhlim and @hyeh20. This issue is critical for the structural prediction of trimer or higher.
As you suspected, the processing of function `unserialize_msa` caused the bug. More precisely, the splitting of `paired_msa` and `unpaired_msa` was not done correctly when the input a3m file was trimer or higher. By changing the condition at line 1120 to `sum(has_amino_acid) > 1`, paired and unpaired MSAs were correctly splitted. I confirmed that this issue was resolved with the example you provided, "8x0t."

I've pushed the fix now (https://github.com/sokrypton/ColabFold/commit/f1f6a578fbb987149d29e942f68e7065c7407094). Please try again after updating your ColabFold.

**Comment by huhlim** [comment]
The fix resolves the issue. Thank you for addressing the issue.
