### ISSUE TITLE
Upload box for template does not appear

### ISSUE THREAD

**Issue by NakiaPolidori** [sokrypton/ColabFold#556]
## Expected Behavior
After selecting the template option, the upload box should appear
## Current Behavior
The box does not appear even after few attempts
## Steps to Reproduce (for bugs)
Please make sure to reproduce the issue after a "Factory Reset" in Colab. 
If running locally ypdate you local installation `colabfold_batch` to the newest version.
Please provide your input if you can share it. 

## ColabFold Output (for bugs)
Please make sure to also post the complete ColabFold output. You can use gist.github.com for large output.

## Context
Providing context helps us come up with a solution and improve our documentation for the future.

## Your Environment
Include as many relevant details about the environment you experienced the bug in.
* Git commit used
* If you run it on a local system. Please add the server specifications
* Operating system and version:

**Comment by milot-mirdita** [comment]
The upload box only appears after running the cell. It also appears under the cell.

Did you either hit "Run All", or ran each cell individually?

**Comment by NakiaPolidori** [comment]
No because it was not specified on the notes! Thank you for the clarification!
