### ISSUE TITLE
run AMBER relaxation within Docker

### ISSUE THREAD

**Issue by xing-he529** [sokrypton/ColabFold#558]
hello, thank you so much for your amazing job on Colabfold. 

I'm currently running ColabFold within Docker using the given command, but I didn't get the relaxed result. I'm wondering how I can run AMBER relaxation within Docker?

**Comment by milot-mirdita** [comment]
Did you pass the `--amber` or `--num-relax` parameter to `colabfold_batch`? If yes, what was the error message?
