### ISSUE TITLE
[BUG] batch error when colabfold_search --use-templates in local search

### ISSUE THREAD

**Issue by lshilab** [sokrypton/ColabFold#567]
When running the local `colabfold_search`  with the `--use-templates 1` flag  encounters an error. This particular issue has been previously documented in issue #560 and was resolved for single input gene in "Fix template search #565"; however, a problem persists when conducting batch searches.

Upon executing `colabfold_search --use-templates 1` on an input file named `test.csv`, the following traceback is encountered:

```plaintext
# test.csv: input file
id,sequence
raf,PSKTSNTIRVFLPNKQRTVVNVRNGMSLHDCLMKALKVRGLQPECCAVFRLLHEHKGKKARLDWNTDAASLIGEELQVDFL
raf2,PSKTSNTIRVFLPNKQRTVVNVRNGMSLHDCLMKALKVRGLQPECCAVFRLLHEHKGKKARLDWNTDAASLIGEELQVDFLLL

Traceback (most recent call last):
  File "bin/colabfold_search", line 8, in <module>
    sys.exit(main())
  File "mmseqs/search.py", line 385, in main
    os.rename(
FileNotFoundError: [Errno 2] No such file or directory: 'test_output/pdb100_230517.m8' -> 'test_output/raf2_pdb100_230517.m8'.
```

The inference drawn from this error suggests that during the batch processing, there seems to be an inconsistency in renaming the intermediate search results. It appears that while searching for the second sequence, the program attempts to rename a file 'pdb100_230517.m8' to include a unique identifier ('raf2_'), but the original file cannot be found. The renaming operation, as seen in line 384 of the `search.py` script:

```python
if args.use_templates:
    os.rename(
        args.base.joinpath(f"{args.db2}.m8"),
        args.base.joinpath(f"{safe_filename(raw_jobname)}_{args.db2}.m8"),
    )
```

happens post-search completion to ensure each output is uniquely identified. However, it seems this process might not be correctly synchronized with the writing and subsequent retrieval of files, leading to the FileNotFoundError.

In the script `search.py` from line 111, the `run_mmseqs` function is being invoked to handle a step in the batch processing of sequences using the `colabfold_search` tool. The function call involves converting and aligning results against a specific template database with the following arguments:

```python
run_mmseqs(mmseqs, [
    "convertalis",
    base.joinpath("prof_res"),  # Input profile residues file
    dbbase.joinpath(f"{template_db}"),  # Path to the template database
    base.joinpath("res_pdb"),  # Output directory or intermediate result?
    base.joinpath(f"{template_db}.m8"),  # Intermediate output file with .m8 format
	...
])
```

During batch searches, it seems that each iteration uses a common filename for the `.m8` intermediate output file, which is constructed as `base.joinpath(f"{template_db}.m8")`. In this case, it would resolve to `'pdb100_230517.m8'`.

This could indeed lead to overwriting issues if multiple sequence searches are writing to the same `.m8` file. 

Appreciate your attention to addressing this matter.

**Comment by hyeh20** [comment]
Also getting this issue on my end. Any fixes yet?

**Comment by YoshitakaMo** [comment]
Dear users,

Sorry for not addressing this issue for a long time. I've pushed the fix for this problem.
With this update, I ensured that the `colabfold_search` using `--use-templates` behaves as expected with the CSV file format.

```csv
id,sequence
3kud,MTEYKLVVVGAGGVGKSALTIQLIQNHFVDEYDPTIEDSYRKQVVIDGETCLLDILDTAGQEEYSAMRDQYMRTGEGFLCVFAINNTKSFEDIHQYREQIKRVKDSDDVPMVLVGNKCDLAARTVESRQAQDLARSYGIPYIETSAKTRQGVEDAFYTLVREIRQH:PSKTSNTIRVFLPNKQRTVVNVRNGMSLHDCLMKKLKVRGLQPECCAVFRLLHEHKGKKARLDWNTDAASLIGEELQVDFL
ras,MTEYKLVVVGAGGVGKSALTIQLIQNHFVDEYDPTIEDSYRKQVVIDGETCLLDILDTAGQEEYSAMRDQYMRTGEGFLCVFAINNTKSFEDIHQYREQIKRVKDSDDVPMVLVGNKCDLAARTVESRQAQDLARSYGIPYIETSAKTRQGVEDAFYTLVREIRQHKLRKLNPPDESGPGCMSCKCVLS
1BJP_2,PIAQIHILEGRSDEQKETLIREVSEAISRSLDAPLTSVRVIITEMAKGHFGIGGELASKVRR:PIAQIHILEGRSDEQKETLIREVSEAISRSLDAPLTSVRVIITEMAKGHFGIGGELASKVRR
1BJP_ras,PIAQIHILEGRSDEQKETLIREVSEAISRSLDAPLTSVRVIITEMAKGHFGIGGELASKVRR:PIAQIHILEGRSDEQKETLIREVSEAISRSLDAPLTSVRVIITEMAKGHFGIGGELASKVRR:MTEYKLVVVGAGGVGKSALTIQLIQNHFVDEYDPTIEDSYRKQVVIDGETCLLDILDTAGQEEYSAMRDQYMRTGEGFLCVFAINNTKSFEDIHQYREQIKRVKDSDDVPMVLVGNKCDLAARTVESRQAQDLARSYGIPYIETSAKTRQGVEDAFYTLVREIRQHKLRKLNPPDESGPGCMSCKCVLS
```

Command:

```
colabfold_search \
  --use-env 1 \
  --use-templates 1 \
  --db-load-mode 2 \
  --mmseqs /path/to/bin/mmseqs \
  --db2 pdb100_230517 \
  --threads 4 \
  test.csv \
  /path/to/databases/colabfold_env \
  test_output
```

The results:

```
$ ls -lt ./test_output
total 18668
-rw-r--r-- 1 moriwaki staffs   21754 Feb 22 10:23 1BJP_ras_pdb100_230517.m8
-rw-r--r-- 1 moriwaki staffs    3090 Feb 22 10:23 1BJP_2_pdb100_230517.m8
-rw-r--r-- 1 moriwaki staffs   18664 Feb 22 10:23 ras_pdb100_230517.m8
-rw-r--r-- 1 moriwaki staffs   19889 Feb 22 10:23 3kud_pdb100_230517.m8
-rw-r--r-- 1 moriwaki staffs 8075195 Feb 22 10:23 1BJP_ras.a3m
-rw-r--r-- 1 moriwaki staffs 1001542 Feb 22 10:23 1BJP_2.a3m
-rw-r--r-- 1 moriwaki staffs 4426861 Feb 22 10:23 ras.a3m
-rw-r--r-- 1 moriwaki staffs 5535278 Feb 22 10:23 3kud.a3m
```

If you want to predict the structures, using this CSV format is much faster than inputting each fasta file individually.

**Comment by lshilab** [comment]
Thank you, I have tested with the data you provided, and it works successfully, yielding the same results as yours. By the way, may I ask if template-based institutional forecasting can be run in batch mode? I have tested that it runs fine for a single protein, but when the input is a folder, it throws an error.

**Comment by YoshitakaMo** [comment]
> I have tested that it runs fine for a single protein, but when the input is a folder, it throws an error.

Sorry, We've not tested the feature for input as a folder. But I think that feature is in demand. We'll implement it soon.

**Comment by lshilab** [comment]
> > I have tested that it runs fine for a single protein, but when the input is a folder, it throws an error.
> 
> Sorry, We've not tested the feature for input as a folder. But I think that feature is in demand. We'll implement it soon.

Thanks, really appreciate it.
