### ISSUE TITLE
list index out of range error while running batch.ipynb

### ISSUE THREAD

**Issue by pweigele** [sokrypton/ColabFold#57]
I got the following error when running the prediction. I don't know if this is my fault.

IndexError                                Traceback (most recent call last)
<ipython-input-4-a76dac23e0b1> in <module>()
    314 queries.sort(key=lambda t: len(t[1]))
    315 import math
--> 316 crop_len = math.ceil(len(queries[0][1]) * 1.1)
    317 
    318 ### run

IndexError: list index out of range

**Comment by dsairam789** [comment]
Hi, @pweigele  could you kindly share how did you resolve your (list index out of range) problem?
