### ISSUE TITLE
Suggestion: Move .m8 file generation outside of template database to avoid read-only database conflict

### ISSUE THREAD

**Issue by MHvegholm** [sokrypton/ColabFold#571]
## Suggested change
`colabfold_search --use-templates=1 --db2 _/path/to/template/db_` currently generates `pdb100_*_Protein#.m8` files in the specified `--db2` database dictionary. I suggest moving file generation outside of databases (ex. path from argument 'base'), this prevents issues when databases are flagged as read-only, relevant when multiple users utilize the same databases

## Context
We run a HPC system with all colabfold docker images attaching a single read-only colabfold database to prevent accidental overwriting during simultaneous runs

**Comment by NickWoodall** [comment]
If you just use the database name only "pdb100_230517" instead of the full path it should put the .m8 file in the desired output directory instead the database directory. This is a quoted example from issue 563. Hope this helps.



> Currently, `colabfold_search` can generate a list of template PDB files together with MSA files. For example,
> 
> ```shell
> MMSEQS_PATH="/path/to/your/mmseqs2/for_colabfold"
> DATABASE_PATH="/mnt/databases"
> INPUTFILE="ras_raf.fasta"
> OUTPUTDIR="ras_raf"
> 
> colabfold_search \
>   --use-env 1 \
>   --use-templates 1 \
>   --db-load-mode 2 \
>   --db2 pdb100_230517 \
>   --mmseqs ${MMSEQS_PATH}/bin/mmseqs \
>   --threads 4 \
>   ${INPUTFILE} \
>   ${DATABASE_PATH} \
>   ${OUTPUTDIR}
> ```
>

**Comment by hyeh20** [comment]
> If you just use the database name only "pdb100_230517" instead of the full path it should put the .m8 file in the desired output directory instead the database directory. This is a quoted example from issue 563. Hope this helps.
> 
> > Currently, `colabfold_search` can generate a list of template PDB files together with MSA files. For example,
> > ```shell
> > MMSEQS_PATH="/path/to/your/mmseqs2/for_colabfold"
> > DATABASE_PATH="/mnt/databases"
> > INPUTFILE="ras_raf.fasta"
> > OUTPUTDIR="ras_raf"
> > 
> > colabfold_search \
> >   --use-env 1 \
> >   --use-templates 1 \
> >   --db-load-mode 2 \
> >   --db2 pdb100_230517 \
> >   --mmseqs ${MMSEQS_PATH}/bin/mmseqs \
> >   --threads 4 \
> >   ${INPUTFILE} \
> >   ${DATABASE_PATH} \
> >   ${OUTPUTDIR}
> > ```

Just heads up this works only if you run a single sequence. If you run it in a fasta or csv file with multiple sequence, there's still some file naming issues that will throw you an error.

**Comment by MHvegholm** [comment]
> If you just use the database name only "pdb100_230517" instead of the full path it should put the .m8 file in the desired output directory instead the database directory. This is a quoted example from issue 563. Hope this helps.
> 
> > Currently, `colabfold_search` can generate a list of template PDB files together with MSA files. For example,
> > ```shell
> > MMSEQS_PATH="/path/to/your/mmseqs2/for_colabfold"
> > DATABASE_PATH="/mnt/databases"
> > INPUTFILE="ras_raf.fasta"
> > OUTPUTDIR="ras_raf"
> > 
> > colabfold_search \
> >   --use-env 1 \
> >   --use-templates 1 \
> >   --db-load-mode 2 \
> >   --db2 pdb100_230517 \
> >   --mmseqs ${MMSEQS_PATH}/bin/mmseqs \
> >   --threads 4 \
> >   ${INPUTFILE} \
> >   ${DATABASE_PATH} \
> >   ${OUTPUTDIR}
> > ```

This indeed solved the issue I was facing 👍 
Thank you
