### ISSUE TITLE
colabfold_batch fails with "Could not get MSA/templates list index out of range" on MSA from colabfold_search

### ISSUE THREAD

**Issue by srom** [sokrypton/ColabFold#573]
I am attempting to fold protein complexes with 3 chains using `colabfold_batch`, [localcolabfold](https://github.com/YoshitakaMo/localcolabfold) and ColabFold 1.5.2. 

I am running `colabfold_batch` with MSAs computed with `colabfold_search`. Yet, I am getting the following error:

```
Could not get MSA/templates for Q9Y8I1__Q9Y8I2__Q5JI66: list index out of range
Traceback (most recent call last):
  File "/gpfs/easybuild/prod/software/ColabFold/1.5.2-foss-2022a-CUDA-11.7.0/lib/python3.10/site-packages/colabfold/batch.py", line 1374, in run
    = unserialize_msa(a3m_lines, query_sequence)
  File "/gpfs/easybuild/prod/software/ColabFold/1.5.2-foss-2022a-CUDA-11.7.0/lib/python3.10/site-packages/colabfold/batch.py", line 1121, in unserialize_msa
    paired_msa[j] += ">" + header_no_faster_split[j] + "\n"
IndexError: list index out of range
```

## Commands

```
colabfold_search \
	--db1 uniref30_2302_db  \
	--db2 colabfold_envdb_202108_db \
	--mmseqs <path to mmseqs2> \
	--threads 64 \
	<input fasta> \
	<path to colabfold databases> \
	msa_folder/
```

```
colabfold_batch \
	--num-models 1 \
	--num-recycle 2 \
	--model-type alphafold2_multimer_v3 \
        msa_folder/
        predictions_folder/
```

## Excerpt from one of the a3m alignment files causing an issue

```
#67,67,33	1,1,1
>Q9Y8I1__Q9Y8I2__Q5JI66	Q9Y8I1__Q9Y8I2__Q5JI66	Q9Y8I1__Q9Y8I2__Q5JI66
MAELPIAPVDRLIRKAGAERVSEDAAKVLAEYLEEYAIELSKKAVDFARHAGRKTVKAEDIKLAIKAMAELPIAPVDRLIRKAGAARVSEEAAKVLAEHLEEKALEIAKKAVALAQHAGRKTVKAEDIKLAIKSMIFIAHSRYKEPRKALLLLKVTEEGNAEIAVKL
>UniRef100_A0A6G1WY19	UniRef100_A0A6G1WY19
MVELPVAAIDRIIRKSGARRVSESAAVALAEVLEERALTIANEAAKLAEHAGRRTVRDVDIRLAVK-MVELPVAAIDRIIRKSGARRVSESAAVALAEVLEERALTIANEAAKLAEHAGRRTVRDVDIRLAVK-
>UniRef100_A0A520KCW3	UniRef100_A0A520KCW3
MMALPIATIEKIIRKAGAYRVSKGAAKELSEFLEDWGVEIAQEAMRLAEHAGRKTVKSEDIELAIK-MMALPIATIEKIIRKAGAYRVSKGAAKELSEFLEDWGVEIAQEAMRLAEHAGRKTVKSEDIELAIK-
>UniRef100_A0A1V4YMI9	UniRef100_A0A1V4YMI9
MAELPIAPVGRIIKNAGAQRISDDAKEALAKSLEEKGEEIAKKAVELAKHAGRKTVKADDIELAVKAMAELPIAPVGRIIKNAGAQRISDDAKEALAKSLEEKGEEIAKKAVELAKHAGRKTVKADDIELAVKA
```

## Environment

* ColabFold version 1.5.2, running locally, installed on university HPC with [easybuild ColabFold recipe 1.5.2-foss-2022a-CUDA-11.7.0](https://docs.easybuild.io/version-specific/supported-software/?h=colabfold)
* MMSeqs2 version (for colabfold_search): [bb0a1b3569b9fe115f3bf63e5ba1da234748de23](https://github.com/soedinglab/MMseqs2/commit/bb0a1b3569b9fe115f3bf63e5ba1da234748de23)
* Operating system and version: RedHat enterprise 8 (university HPC)
* Running on A100 nvidia GPU with CUDA 11.7

**Comment by YoshitakaMo** [comment]
Please test the latest commit of (Local)ColabFold (ver. 1.5.5). Currently some critical bugs around MSA generation and prediction have been fixed.

**Comment by srom** [comment]
I can confirm that using ColabFold 1.5.5 fixed the issue, thank you for your help!
