### ISSUE TITLE
Batch error

### ISSUE THREAD

**Issue by Pollock89** [sokrypton/ColabFold#58]
Hi,
I am trying to run the batch colab, but proteins with sizes above ~200 aas do not give a result. It crashes after printing _running model_1_. Then, I get _Your session crashed for an unknown reason._ and in the log it _says F external/org_tensorflow/tensorflow/compiler/xla/service/gpu/gemm_algorithm_picker.cc:118] Check failed: stream->parent()->GetBlasGemmAlgorithms(&algorithms)_ and _WARNING:root:kernel 30934950-7cf4-41bc-aa7d-7fbbef191947 restarted_
The same proteins I can predict without problems in the non-batch colab (MMseq2).
Is there some cap that I do not know about? I provide single fastas in the right folder. Shorter versions of the sampled proteins work. 
Thank you

**Comment by martin-steinegger** [comment]
Does this error still occur?

**Comment by martin-steinegger** [comment]
I close this for now. Please reopen it if the error still occurs.
