### ISSUE TITLE
Supplying alternative model weights

### ISSUE THREAD

**Issue by dthorburn** [sokrypton/ColabFold#593]
I am looking at fine tuning AF2, potentially using something like [alphafold_finetune](https://github.com/phbradley/alphafold_finetune) or using OpenFold (which should permit directly swapping weights between canonical AF2 and OF). 

If I was running colabfold locally or on a custom notebook, can I directly swap the default model weights?

**Comment by milot-mirdita** [comment]
OpenFold weights require a conversion step to work with ColabFold. We were waiting for the OF team to release an updated set of weights, as the initial monomer weights didn't perform as well as hoped.

In the meantime we have integrated the DeepFold weights. 

alphafold_finetune looks interesting, I was not aware of this project before.

**Comment by dthorburn** [comment]
Ah, that's unfortunate. I am just gearing up to benchmark their multimer and protein LLM monomer implementations. Hopefully they work well. 

Are scripts to enact the weights conversation available? I'm asking mostly because my existing pipelines leverage local ColabFold and it's been by far the easiest to install and most stable solution.

**Comment by sokrypton** [comment]
Openfold provides a script for converting to jax weights:
https://github.com/aqlaboratory/openfold/blob/main/scripts/convert_of_weights_to_jax.py

**Comment by dthorburn** [comment]
Must have missed that. Thank you for highlighting it for me.

**Comment by milot-mirdita** [comment]
Where the multimer weights released? I might have missed that

**Comment by milot-mirdita** [comment]
Yes, I've seen that but I hadn't seen any weights.
