### ISSUE TITLE
About the AlphaFold-Multimer

### ISSUE THREAD

**Issue by xiki-tempula** [sokrypton/ColabFold#60]
I'm interested in using the AlphaFold-Multimer from https://www.biorxiv.org/content/10.1101/2021.10.04.463034v1.full.pdf. I wonder if ColabFold/beta/AlphaFold2_advanced.ipynb is the implementation of this AlphaFold-Multimer? Thank you.

**Comment by sokrypton** [comment]
@deepmind has not yet released the weights for AlphaFold-Multimer, as soon as they do we'll add support for these models :D

**Comment by xvazquezc** [comment]
@sokrypton Just a heads up, the code for AlphaFold-Multimer has just been included in the 2.1.0 release.
https://github.com/deepmind/alphafold/releases/tag/v2.1.0

**Comment by xiki-tempula** [comment]
Thank you very much.

**Comment by konstin** [comment]
Complex modelling is now available! [AlphaFold2_complexes notebook](https://colab.research.google.com/github/sokrypton/ColabFold/blob/main/AlphaFold2_complexes.ipynb)
