### ISSUE TITLE
Clarification on MSA server RAM requirements

### ISSUE THREAD

**Issue by puddleglum56** [sokrypton/ColabFold#626]
Hello! We are looking at implementing the MSA server in-house for fast MSAs. The [wiki](https://github.com/sokrypton/ColabFold/wiki) states that a machine with 2TB RAM is recommended to store the pre-computed indexes in memory, whereas the [README](https://github.com/sokrypton/ColabFold?tab=readme-ov-file#generating-msas-for-large-scale-structurecomplex-predictions) indicates that the MSA databases take up to 1TB RAM. Additionally the [ColabFold paper](https://www.nature.com/articles/s41592-022-01488-1) states that a 768GB RAM server was used for MSAs.

My understanding is that the 2TB RAM configuration stores the indexes in memory, and is thus faster, whereas the 1TB RAM configuration stores the un-indexed databases in memory and computes the indexes on-the-fly? Could you give more clarity as far as the RAM requirements so that we can spec out an internal server?

Thank you!

**Comment by juliocesar-io** [comment]
Hey @puddleglum56. if still useful for reference I used a EC2 instance type `r7i.23xlarge` vCPU 96, 768GB of RAM and 1.2TB of disk space and I was able to run the MSA Server just fine using Uniref30+Colabfold_env.

**Comment by puddleglum56** [comment]
Hey @juliocesar-io thanks for getting back to me. For everyone else, we ended up going with a 2TB RAM box to be safe, although this was probably overkill

**Comment by puddleglum56** [comment]
Hey @juliocesar-io thanks for getting back to me. For everyone else, we ended up going with a 2TB RAM box to be safe, although this was probably overkill
