### ISSUE TITLE
Colabfold install on `aarch64` with GPU support

### ISSUE THREAD

**Issue by wahabk** [sokrypton/ColabFold#637]
## Expected Behavior

Colabfold should be installable on `aarch64`. I am working on porting this to a GraceHopper (GH200) system but there are x86 dependencies. The main issue is `tensorflow-cpu`. Tensorflow only builds wheels for `aarch64` without GPU support https://www.tensorflow.org/install/pip

Furthermore there are x86 conda dependencies in the Dockerfile and in `localcolabfold`:

> bash Mambaforge-Linux-x86_64.sh -bfp /usr/local && \

Mainly creating this issue to understand whether `aarch64` support is planned and how I can help with this. Conda dependencies can be fixed with `$(uname -m)`.

## Current Behavior

```
ERROR: Could not find a version that satisfies the requirement tensorflow-cpu<3.0.0,>=2.12.1; sys_platform != "darwin" (from colabfold) (from versions: none)
ERROR: No matching distribution found for tensorflow-cpu<3.0.0,>=2.12.1; sys_platform != "darwin"
```

## Steps to Reproduce (for bugs)
Please make sure to reproduce the issue after a "Factory Reset" in Colab. 
If running locally ypdate you local installation `colabfold_batch` to the newest version.
Please provide your input if you can share it. 

```
pip install -q --no-warn-conflicts "colabfold[alphafold-minus-jax] @ git+https://github.com/sokrypton/ColabFold"
```

## ColabFold Output (for bugs)
Please make sure to also post the complete ColabFold output. You can use gist.github.com for large output.

NA can't install colabfold.

## Context
Providing context helps us come up with a solution and improve our documentation for the future.

## Your Environment
Include as many relevant details about the environment you experienced the bug in.
* Git commit used
* If you run it on a local system. Please add the server specifications
* Operating system and version:

Colabfold Version 1.5.5

```bash
$ uname -a
Linux nid001041 5.14.21-150500.55.31_13.0.53-cray_shasta_c_64k #1 SMP Mon Dec 4 22:56:47 UTC 2023 (03d3f83) aarch64 aarch64 aarch64 GNU/Linux
$ cat /etc/os-release 
NAME="SLES"
VERSION="15-SP5"
VERSION_ID="15.5"
PRETTY_NAME="SUSE Linux Enterprise Server 15 SP5"
ID="sles"
ID_LIKE="suse"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:suse:sles:15:sp5"
DOCUMENTATION_URL="https://documentation.suse.com/"
```

**Comment by milot-mirdita** [comment]
I've been working on getting this running but I am stuck on the conda tensorflow package not offering ARM builds (https://github.com/conda-forge/tensorflow-feedstock/issues/136). You can still install ColabFold manually with pip. Pip has aarch64 builds for jaxlib.

**Comment by wahabk** [comment]
Thanks @milot-mirdita. I'm aware of that feedstock issue and will try to `conda-build`.

Could you please clarify what you mean by "install manually with pip"? I'm still getting the error:

```bash
$ pip install -q --no-warn-conflicts 'colabfold[alphafold] @ git+https://github.com/sokrypton/ColabFold'
ERROR: Could not find a version that satisfies the requirement tensorflow-cpu<3.0.0,>=2.12.1; sys_platform != "darwin" (from colabfold) (from versions: none)
ERROR: No matching distribution found for tensorflow-cpu<3.0.0,>=2.12.1; sys_platform != "darwin"
```
