### ISSUE TITLE
What should I do if I just want to use colabfold_search with mmseqs-gpu?

### ISSUE THREAD

**Issue by TheChosenOneJG** [sokrypton/ColabFold#670]
Notice that MMseqs-gpu is open-sourced. So I want to know how to replace `mmseqs-cpu` with `mmseqs-gpu` among expandable search databases. Can the expandable search databases transform to gpu-databases? Do other commands, such as `expandaln` , `align` and `filterresult` , need to modify? 
Thank you in advance!

**Comment by milot-mirdita** [comment]
We should have all the scripts and changes ready and uploaded to this repository by next week.

**Comment by TheChosenOneJG** [comment]
> We should have all the scripts and changes ready and uploaded to this repository by next week.

Looking forward to it! Thank you for your reply! ^_^
