### ISSUE TITLE
Error while running Install software in AlphaFold2_advanced

### ISSUE THREAD

**Issue by Markerbo** [sokrypton/ColabFold#69]
**Error while running Install software in AlphaFold2_advanced.**

ImportError                               Traceback (most recent call last)
<ipython-input-1-195a3e52d4de> in <module>()
    100 import py3Dmol
    101 
--> 102 from alphafold.model import model
    103 from alphafold.model import config
    104 from alphafold.model import data

9 frames
/usr/local/lib/python3.7/dist-packages/tensorflow/_api/v2/compat/v1/data/experimental/service/__init__.py in <module>()
    361 import sys as _sys
    362 
--> 363 from tensorflow.python.data.experimental.ops.data_service_ops import ShardingPolicy
    364 from tensorflow.python.data.experimental.ops.data_service_ops import distribute
    365 from tensorflow.python.data.experimental.ops.data_service_ops import from_dataset_id

ImportError: cannot import name 'ShardingPolicy' from 'tensorflow.python.data.experimental.ops.data_service_ops' (/usr/local/lib/python3.7/dist-packages/tensorflow/python/data/experimental/ops/data_service_ops.py)

---------------------------------------------------------------------------
NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.

To view examples of installing some common dependencies, click the
"Open Examples" button below.

**Comment by milot-mirdita** [comment]
I applied a temporary fix. The advanced notebook should work again.
