### ISSUE TITLE
Cannot reshape a tensor with 2705220 elements to shape [6441,127,1]

### ISSUE THREAD

**Issue by chenxin199261** [sokrypton/ColabFold#7]
Hello，I am using this ipynb file on Colab
https://colab.research.google.com/github/sokrypton/ColabFold/blob/main/AlphaFold2.ipynb

When I did the _Gather input features, predict structure_ step. I found an error.

=============================================
Running model_1
InvalidArgumentError                      Traceback (most recent call last)
/usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/ops.py in _create_c_op(graph, node_def, inputs, control_inputs, op_def)
   1879   try:
-> 1880     c_op = pywrap_tf_session.TF_FinishOperation(op_desc)
   1881   except errors.InvalidArgumentError as e:

InvalidArgumentError: Cannot reshape a tensor with 2705220 elements to shape [6441,127,1] (818007 elements) for '{{node reshape_msa}} = Reshape[T=DT_INT32, Tshape=DT_INT32](Const_6, reshape_msa/shape)' with input shapes: [6441,420], [3] and with input tensors computed as partial shapes: input[1] = [6441,127,1].

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
12 frames
/usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/ops.py in _create_c_op(graph, node_def, inputs, control_inputs, op_def)
   1881   except errors.InvalidArgumentError as e:
   1882     # Convert to ValueError for backwards compatibility.
-> 1883     raise ValueError(str(e))
   1884 
   1885   return c_op
ValueError: Cannot reshape a tensor with 2705220 elements to shape [6441,127,1] (818007 elements) for '{{node reshape_msa}} = Reshape[T=DT_INT32, Tshape=DT_INT32](Const_6, reshape_msa/shape)' with input shapes: [6441,420], [3] and with input tensors computed as partial shapes: input[1] = [6441,127,1].

============================================================

My protein sequence is:

SMNPPPPETSNPNKPKRQTNQLQYLLRVVLKTLWKHQFAWPFQQPVDAVKLNLPDYYKIIKTPMDMGTIKKRLENNYYWNAQECIQDFNTMFTNCYIYNKPGDDIVLMAEALEKLFLQKINELPTEE

**Comment by sokrypton** [comment]
Hmmm... it worked for me. Were there any other options you enabled/disabled (compared to default)? Can you try "factory reset" and run all again?

**Comment by chenxin199261** [comment]
> Hmmm... it worked for me. Were there any other options you enabled/disabled (compared to default)? Can you try "factory reset" and run all again?

It worked after I restart the environment ! The second running failed.

**Comment by sokrypton** [comment]
For the "second running" are you changing the sequence?

**Comment by sokrypton** [comment]
Fixed it! You should be able to run again with second sequence without needing to factory reset.

Thanks for the report!
