### ISSUE TITLE
AlphaFold2_batch.ipynb Run Prediction Error

### ISSUE THREAD

**Issue by andypaige772** [sokrypton/ColabFold#71]
I am attempting to use the batch ColabFold notebook, but I received the following error message.

How can I resolve this issue? Thank you for your help.

Best
![Screen Shot 2021-11-10 at 6 49 26 PM](https://user-images.githubusercontent.com/60631605/141211934-9ae48e89-d3e1-4ca4-858d-a45df640f1d6.png)
,

**Comment by milot-mirdita** [comment]
I think I fixed the issue, however we will have to double check that everything is alright after the recent merge of the new code base (see https://twitter.com/thesteinegger/status/1458510244116451329).

**Comment by milot-mirdita** [comment]
Martin will update the issue later when he gets a chance to try it out.

**Comment by konstin** [comment]
This should be fixed. Please open a new issue if there are still problems with the installation
