### ISSUE TITLE
Missing form fields

### ISSUE THREAD

**Issue by gezmi** [sokrypton/ColabFold#75]
Hi,

I am using the AlphaFold2_mmseqs2 notebook and wanted to allow using templates.However, althought these lines exist in the code, they do not display:
```
#@markdown ### Advanced settings
msa_mode = "MMseqs2 (UniRef+Environmental)" #@param ["MMseqs2 (UniRef+Environmental)", "MMseqs2 (UniRef only)","single_sequence","custom"]
num_models = 5 #@param [1,2,3,4,5] {type:"raw"}
use_msa = True if msa_mode.startswith("MMseqs2") else False
use_env = True if msa_mode == "MMseqs2 (UniRef+Environmental)" else False
use_amber = False #@param {type:"boolean"}
use_templates = False 
```
![image](https://user-images.githubusercontent.com/13509667/141470818-e7bf7d81-d6e6-4004-9861-4f5261759326.png)

I tried with different browsers and they do not show. What could be the reason?

Thank you!
Julia

**Comment by milot-mirdita** [comment]
Hi, AF-multimer has introduced a few changes and we haven't finished integrating templates quite yet.

**Comment by martin-steinegger** [comment]
Templates should work now and are active.
