### ISSUE TITLE
RoseTTAFold Install step failed with undefined symbol (solution included)

### ISSUE THREAD

**Issue by SKleinfelter** [sokrypton/ColabFold#78]
RoseTTAFold install cell failed with this error:
OSError: /usr/local/lib/python3.7/dist-packages/torch_sparse/_convert_cuda.so: undefined symbol: _ZNK2at6Tensor5zero_Ev

Per this thread on github: https://github.com/pyg-team/pytorch_geometric/issues/3484
I restarted the runtime and replaced these two lines in the install cell:
    %shell pip install -q torch-scatter -f https://pytorch-geometric.com/whl/torch-1.9.0+cu111.html
    %shell pip install -q torch-sparse -f https://pytorch-geometric.com/whl/torch-1.9.0+cu111.html
with these two lines:
    %shell pip install -q torch-scatter -f https://pytorch-geometric.com/whl/torch-1.10.0+cu113.html
    %shell pip install -q torch-sparse -f https://pytorch-geometric.com/whl/torch-1.10.0+cu113.html

...and installation succeeded.

**Comment by sokrypton** [comment]
Thanks! Fix has been applied!
