### ISSUE TITLE
Wrong in single sequence mode 

### ISSUE THREAD

**Issue by quailwwk** [sokrypton/ColabFold#81]
Hi, I tried to run [AlphaFold2.ipynb](https://colab.research.google.com/github/sokrypton/ColabFold/blob/main/AlphaFold2.ipynb) in `single sequence` mode, but the result is completely same to `MMseq2 (UniRef only)` mode. 

Sequence:
```
GSHMSSVTIGKCYIQNRENGGRAFYNLGRKDLGIFTGKMYDDQIWSFQKSDTPGYYTIGRESKFLQYNGEQVIMSDIEQDTTLWSLEEVPEDKGFYRLLNKVHKAYLDYNGGDLVANKHQTESEKWILFKAY
```

config:
```
# single sequence mode
num_models=1
num_recycles=1
use_amber=False
use_msa=False
msa_mode=single_sequence
use_templates=False

# MMseq2 (UniRef only) mode
num_models=1
num_recycles=1
use_amber=False
use_msa=True
msa_mode=MMseqs2 (UniRef only)
use_templates=False
```

The top rows of pdb predicted by single-sequnce mode:
MODEL     1                                                                     
ATOM      1  N   GLY A   1     -16.476  23.049 -12.538  1.00 30.08           N  
ATOM      2  CA  GLY A   1     -17.257  22.145 -13.366  1.00 30.08           C  
ATOM      3  C   GLY A   1     -16.750  20.715 -13.331  1.00 30.08           C  
ATOM      4  O   GLY A   1     -15.586  20.456 -13.644  1.00 30.08           O

The top rows of pdb predicted by MMseqs mode:
MODEL     1                                                                     
ATOM      1  N   GLY A   1     -16.476  23.049 -12.538  1.00 30.08           N  
ATOM      2  CA  GLY A   1     -17.257  22.145 -13.366  1.00 30.08           C  
ATOM      3  C   GLY A   1     -16.750  20.715 -13.331  1.00 30.08           C  
ATOM      4  O   GLY A   1     -15.586  20.456 -13.644  1.00 30.08           O

**Comment by sokrypton** [comment]
How many sequences were found by MMseqs2? If none, than the answer should be identical.

**Comment by martin-steinegger** [comment]
Thank you for reporting this. I can confirm that "single_sequence" is currently not work. Will fix it soon.

**Comment by quailwwk** [comment]
~70 [https://drive.google.com/file/d/1LRmLAWBbUx-1Fyl4Bf9QurUaXbQMBSS1/view?usp=sharing](url)

> How many sequences were found by MMseqs2? If none, than the answer should be identical.

**Comment by martin-steinegger** [comment]
@quailwwk this should be resolved now. If you still have the same active session then you need to do a factory reset.
