### ISSUE TITLE
alphafold_mmseq multimer fails with single sequence msa

### ISSUE THREAD

**Issue by carlocamilloni** [sokrypton/ColabFold#82]
I get this error that I think it may be related to fact that I don't want to use sequences but only templates,
my input is that of an heterodimer using msa_mode single sequence + template

ValueError                                Traceback (most recent call last)
<ipython-input-3-b1110d0a69bd> in <module>()
     32     rank_mode="auto",
     33     pair_mode="unpaired+paired",
---> 34     stop_at_score=float(100),
     35 )

3 frames
<__array_function__ internals> in argmax(*args, **kwargs)

/usr/local/lib/python3.7/dist-packages/numpy/core/fromnumeric.py in _wrapfunc(obj, method, *args, **kwds)
     56 
     57     try:
---> 58         return bound(*args, **kwds)
     59     except TypeError:
     60         # A TypeError occurs if the object does have such a method in its

ValueError: attempt to get argmax of an empty sequence

**Comment by martin-steinegger** [comment]
This should work now in the [AlphaFold2_mmseqs2](https://colab.research.google.com/github/sokrypton/ColabFold/blob/main/AlphaFold2.ipynb) notebook
