### ISSUE TITLE
How to predict complexes using pip colabfold?

### ISSUE THREAD

**Issue by tony9664** [sokrypton/ColabFold#83]
I tried to split chains using colons and get this error:

Could not predict A: Invalid character in the sequence: :

**Comment by martin-steinegger** [comment]
@tony9664 how do you call colabfold and how does your input look like?

**Comment by tony9664** [comment]
I used the colabfold_batch executable like this

colabfold_batch bth_comp.fasta ./

In the fasta file I have four chains separated by 3 colons.

**Comment by martin-steinegger** [comment]
Could you try to provide the input as a `csv` formatted file:
Example: 
```
id,sequence
bla,PIAQIHILEGRSDEQKETLIREVSEAISRSLDAPLTSVRVIITEMAKGHFGIGGELASK:PIAQIHILEGRSDEQKETLIREVSEAISRSLDAPLTSVRVIITEMAKGHFGIGGELASK
```
The first line is a header line and the second consists of an identifier `bla` and a homomer with two chain. Each line in this file will result in a prediction.

**Comment by tony9664** [comment]
Thanks! This worked.
