### ISSUE TITLE
Dependencies errors

### ISSUE THREAD

**Issue by mauricirl** [sokrypton/ColabFold#86]
Hi, i get these errors runnig predictions on a sigle sequence

WARNING: Skipping colabfold as it is not installed.
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tensorflow-metadata 1.4.0 requires absl-py<0.13,>=0.9, but you have absl-py 0.13.0 which is incompatible.
google-colab 1.0.0 requires pandas~=1.1.0; python_version >= "3.0", but you have pandas 1.3.4 which is incompatible.
google-colab 1.0.0 requires requests~=2.23.0, but you have requests 2.26.0 which is incompatible.
datascience 0.10.6 requires folium==0.2.1, but you have folium 0.8.3 which is incompatible.
albumentations 0.1.12 requires imgaug<0.2.7,>=0.2.5, but you have imgaug 0.2.9 which is incompatible.

Plese help to fix it.

-- Maurizio

**Comment by konstin** [comment]
Hi, which notebook are you running, and do you get any errors when trying to run a prediction? In general these errors can be ignored, they come from preinstalled packages we do not use.

**Comment by mauricirl** [comment]
AlphaFold2_mmseqs2 
at
https://colab.research.google.com/github/sokrypton/ColabFold/blob/main/AlphaFold2.ipynb

It is stiil running ( 6 recyclings....) but looks OK so far.
