### ISSUE TITLE
where are the PAE data?

### ISSUE THREAD

**Issue by ttianchen** [sokrypton/ColabFold#89]
Hi,
Thanks for sharing the powerful tool.
I'm running Alphafold on a computer cluster, I wanted to make a PAE plot like those shown on Alphafold database and colab results. Where are these PAE data? Which file should I use?
Thanks

**Comment by martin-steinegger** [comment]
The AlphaFold2_mmseqs, colabfold_batch notebook provides now a json file with the PAE. Here is an example how to parse the json https://github.com/sokrypton/ColabFold/blob/main/utils/plot_scores.ipynb

**Comment by snoze** [comment]
Can we print final pLDDT score (not average per position) per model from this file?

**Comment by konstin** [comment]
Well the final pLDDT score is just the average over all pLDDT scores, so you can just read the array and take the mean
