### ISSUE TITLE
fasta database

### ISSUE THREAD

**Issue by hartrials** [sokrypton/ColabFold#9]
If I choose mmseqs2 (uniref + environmental), it should include SMAG and MetaEuk databases. Could you tell me the exact link of the two databases? Thank you!

**Comment by hartrials** [comment]
* SMAG
![image](https://user-images.githubusercontent.com/45934739/127012637-ba31fb62-f7ba-4083-b22d-06e9fc025402.png)
* MetaEuk
![image](https://user-images.githubusercontent.com/45934739/127012889-d5533d7d-b43e-444f-8f48-cc8c5b14b3e6.png)
There are many links of the two databases. Which database link do you use?

**Comment by milot-mirdita** [comment]
See martins edit above for filenames

**Comment by hartrials** [comment]
OK. Thank you very much for your quick reply! However, there are still doubts about the accurate FASTA database used.

**Comment by milot-mirdita** [comment]
We will describe the exact procedure used to construct the environmental database in the preprint we are preparing currently.

**Comment by hartrials** [comment]
OK, thanks!
