### ISSUE TITLE
warning and error message when using AF2mmseqs now (after the updates for multimer)

### ISSUE THREAD

**Issue by cajje** [sokrypton/ColabFold#92]
Hi! TheAF2/mmseqs presents a warning and error (see below) after upload of seq:seq just as in the instructions for a homooligomer followed by Run all.
WARNING: Skipping colabfold as it is not installed.
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tensorflow-metadata 1.4.0 requires absl-py<0.13,>=0.9, but you have absl-py 0.13.0 which is incompatible.
google-colab 1.0.0 requires pandas~=1.1.0; python_version >= "3.0", but you have pandas 1.3.4 which is incompatible.
google-colab 1.0.0 requires requests~=2.23.0, but you have requests 2.26.0 which is incompatible.
datascience 0.10.6 requires folium==0.2.1, but you have folium 0.8.3 which is incompatible.
albumentations 0.1.12 requires imgaug<0.2.7,>=0.2.5, but you have imgaug 0.2.9 which is incompatible.

I tried the reset to factory if it would work.
Caj

**Comment by martin-steinegger** [comment]
This has todo with our pip install. It should not be an issue. 
Please see https://github.com/sokrypton/ColabFold/issues/86

**Comment by martin-steinegger** [comment]
Should be fixed.
