### ISSUE TITLE
No such file or directory: '/usr/local/lib/python3.7/dist-packages/colabfold/stereo_chemical_props.txt'

### ISSUE THREAD

**Issue by dxzh0129** [sokrypton/ColabFold#94]
Hi! I got an error message in a recent run today (in the "Run Prediction" block): 
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.7/dist-packages/colabfold/stereo_chemical_props.txt'

This probably has to do with recent commits related to the path to this file...

Cheers

**Comment by martin-steinegger** [comment]
I reverted the change. Sorry for the inconvenience.

**Comment by utimcraig** [comment]
Hi- I have the same error today
