### ISSUE TITLE
ranking

### ISSUE THREAD

**Issue by ki3l3y** [sokrypton/ColabFold#96]
Hello! I noticed that ranking was added to each model. Is the best model the one with the lowest ranking? I had been choosing the best model based on highest model confidence, however the ranking does not correlate.

**Comment by martin-steinegger** [comment]
Do you still have this issue? Could you please share more information about it? 
Only rank is meaningful to determine the best model (Rank 1 = best ... Rank 5 = worse prediction). The model information can not be used to determine the prediction performance. It is just an extra info to know what model produced the prediction.

**Comment by martin-steinegger** [comment]
I am closing this for now. Please reopen it if the error still persists.
